### ISSUE TITLE
FR: Expose C++ functions WindowFromPoint and GetClientRect to API [DONE!]

### ISSUE THREAD

**Issue by juliansader** [reaper-oss/sws#1002]
ReaScripts do not currently have access to all the nifty C++ functions for getting information about windows.

It would be very helpful if SWS could expose these three functions to the API:
* WindowFromPoint
* GetClientRect 
* ScreenToClient

This would help me to 
* precisely position script GUIs within the MIDI editor and other windows, and
* obtain more detailed info about the mouse cursor context than BR_GetMouseCursorContext currently provides.

**Comment by juliansader** [comment]
I figured out how to do this myself!

I will soon upload these (and other) functions to SWS.

**Comment by mespotine** [comment]
Congratulations and thank you for your hard work :D

**Comment by nofishonfriday** [comment]
BR_Win32_WindowFromPoint() added in v2.10.0
The others are done by @juliansader's [own extension](https://forum.cockos.com/showthread.php?t=212174) meanwhile.
