### ISSUE TITLE
Take FX bug Not fixed

### ISSUE THREAD

**Issue by svijayrathinam** [reaper-oss/sws#1004]
Hi this issue is not fixed yet. I have reported this long time ago...Pls go through the following link. All the history is there on that thread

https://github.com/reaper-oss/sws/issues/938

**Comment by nofishonfriday** [comment]
Fix submitted for next SWS version (PR #961)

Here's a temporary SWS 2.9.8 version with the fix included:
https://www.dropbox.com/s/nocf53hptei87ei/reaper_sws_extension%202.9.8.%20%2B%20Copy%20Take%20FX%20bugfix.zip?dl=1

(no installer, unzip and replace existing reaper_sws_extension.dylib)

**Comment by nofishonfriday** [comment]
fixed in v2.10.0
>  SWS/S&M: Copy FX Chain (Depending on Focus) - if take FX chain, also copy take FX chain channel count
