### ISSUE TITLE
FR: Allow script windows to set/get focus

### ISSUE THREAD

**Issue by jalovatt** [reaper-oss/sws#1005]
Hopefully self-explanatory. Scripts using _Main_OnCommand_ to run actions will often lose focus to the arrange window in the process, requiring the user to click back into them. My Radial Menu script suffers even more, since unfocused windows don't receive keyboard updates anymore.

Something like these, say:

    SetScriptWindowFocus(boolean focused)

    boolean retval = GetScriptWindowFocus()

Cheers.

**Comment by juliansader** [comment]
I am currently writing new SWS functions to expose a bunch of Win32 windows-related C++ functions to the Lua API.  These will include:
Win32_FindWindow:  Find the HWND to the Radial Menu window by titlebar text.
Win32_SetForegroundWindow
Win32_GetForegroundWindow:  Check whether window is still in focus.

I hope to have them uploaded to a new version of SWS within the next few days.

**Comment by jalovatt** [comment]
Will those be useable on Mac and Linux?

**Comment by juliansader** [comment]
They will be useable on Mac, since SWS uses Cockos's own emulation of Win32 for MacOS: https://www.cockos.com/wdl/.

Unfortunately, they will probably not work on Linux (except if you are using Wine).  SWS itself is not yet available for Linux.

**Comment by jalovatt** [comment]
Fair enough. Thanks.

**Comment by cfillion** [comment]
SWS is available for Linux. FindWindow, GetForegroundWindow and SetForegroundWindow are all implemented by SWELL on both macOS and Linux. Are you using other Win32 functoins that aren't supported by SWELL? There's often a compatible alternative when that happens (if REAPER does it, it's in SWELL).

**Comment by cfillion** [comment]
SWS is available for Linux! You can build it yourself by running make from the sws root with wdl in the parent folder and symlinking reaper_sws64.so to your REAPER UserPlugins folder.

**Comment by juliansader** [comment]
> SWS is available for Linux

Thanks for letting me know!

**Comment by cfillion** [comment]
Closing this as SWS v2.10.0 added `BR_Win32_SetForegroundWindow`.
