### ISSUE TITLE
FR: "SWS/BR: Project track selection Action" should not only work with mouse

### ISSUE THREAD

**Issue by StephanRoemer** [reaper-oss/sws#1009]
Would it be possible to make this action work with keyboard selection, too?
Sometimes, I use the keyboard to select next or previous track.

**Comment by StephanRoemer** [comment]
Doh! I really hope there is a way to get there. Fingers crossed.

**Comment by nofishonfriday** [comment]
The limited OnTrackSelection() functionality is also mentioned [here](https://forum.cockos.com/showpost.php?p=1265074&postcount=10) and [here](https://forum.cockos.com/project.php?issueid=1253) so yeah, I think best bet would probably be to do a BR/FR (not sure if intended behaviour or not) in the Reaper forum.

**Comment by StephanRoemer** [comment]
done!
https://forums.cockos.com/showthread.php?p=2002317#post2002317

**Comment by nofishonfriday** [comment]
@StephanRoemer 
I noticed by chance this seems to be fixed on Reaper side meanwhile.
I tried with Reaper v6.05 and actions _Track: Go to next track_ / _Track: Go to next track_  and it's running the set Project track selection action here. 
Could you check on your side if you get a chance?

**Comment by StephanRoemer** [comment]
Thanks so much for the headsup nofish, yes I can confirm that it's working for mouse AND keyboard now!

**Comment by nofishonfriday** [comment]
Thanks for reporting back.
For keyboard there seems to be still one case missing (posted [here](https://forum.cockos.com/showpost.php?p=2253461&postcount=15)), but anyway, closing as 'fixed on REAPER side'. :)
