### ISSUE TITLE
FR: API exposure of projectconfig_var_addr and projectconfig_var_getoffs 

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#1013]
The Reaper-API has these two functions 
projectconfig_var_addr 
projectconfig_var_getoffs 

which seem to be able to access configuration-settings, that are project-related only, unlike getconfig_var() which is for most of Reaper's settings.

I would love to have access getting/setting to these from ReaScript as well, as they seem to be very handy...

**Comment by cfillion** [comment]
SNM_{Get,Set}{Int,Double}ConfigVar already exposes projectconfig_var_{addr,getoffs}.

**Comment by mespotine** [comment]
Are you sure? Because when I look into the functions, they don't call projectconfig_var_addr or projectconfig_var_getoffs at all. Or is get_config_var() itself calling them?

**Comment by cfillion** [comment]
They call GetConfigVar which in turn calls projectconfig_var_*.
https://github.com/reaper-oss/sws/blob/1b4449bedf2fd130c372e3db29ba2e33430fd704/SnM/SnM_Misc.cpp#L207-L211

https://github.com/reaper-oss/sws/blob/1b4449bedf2fd130c372e3db29ba2e33430fd704/sws_util.cpp#L304-L317

**Comment by mespotine** [comment]
Ah, ok, thanks. Didn't know, that SWS has it's own GetConfigVar-function as well, that does it already.

That way, this FR is already done and can be closed :)
