### ISSUE TITLE
"SWS/S&M: Remove all envelopes for selected tracks" causes hang if used in custom actions

### ISSUE THREAD

**Issue by reaperblog** [reaper-oss/sws#1021]
I'm trying to build a custom action that resets the entire project to default state.

If I use this action as part of the custom action reaper hangs indefinitely. 
Seems ok if used independently.

MacOS 10.12.6
reaper 5.92

**Comment by cfillion** [comment]
What else is there in the custom action? It seems to work fine with just that one SWS action in a custom action.

**Comment by cfillion** [comment]
macOS test build at <https://cfillion.ca/files/sws/fix-removeallenvs2-freeze/>.

**Comment by reaperblog** [comment]
problem solved. thanks for the quick fix
