### ISSUE TITLE
FR: SWS/gofer: Split selected Items at mouse cursor (obey snapping): select left or right

### ISSUE THREAD

**Issue by StephanRoemer** [reaper-oss/sws#1022]
This action is great, but when splitting items, all items are selected. I wish there were additional scripts  to only select the left or right items from the split.

**Comment by nofishonfriday** [comment]
Hi,

this action just runs two native Reaper commands:
Main_OnCommand(40513, 0); // move edit cursor to mouse cursor (obey snapping)
Main_OnCommand(40757, 0); // Item: Split items at edit cursor (no selection change)

https://github.com/reaper-oss/sws/blob/b3ad441575f075d9232872f7873a6af83bb9de61/SnM/SnM_Item.cpp#L351

I think the requested variants of it could also be done via scripts or a custom action, replacing the second action with either
MainOnCommand(40758, 0) // Item: Split items at edit cursor (select left)
or
MainOnCommand(40759,0): // Item: Split items at edit cursor (select right)

Would that be a viable solution for you ?

**Comment by StephanRoemer** [comment]
Hey nofish!

Indeed, that will work! And I found another solution... I don't know why, but I overlooked this one here:
Item: Split item under mouse cursor (select right)

I actually can create a cycle action and check for the snap state and always turn it on by condition.
That way, I will have an "obey snap" functionality. Sometimes, a little nudge helps wonders, thanks ;)

**Comment by nofishonfriday** [comment]
Ah nice.
So sounds like we can close this one. (If you think otherwise, just tell...)
