### ISSUE TITLE
FR: Post-render action

### ISSUE THREAD

**Issue by jalovatt** [reaper-oss/sws#1027]
In the same vein as the Global/Project Startup actions, what about a hook to be run _after rendering is finished_? Custom actions along the lines of "render the file, then do ___" don't wait for rendering to complete, making some workflows impossible: https://forum.cockos.com/showpost.php?p=2007297&postcount=3

**Comment by cfillion** [comment]
I don't think REAPER tells extensions when it's done rendering (I looked around and didn't find anything). We could poll `EnumProject(0x40000000)` for changes over and over, but this is just the same as a script using `reaper.defer`. Not sure if this would be a good idea?

**Comment by X-Raym** [comment]
It is already possible to do post render action. I and Heda have several scriprs which open render dialog and then do an action with new created files.

The trick is to use the Render with last settings action. It doesnt open the Render dialog, but next action are trigger after this one.

**Comment by jalovatt** [comment]
Fair enough.

**Comment by X-Raym** [comment]
@jalovatt You can close the issue I think :)
