### ISSUE TITLE
FR: Exposure of mouse state-functions for non gfx.ini-created windows

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#1030]
I would love to suggest a function, that returns the mousestate of the currently clicked window.

`bool leftclick, bool rightclick, bool middleclick, integer mousewheel, integer mousewheelhorz, HWND clickedwindow = GetMouseProperties()`

Sometimes one wants to know, which mousebutton has been clicked or if the mousewheel is used or the position of the mousecursor relative to the window-position.
This is curently only possible in gfx.init/gfx_init-created ReaScript-windows, but not in other windows from Reaper(like Video Processor, Navigator, etc), even though it would be helpful.

One such usecase would be, having the chance to create clickable/draggable graphical elements in the video-processor-window, of which we can't get mouse-events at all currently.

This, in combination with the window-functions from #1002, would allow proper, clickable user-interface-elements in the Video Processor-window, which would be awesome!

**Comment by juliansader** [comment]
My recent [url=https://github.com/reaper-oss/sws/pull/1028]pull request[/url] includes Mouse_GetState, which can return the state of mouse buttons and keyboard modifiers.

I haven't tried to add a function for mousewheel, since REAPER already sends mousewheel info to the script, if it is linked to a mousewheel shortcut.  (Also, I don't remember seeing a cross-platform SWELL function to detect mousewheel movement.)

**Comment by cfillion** [comment]
> Also, I don't remember seeing a cross-platform SWELL function to detect mousewheel movement.

In the Windows API, mouse wheel events are done by the OS sending a WM_MOUSEWHEEL message to the window proc. SWELL does the same (if REAPER can do it, it's very likely it's in SWELL!). https://docs.microsoft.com/en-us/windows/desktop/inputdev/wm-mousewheel

I use this in this extension to block mousewheel events over the TCP from messing with track heights: https://github.com/cfillion/tcp_mw_inhibitor/blob/master/src/main.cpp.

**Comment by juliansader** [comment]
In the Windows API, mouse wheel events are done by the OS sending a WM_MOUSEWHEEL message to the focused window proc.

Thanks for reminding me about SetWindowLongPtr!

I have added some functions to intercept window events - and they work great for mouse and mousewheel:
Window_Intercept
Window_ReleaseIntercept
Window_PostMessage
Window_PollMessage

(Or, at least, they work great in Windows - I have no idea whether they will work as well on MacOS/Linux.)

The disadvantage is that the script can only intercept messages from specific windows.  However, in many situations (including my own CC editing scripts), the script is only interested in a single window, so this would be acceptable (or even preferable).

In the case of mespotine's example of the video-processor-window, it should also work well.

**Comment by nofishonfriday** [comment]
@mespotine 
Sounds like this was done by @juliansader meanwhile?
So you think we can close this issue or should it stay open?

**Comment by mespotine** [comment]
I think it can be closed.
