### ISSUE TITLE
FR: exposing ItemPreview() to the API

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#1033]
Currently I could only preview a MediaItem using complicated selection/deselection of items or need to force the user to hover the mouse over the item to preview.

But I would like to play it directly from within ReaScript. 
ItemPreview() seems to be the perfect candidate for that, as far as I can see.

[](https://github.com/reaper-oss/sws/blob/master/Xenakios/main.cpp)

By the way, would previewing of an external file without having it as a MediaItem be possible too? Or is using a MediaItem mandatory for that?

**Comment by cfillion** [comment]
At first glance the REAPER preview API seems to be able to play any PCM_source.

**Comment by mespotine** [comment]
This sounds cool :)

Maybe I should add a little background to my use-case for this FR:
We at ultraschall would love to code a script, in which one can put MediaItems temporarily, as kind of a small clipboard. This shall also get a previewfunctionality, where you can preview the items in this clipboard.
For that, this function would be really really nice :)

**Comment by mespotine** [comment]
Implemented in JS-extension.

**Comment by cfillion** [comment]
I'm making a full-featured API for previewing audio sources: #1702 It has many features that are missing from the implementation in js_ReaScriptAPI.

**Comment by mespotine** [comment]
Nice!
I wonder, is changing pan also possible?

**Comment by cfillion** [comment]
Yes, since I'm handling audio at the sample level. Added!

**Comment by mespotine** [comment]
Fantastic :D

One more question: I've seen in the PR previewing through tracks. Is that mandatory or can I preview just the file, no matter how the project looks like?

I'm asking, as I want to go into more writing scripts for blind users in the future and being able to play a sound, pitch, volume change and pan would give all sorts of additional information. 
For instance, you can code a script that signals you, where to find the next button in the ui. The sound gives you a hint for that, like 
- played right means, there's a button to the right of the mouse, left the button is to the left, 
- the more silent the sound the further away is the button from the mouse, 
- sound pitched higher means button over the mouse, 
- pitched lower, under the mouse, 
- sound in the middle, mouse hovering over the button
etc.
But for this, I would need it to be able to play regardless of projects and be able to change pitch, pan, volume of a playing sound.
That's my usecase for it...

Thanks for putting in the effort to make this function :)

**Comment by cfillion** [comment]
By default the preview is played through a hardware out. The index of the first output channel is configurable via `I_OUTCHAN`. &1024 for mono.

The previews are only played through a track if configured to do so via the `SetOutputTrack` function.

(Nice usecase!)
