### ISSUE TITLE
FR: Addition of LibCurl; exposure of LibCurl-functions to Api

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#1038]
I would love to have libcurl-added to SWS.

As Reaper has no WebRequest-support and only some network-functions in EEL, this would be a real move forward.

[https://curl.haxx.se/libcurl/](https://curl.haxx.se/libcurl/)

**Comment by cfillion** [comment]
https://forums.cockos.com/showthread.php?t=267360
