### ISSUE TITLE
Bug: SWS/IX: Import m3u/pls playlist - crash when cancelling file loading dialog

### ISSUE THREAD

**Issue by nofishonfriday** [reaper-oss/sws#1041]
![m3u crash](https://user-images.githubusercontent.com/7658194/44549821-97a99480-a722-11e8-94ee-426bd6037acf.gif)

(click image for bigger version)

**Comment by cfillion** [comment]
It was also leaking the filename buffer when clicking not cancelling...

**Comment by nofishonfriday** [comment]
Hah, you were a tad faster. :gun:  I was just about to open my fix PR when I noticed yours (missed the leaking though).,
Thanks.

While at it, I found another minor quirk, when clicking 'No' in the 'Cannot find some files. Create items anyway?' dialog it creates the items anyway.

https://github.com/reaper-oss/sws/blob/400c3c13949805afc37b87627a0c8664f436508f/IX/PlaylistImport.cpp#L267

should be 'return' instead of 'break' in line 268 I think.
Would you add that too to your PR ?

**Comment by cfillion** [comment]
Oh sorry! I wasn't sure whether you intended to fix it...

I suppose "No" is useful for importing the files that do exist even if some aren't found? Otherwise I think the dialog should also be converted to a simple OK/Cancel one.

Maybe the message should instead say "The following files cannot be found. Create items for them anyway?" to be clearer.

**Comment by nofishonfriday** [comment]
No problem, doesn't matter to me _who_ fixes something in the end. :)

> Maybe the message should instead say "The following files cannot be found. Create items for them anyway?" to be clearer.

That's what I though it should do, but here I import a playlist where items are not found, when I click 'No' it still creates the (empty) items, that's what confuses me.

![m3u test](https://user-images.githubusercontent.com/7658194/44557374-7191ed80-a73e-11e8-8662-40af3dcc7783.gif)

**Comment by cfillion** [comment]
Looks like another bug to me! I'm guessing PCM_Source_CreateFromFile returned NULL at the time this feature was written if the file doesn't exist.

**Comment by nofishonfriday** [comment]
This seems to fix I think:
`if(pSrc && pSrc->GetSampleRate() > 0 || includeMissing)`
