### ISSUE TITLE
Load fails on Linux - reaper_sws64.so: undefined symbol: CreateTrackSend

### ISSUE THREAD

**Issue by realbucksavage** [reaper-oss/sws#1044]
It looks like that REAPER v5.95 cannot load the extension.
It fails with this:

```
swell: dlopen() failed: /home/bucksavage/reaper/REAPER/Plugins/reaper_sws64.so: undefined symbol: CreateTrackSend
Error loading /home/bucksavage/reaper/REAPER/Plugins/reaper_sws64.so: (null)
```

**Comment by cfillion** [comment]
That symbol shouldn't be resolved at runtime. Is this with the pre-built binary on Landoleet or did you build it yourself (if so, did you use the `next` branch)?

**Comment by jgodara** [comment]
@cfillion I built it myself.
I used the `next` branch to build it.
The pre-compiled binary worked, though...

**Comment by cfillion** [comment]
What compiler on which OS?

**Comment by jgodara** [comment]
I'm using Ubuntu Studio (Based on Ubuntu 18.04 LTS)

uname -a:
```
Linux bucksavage-desktop 4.15.0-34-lowlatency #37-Ubuntu SMP PREEMPT Mon Aug 27 17:40:31 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

I'm not a C++ guy at all, however, here is some stuff: 

- g++ --version: `g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0`
- make --version: 
```
GNU Make 4.1
Built for x86_64-pc-linux-gnu
```
