### ISSUE TITLE
BUG: Resize ReaConsole causes garbled display

### ISSUE THREAD

**Issue by daxliniere** [reaper-oss/sws#1047]
When you resize the Console window, the text becomes garbled. See LICEcap:

https://drive.google.com/open?id=1sTlf5zqR88HLaOzX0fedR0IgKHD3z0n0

Also, why is it called both ReaConsole and Console? I typed ReaConsole into the Actions window and couldn't find it at first.

**Comment by cfillion** [comment]
I'm surprised nobody reported this before! Looks like the culprit was WDL_WndSizer's enum_RegionRemove.

**Comment by daxliniere** [comment]
Thanks Christian!!
