### ISSUE TITLE
FR: Actions for Goto Next/Prev marker/region

### ISSUE THREAD

**Issue by daxliniere** [reaper-oss/sws#1053]
Hey guys,
We have "**SWS: Goto/select next marker/region**" and "**SWS: Goto/select previous marker/region**" for main arrange window, but these aren't available for **Section: MIDI Editor**.

Is it possible for these actions to be added/duplicated to that Section, please?

Thankyou!
Dax.

**Comment by daxliniere** [comment]
Ahhh, cool, I didn't know about the pass through. How could I find out more info about them? (how to set up, etc)

**Comment by nofishonfriday** [comment]
See
https://forum.cockos.com/showthread.php?t=205955

Basically you assign a shortcut to an action in Main action section and then you assign the same shortcut to the  action 'Misc: Pass through key to main window' in MIDI editor action section. (You can assign several shortcuts to this action, all that you want to pass through to Main window.)

Does this help?

**Comment by daxliniere** [comment]
Man, that's really cool.
And of course you can assign multiple keystrokes to that one "action". Thanks so much for this tip. Solid gold!

**Comment by nofishonfriday** [comment]
You're welcome.
So I'd think we can close this action (just tell if you think otherwise...).
