### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by jimfallope** [reaper-oss/sws#1055]
Hello,
I am new to all this.  I attempted to download the SWS extensions and it told me that the disc image was damaged and that I should eject it immediately.  How should I go about fixing this issue.  

Thanks.

**Comment by cfillion** [comment]
Which version of macOS?

**Comment by cfillion** [comment]
I tried on a fresh macOS 10.11.6 virtual machine and it opened fine here. Not sure what could be going on, but a bit of googling suggests opening the .dmg using the Disk Utility app might help: https://discussions.apple.com/thread/7774665. You can also try [re-downloading the file](http://www.sws-extension.org/download/featured/sws-v2.9.7.0.dmg).
