### ISSUE TITLE
Action "SWS: Quantize item's start to grid (keep length)" crashes Reaper when selecting multiple audio items and grid spacing is set to "frame"

### ISSUE THREAD

**Issue by s9menine** [reaper-oss/sws#1057]
Reaper v5.961/x64, SWS v2.9.7, Windows 7 64-bit. Report files found in Windows Event Viewer attached
[reaper quantize crash.zip](https://github.com/reaper-oss/sws/files/2571700/reaper.quantize.crash.zip)

**Comment by s9menine** [comment]
Here it is, too big for Github so I uploaded to GDrive https://drive.google.com/file/d/1bxwO1GbcwG9zWkeiFsUOwB-suear0t29/view?usp=sharing

**Comment by cfillion** [comment]
Thanks! I found two separate bugs leading to this action freezing with frame grid spacing. Fixed in this build: <https://cfillion.ca/files/sws/fix-quantize-time-frame/reaper_sws64.dll>.

What were your project start time and frame rate set to in Project Properties?

**Comment by s9menine** [comment]
The new build works, thanks! 

The crash happened across multiple projects, but my project start time is usually negative (project start measure at 0, and set 0:00 to measure 1), and frame rate is usually 30Hz.
