### ISSUE TITLE
Batch Render Regions Crash with unexpected characters

### ISSUE THREAD

**Issue by spblat** [reaper-oss/sws#1060]
I had a project with regions that included a double quote " in one region's name and a forward slash / in another. I'm not sure which character caused it, but initiating a "Batch render regions" command caused Reaper to crash. Removing both symbols resolved the issue. 

macOS 10.14.1
REAPER and SWS versions verified latest/current as of 11/15/18

Thanks for this magnificent set of extensions.

**Comment by cfillion** [comment]
Thanks! It was the slash (the directory separator character on Linux and macOS). Fixed in this build: <https://cfillion.ca/files/sws/fix-autorender-slash-unix/reaper_sws_extension.dylib>.
