### ISSUE TITLE
FR: Toggle Action for Render Speed

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#1065]
Hi,

Thx to SWS we have 

- **Xenakios/SWS: Set render speed to not limited**
- **Xenakios/SWS: Set render speed to realtime**

Could we have a toggle action for this with on/off states so that it would be perfect in a toolbar ?

A scripts solution would involve having it launched a REAPER startup so that it can toggle the toolbar accordingly, not very handy :/

Thanks !

**Comment by nofishonfriday** [comment]
@X-Raym 
added for next SWS

**Comment by X-Raym** [comment]
@nofish Thx ! It's for a friend, he use this two action all the time.
