### ISSUE TITLE
Plz...No More Snapshots Error Dialog

### ISSUE THREAD

**Issue by Poofox** [reaper-oss/sws#1073]
Hi!  I use Snapshots mainly for switching between visibility snapshots when viewing the mixer fullscreen.  Whenever I delete some tracks and then use my mixer switch, I'm greeted with this dialog:

https://stash.reaper.fm/34994/Capture.PNG

So I'm seeing this dozens of times a day and in nearly a decade of using reaper I have never once needed to click "No."

I would really and truly appreciate if someone could add a checkbox to confirm and never, ever see it again:

https://stash.reaper.fm/34995/3.jpg

 Thanks so much!

**Comment by Poofox** [comment]
One small checkbox?  Pretty please?  I'll iron your socks?

**Comment by nofishonfriday** [comment]
Added tickbox in Snapshots window: 'Prompt on recalling deleted tracks'.
Test version (Win x64, let me know if you're on OSX):
https://www.dropbox.com/s/2hytw7cvj1g2c1j/reaper_sws64.dll?dl=1

**Comment by Poofox** [comment]
Omg, thank you, thank you, thank you!  Works perfectly!  :D

**Comment by nofishonfriday** [comment]
Where can I send my socks? (j/k)
For info: The test version above is current SWS (v2.10.0 #1) + this addition, so you could use it until it gets integrated officially in next release.
If any quirk / bug comes up meanwhile let me know.

**Comment by nofishonfriday** [comment]
@Poofox 
I updated the test version (same link as above).
Because current official SWS version contains a bug relating to envelope functionality which is fixed meanwhile by cfillion but I forgot to include in my test version.

https://forum.cockos.com/showthread.php?p=2094872#post2094872

This fix is now also included in my test version so it's recommended to download again from above link and use this version instead until next SWS is officially released. :)

**Comment by Poofox** [comment]
Thanks, homie!  So good to see SWS is still alive!  :)

**Comment by Poofox** [comment]
Hi guys, thanks for this fix but I'm sad to say it's not actually working in the official release.  The checkbox has no effect now though it was working perfectly with the custom pre-release version nofish sent me.

**Comment by nofishonfriday** [comment]
Confirmed. Hm..looking into it, I'll get back..

**Comment by Poofox** [comment]
awesome and fast!  thx so much dude!

**Comment by nofishonfriday** [comment]
Thanks for the reprt.
You can check the test build here until the fix makes it in next official (pre) release if you want:
https://github.com/reaper-oss/sws/pull/1237#issuecomment-562808405
