### ISSUE TITLE
Error R6025 - pure virtual function call on SWS/BR: Toggle preview take under mouse

### ISSUE THREAD

**Issue by cuzer** [reaper-oss/sws#1077]
I get the error in the title and Reaper crashes when I use SWS/BR: Toggle preview take under mouse through track, and switch to a different project tab while the preview is in progress. 100% repro rate.

**Comment by cfillion** [comment]
This seems to be a REAPER bug. SWS only starts the preview. Any preview going through a project's track crashes when switching to another tab.
