### ISSUE TITLE
Hide take envelope doesn't hide but bypasses the take envelope

### ISSUE THREAD

**Issue by nanina** [reaper-oss/sws#1078]
It would be great if the 4 "hide take volume/pan/mute/pitch envelope" actions would be renamed to "bypass take volume/pan/mute/pitch envelope" as they don't hide but bypass envelopes.

At the same time please add shortcuts to only change the visibility of the envelope a.k.a. hide them.

Thanks

**Comment by nanina** [comment]
Awesome. Thanks!
Unfortunately i can only test OSX Versions.

**Comment by cfillion** [comment]
The fix was included in the 2.10.0 update. You can get it for macOS here: http://sws-extension.org/.
