### ISSUE TITLE
Update TagLib for VS 2017

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#1088]
Hi,

I tried to merge all pull request for SWS.

I use Microsoft VS Studio 2017 community edition,
and to open the project, I had to update the SDK.

Though, I had compilation error related to TagLib, and according to @cfillion, it seems the current TagLib binaries included with SWS are not compatible with VS 2017?

Can we update it ? :)

This way we could all use up to date IDE.

Thanks !

**Comment by nofishonfriday** [comment]
You can open the current SWS VS project file (VS 2013 format) also in VS 2017 without updating to VS 2017 format, but you also need to have VS 2013 Express installed for it. Then you can open the project file in VS 2017 and build SWS without updating the project file to VS 2017 (choose no when asked) or the TagLib libraries. 
That's what I'm doing here.

https://i.imgur.com/vTC3qhY.jpg

If we all agree to update the project file to VS 2017 that's also fine with me of course.

**Comment by X-Raym** [comment]
@nofishonfriday Thanks for your input ! Though I'm affraid it's to late on my branch :(

I think we have to make the thing as simple as possible for contributors. The easiest way IMHO is to just tell "download last cool VS version and Run" rather than "you have to have two softwares version installed, and be careful for build because there dependencies etc"...

cfillion successfully build taglib for VS 2017 once but doesn't succeed to reproduce so far 😥

**Comment by nofishonfriday** [comment]
As said, it's totally fine for me. :)
But I think we should also ask/wait for opinion from Tim about it (but maybe this already happened?)

> cfillion successfully build taglib for VS 2017 once but doesn't succeed to reproduce so far 

I don't understand this.
If he succeeded building taglib for VS 2017 then they should already exist no?
(even if he just succeeded one tiime :D)

**Comment by X-Raym** [comment]
@nofishonfriday 

> If he succeeded building taglib for VS 2017 then the binaries should already exist no?

I'm afraid it was just a temporary test :P Too bad it is probably the last step which prevents me to end the pull requests merging.

> But I think we should also ask/wait for opinion from Tim

Tim agreed to merge my fork, if it builds successfully. So I'm pretty sure we can change (update) anything we want as long as it doesn't break things. 😄

**Comment by nofishonfriday** [comment]
Fine. :)
I could take a look at building taglib for VS 2017 but tbh I doubt I would succeed if cfillion doesn't.
Which then brings the question who else could do it as we (and now also you, thanks!) seem to be the only SWS contributers currently.
But I'll keep you updated if I try how it goes.

**Comment by X-Raym** [comment]
> and now also you, thanks!

Well, for now I'm just someone who is messing with Git 😆 I still have no knowledge of C++ at all. Without cfillion helps I wouldn't have been so far in compilation process. I just want to make a new codebase (merging pull) so you guys can start 2019 from a fresh start. And finally valorize your 2018 SWS work!

**Comment by cfillion** [comment]
Using the Developer Command Prompt for VS2017:

```bat
git clone https://github.com/taglib/taglib.git
cd taglib

rem 64-bit
cmake . -DBUILD_SHARED_LIBS=OFF -DENABLE_STATIC_RUNTIME=ON -DCMAKE_INSTALL_PREFIX=install -G "Visual Studio 15 2017 Win64"
msbuild install.vcxproj /p:Configuration=Release
copy install\lib\tag.lib ..\sws\lib\vs12_tag64.lib

git clean -fx

rem 32-bit
cmake . -DBUILD_SHARED_LIBS=OFF -DENABLE_STATIC_RUNTIME=ON -DCMAKE_INSTALL_PREFIX=install -G "Visual Studio 15 2017"
msbuild install.vcxproj /p:Configuration=Release
copy install\lib\tag.lib ..\sws\lib\vs12_tag32.lib

rem update headers in the sws repository
xcopy install\include\taglib ..\sws\taglib
```

**Comment by nofishonfriday** [comment]
I suceedeed meanwhile building with VS2017:
https://www.dropbox.com/s/58cvlqortpzds9y/taglib%20VS2017.rar?dl=1

@X-Raym 
You could try these and let me know if it works.
@cfillion 
I know you're not a fan hosting binaries in the repository. :D
Doing it as git submodule is agreed, the cleaner solution, but I've never worked submodules so far (meaning if you want to do it I'll be happy. :))

**Comment by X-Raym** [comment]
> Maybe we could add taglib as a git submodule and have it be built automatically when compiling SWS instead of including binaries and headers directly to the sws repository?

This would be the optimum solution, cause handling the binaries and headers right in SWS repo will have the same issue as we just have at each SDK update.
Also, having less files in SWS makes maintenance easier.

So, if this method is not too hard to set up, and not to hard to use, I'm 100% for it.

@nofishonfriday 
You .rar has two lib file,each containing some obj file, which seems very different thant the current taglib folder content... How should they be used ?

**Comment by nofishonfriday** [comment]
@X-Raym 
Replace with the existing ones in sws / lib folder
https://github.com/reaper-oss/sws/tree/master/lib

**Comment by X-Raym** [comment]
@nofishonfriday Ok so here is the compilation erorr I get:

```Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur	LNK2005	"public: __thiscall TagLib::FileName::FileName(wchar_t const *)" (??0FileName@TagLib@@QAE@PB_W@Z) déjà défini(e) dans vs12_tag32.lib(tiostream.obj)	SWS_Extension	E:\Bureau\sws\SnM_Misc.obj	1	```

**Comment by nofishonfriday** [comment]
I've built again using cfillion's instructions above.
https://www.dropbox.com/s/9ovivjegcoryq4n/taglib%20VS2017.zip?dl=1

Additionally replace the 'taglib' folder in sws with the one included in the zip.

**Comment by X-Raym** [comment]
@nofishonfriday 
It works ! (on Win 64 at least to Win and Win 34 build)

Compilation of all merged pull request +with SDK update and TagLib update !

Here is my test build if you want to have fun before it become official :

https://drive.google.com/file/d/1GjyDJTHsBntEy5gVSMy3KC6NkODROCwz/view?usp=sharing

I'll discuss with @cfillion about some Git related things though before proposing this merge though.

And for the way tag lib is managed, again I think it is better to wait for my pull request, and then we will set up that.

**Comment by swstim** [comment]
Merged!
