### ISSUE TITLE
Pull Request from Local Branch

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#1091]
Hi,

Git related issue,

to have access to all PR, I worked directly on a local version of the SWS repo (not a fork).
I worked on master branch directly. After having meged all PR, I create my own branch (not fork).

So now, how do I propose this local branch as Pull Request ?

I can only click on Pull Origin GitHub App button but I have no write access to this repo so it fails.

Thanks !

**Comment by cfillion** [comment]
I don't know if there's an equivalent within the GitHub App, but using the command line:

1. Add your fork as a remote: `git remote add x-raym https://github.com/X-Raym/sws.git`
2. Push your branch to it: `git push x-raym`
3. You will now be able to create the pull request from your fork's branch to this repo's `next` branch (the git push above will provide a link, or use the "New pull request" button on GitHub). `next` won't be automatically selected.

**Comment by X-Raym** [comment]
@cfillion Seems good thx !

https://github.com/reaper-oss/sws/pull/1092
