### ISSUE TITLE
Cannot install sws extensions on win7x64

### ISSUE THREAD

**Issue by samantien** [reaper-oss/sws#1094]
I've been trying to install the SWS extensions on my computer with no luck. I downloaded both of the windows versions on my computer and the 32bit installer works like it should. The more important 64bit version on the other hand doesn't. It seems that Windows doesn't recognise the file type and cannot open it. Also the file size of the 64bit installer seems to be 0Mb. 

Any help would be greatly appreciated.

Thanks in advance!

- samantien

**Comment by cfillion** [comment]
Try downloading using a different browser, computer and/or network. An empty file points to a failed download.

**Comment by samantien** [comment]
Haha,

I dowloaded the file using a different browser and got it working. I can't believe I didn't think of that. Thanks!
