### ISSUE TITLE
API: Delete/Remove Take function

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#1097]
Hi,

There is no delete takes from items API function, it require handling items chunk.

There is some BR actions which does that like for deleting item under mouse like this :

```
SNM_TakeParserPatcher takePatcher(mouseInfo.GetItem());
takePatcher.RemoveTake(mouseInfo.GetTakeId());
```

I think this could be exposed to ReaScript.

It could be `DeleteTake( *take)` or simply `DeleteTakeFromItem( item, id )`

What do you think ?

Cheers !

**Comment by nofishonfriday** [comment]
Maybe check how Breeder deletes takes in his script?
https://forum.cockos.com/showthread.php?t=216665

Haven't looked at the code myself, would that be a viable alternative?

**Comment by StephanRoemer** [comment]
It's funny, because Breeder himself complained about a missing delete take function ;)

**Comment by X-Raym** [comment]
@StephanRoemer This is why I posted the request 😄 

@nofishonfriday most advanced lua solution only is mpl's take parser. But it's Lua only. I would choose this solution if I needed it right now personally, but it is more like a "would be good to have in the future cause we never know" type of request. It's surprising that this isn't already a native function.
