### ISSUE TITLE
Can't install SWS on mac

### ISSUE THREAD

**Issue by Nujinho** [reaper-oss/sws#1102]
Hi

I'm new to podcasting and want to to use Reaper to edit. I found this amazing guide:

https://podigy.co/podcast-editing-guide/

It recommends the SWS extension to create easy shortcuts but I can't seem to install it. I've downloaded the .dmg file on my Mac. When I double click it I get the attached image telling me to drag and drop into the Plugins folder, but when I attempt to, it won't let me

Any ideas on how I can get it installed into Reaper?

Thanks
Anuj

<img width="546" alt="screenshot 2019-02-05 at 19 28 34" src="https://user-images.githubusercontent.com/47366526/52299042-60e7d380-297c-11e9-9d55-6601c787aa89.png">

**Comment by mespotine** [comment]
What does "It won't let me" mean?

You may have a look at ultraschall.fm which is meant for podcasting stuff(which also includes SWS).

There's an introduction-video at: https://www.youtube.com/watch?v=p5kYH-YheN0
It's in german, but should be a good introduction any way.

**Comment by Nujinho** [comment]
Thanks - will check it out! 

When I try and drag the icon over into the folder (on the attachment) nothing happens. There is no UserPlugins folder setup when I look in Finder so not sure where it is actually located. Neither is there an Application Support folder for REAPER.

Do I need to manually set this folder up? If so, how can I direct Reaper to look there for a plugin

(Apols I'm quite out of my depth here!)

Does that help?

**Comment by cfillion** [comment]
1. From REAPER: Options > Show REAPER resource path in explorer/finder
2. Put reaper_sws_extension.dylibe in the UserPlugins subdirectory
3. Restart REAPER

The .dmg points to a system-wide folder that doesn't usually exist for most REAPER installs.

**Comment by Nujinho** [comment]
Amazing - thanks so much. Worked a treat!
