### ISSUE TITLE
Command ID 39781

### ISSUE THREAD

**Issue by MarvOlis** [reaper-oss/sws#1104]
"horizontal" is spelled wrong in Command ID 39781

**Comment by cfillion** [comment]
Action 39781 aka *Set default mouse modifier action for "Arrange view middle drag" to "Set edit cursor and orizontal zoom"* is a native REAPER action. It's not provided by SWS.

It's indeed misspelled. REAPER bugs can be reported here: <https://forum.cockos.com/forumdisplay.php?f=22>.
