### ISSUE TITLE
Problem with Umlauts (ä,ö,ü) in BR_Win32_GetPrivateProfileString and BR_Win32_WritePrivateProfileString

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#1105]
We stumbled recently over this problem with BR_Win32_GetPrivateProfileString and BR_Win32_WritePrivateProfileString.
When I try to access an ini-file, where an umlaut is in the path, it will return the error-value.

Problematic: 
c:\Ultraschall_3.2_Hackverzeichnisse\Ultraschall-Portable_Januar2019-Ultraschall_Ini-Uml**ä**ut-Bug\ultraschall.ini

Working:
c:\Ultraschall_3.2_Hackverzeichnisse\Ultraschall-Portable_Januar2019-Ultraschall_Ini-Uml**a**ut-Bug\

I haven't checked on Mac and Linux, only on Windows 7, but it seems to occur on Windows 10 as well.

**Comment by cfillion** [comment]
Is this with the latest REAPER and SWS versions? Is the string UTF8-encoded (it should if you're getting it from GetResourcePath)? ä should be 0xC3 0xA4.

**Comment by mespotine** [comment]
Oh, it works with the new version :D 

Which is interesting, as there's no change in these functions in that regards, only the possible crash-check.

Being curious, did you change something in the development-environment?

So, this Issue is now obsolete :)

**Comment by cfillion** [comment]
SWS 2.9.8 added support for REAPER 5.70 now using UTF-8 for encoding the resource path.
