### ISSUE TITLE
FR: BR_SetItemEdges -1 value for not moving edge

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#1114]
Hi !

It would be nice if we could pass "-1" (or any negative number) as parameter value into BR_SetItemEdges, to ignore one edge 😄 

Thx !

**Comment by X-Raym** [comment]
@nofishonfriday what is this tag ? "good first issue" ? ^^

**Comment by nofishonfriday** [comment]
@X-Raym 

https://help.github.com/en/articles/helping-new-contributors-find-your-project-with-labels
I put it there, hoping to make it easier for potential new SWS contributors to get started (seeing which issues are relatively 'straightforward' to tackle.). :)

**Comment by nofishonfriday** [comment]
The relevant bit of code which would have to be modified is here btw. :)
https://github.com/reaper-oss/sws/blob/next/Breeder/BR_Util.cpp#L1067

**Comment by X-Raym** [comment]
@nofishonfriday I think there might be some optimizaiton possible there,

for eg, if you have an item at position > 1 and you say

reaper.BR_SetItemEdges(-1, 1)

We might expect that the function doesn't do anything as it is invalid,

but in fact it will move item left edge to -1 and keep right edge in place.

What do you think ?

**Comment by cfillion** [comment]
This is not new: that function has always swapped the supplied left/right positions if the former is larger than the later.

**Comment by X-Raym** [comment]
@cfillion ok I didnt know about this auto swapping, The API doc doesn't mention that case. Thx !
