### ISSUE TITLE
action marker for record problem

### ISSUE THREAD

**Issue by vincentsermonne** [reaper-oss/sws#1115]
https://www.dropbox.com/s/c14cx4jq47k2euh/action%20marker%20record.gif?dl=0

with action marker !1013 the recording starts late and ends late

**Comment by nofishonfriday** [comment]
That's just the way it is with action markers, they have some latency, sorry.
See JeffOS's (who did the action markers afaik) comment here:
https://github.com/reaper-oss/sws/issues/723

**Comment by vincentsermonne** [comment]
ok ! thank you nofish for your answer !

**Comment by nofishonfriday** [comment]
Closing this as 'live with it'.
