### ISSUE TITLE
Measure setting error w- Move closest measure grid line to mouse cursor (perform until shortcut released) 

### ISSUE THREAD

**Issue by blumpy1** [reaper-oss/sws#1117]
The Move closest measure grid line to mouse cursor (all variations) will not work properly when then Snap/Grid Settings: Show Grid, line spacing is set to: Measures. 

The Measures setting is fairly new and a warning is returned that the grid is set to frames despite the "measures" setting being a musical grid not a sample or frame grid.

**Comment by cfillion** [comment]
Measure grid spacing is not implemented in SWS (issue #1058).

**Comment by nofishonfriday** [comment]
@cfillion 
Unless you plan to implement this yourself, I have a potential fix [here](https://github.com/nofishonfriday/sws/commit/fc79227eb6fa4b46806ea84d2c92c1af453de82e).

Would appreciate if you take a look (if you get a chance), not sure if it's that 'trivial'. :D 
Test build:
https://www.dropbox.com/s/oddujqfwr9mxq86/reaper_sws64.dll?dl=1

**Comment by cfillion** [comment]
That patch works perfectly (at least for everything I thought to test). 👍

**Comment by nofishonfriday** [comment]
Thanks for testing!
