### ISSUE TITLE
Region Playlist broken with groups AND undo bug

### ISSUE THREAD

**Issue by reaperblog** [reaper-oss/sws#1118]
Bug 1 - Grouped items don't move with playlist actions

This used to work better, items would move but become ungrouped (not ideal), in current version they don't move at all.

Bug 2 - after running a playlist action, CMD-Z deletes the playlist.

Please see video for both issues

https://www.youtube.com/watch?v=ezyisHyr7Cg

**Comment by cfillion** [comment]
Fixing... In the meantime you can disable "Options: Toggle item grouping override" before pasting the playlist as a workaround.
