### ISSUE TITLE
Go to maximum short term/momentary in Loudness doesn't work properly

### ISSUE THREAD

**Issue by Reaperto** [reaper-oss/sws#1120]
Go to maximum short term/momentary in Loudness doesn't work properly. It creates a time selection outside the audio clip.

I'm in Reaper 5.971, 32 bits
SWS Extensions 2.10.0 #1
Windows 7 64 bits

Many thanks.

**Comment by nofishonfriday** [comment]
Thanks. I can reproduce this (only) when using 'high precision' analyzing mode.
Can you confirm this on your side, that it only happens when using 'high precision' analyzing mode?

**Comment by Reaperto** [comment]
Yes, you are right. No problems when Use high precision mode is off. Many
thanks!

**Comment by nofishonfriday** [comment]
fixed/merged (disabled for now in high precision mode, showing a 'not implemented' pop up)

**Comment by Reaperto** [comment]
Many thanks!
