### ISSUE TITLE
Loudness: Wrong results with mono takes and channel mode set to mono left or right

### ISSUE THREAD

**Issue by nofishonfriday** [reaper-oss/sws#1123]
reminder:
https://forum.cockos.com/showthread.php?t=218203

(reported by @X-Raym via Slack)

**Comment by nofishonfriday** [comment]
@cfillion

What do you think of this?
Seems it won't get changed/fixed in Reaper for now (see above forum link).
Should we add a check in SWS (and set mono item to 'normal' mode temporarily for scanning) or argue it's Reaper's/user's fault? :D

**Comment by cfillion** [comment]
It looks like GetAudioAccessorSamples doesn't write anything to the sample buffer when the take channel mode is set to either Mono Left or Mono Right.

Similar to the bug with video items, except here it writes no samples at all yet still returns non-zero. https://forum.cockos.com/showthread.php?t=226151

**Comment by cfillion** [comment]
REAPER 5.986 is out.
