### ISSUE TITLE
Certain SWS env actions don't work with fader scaling

### ISSUE THREAD

**Issue by mkruselj** [reaper-oss/sws#1126]
SWS/FNG: Move selected envelope points down
SWS/FNG: Move selected envelope points up
SWS/FNG: Shift selected envelope points down on left
SWS/FNG: Shift selected envelope points down on right
SWS/FNG: Shift selected envelope points up on left
SWS/FNG: Shift selected envelope points up on right
SWS/FNG: Compress amplitude of selected envelope points around midpoint
SWS/FNG: Expand amplitude of selected envelope points around midpoint
SWS/FNG: Move selected envelope points down
SWS/FNG: Move selected envelope points up
SWS/BR: Set closest envelope point's value to mouse cursor (perform until shortcut released)
SWS/BR: Set closest left side envelope point's value to mouse cursor (perform until shortcut released)
SWS/BR: Set selected envelope points to first selected point's value
SWS/BR: Set selected envelope points to last selected point's value
SWS/BR: Set selected envelope points to next point's value
SWS/BR: Set selected envelope points to previous point's value

Just mess up the volume envelope in case of it being set to fader scaling.

I hope these are the only ones that need fixing, but I'm not 100% sure.

**Comment by cfillion** [comment]
PR #1111 fixes this.
