### ISSUE TITLE
Xenakios/SWS: Switch item source file to random in folder - Issue?

### ISSUE THREAD

**Issue by davidkamp** [reaper-oss/sws#1128]
Hi,
I am having the issue that the action:
Xenakios/SWS: Switch item source file to random in folder

Uses the media folder, rather than the folder where the source file I pointed it too.
I am using separate folders with different types of files and want this action to only pick a random file from the folder where the current file came from.  
It seems to use the media folder only... 
Am I missing something?
Thanks!

**Comment by cfillion** [comment]
It works as expected here (and, looking at the code, it should only look at the take's source's directory). Could it be the file was automatically copied in the Media directory on import (as per the *Options: When importing, copy imported media to project media directory* option)?

**Comment by davidkamp** [comment]
Ah well... you're right. Thanks a lot, and sorry for the false alarm! :)
