### ISSUE TITLE
Accessing ConfigVar "g_config_project" crashes Reaper

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#1131]
Accessing the config-var "g_config_project" crashes Reaper or at least lets Lua hang up.
It is a crash within SWS, but as earlier versions worked without any problems, I think it is a regression of Reaper's side(if not, I'll report it into SWS-git as well).

Code:
```
  O=reaper.time_precise()

  A0=reaper.SNM_SetDoubleConfigVar("g_config_project", 100)
Tested on Windows 7, Reaper 5.974 and SWS 2.9.7 and SWS 2.10.0.1.
```

The rc2 of Reaper 5.974 seems to not have that problem, but I might be wrong.
5.973 and earlier worked without any problems.

According to Justin, this is due this variable being a string and should not be accessed as double.

The full post in this bug-reports-thread.
https://forum.cockos.com/showthread.php?p=2119876#post2119876

**Comment by nofishonfriday** [comment]
Well, the name of this function and the description ("Sets a _double_ preference") quite clearly states it isn't intended to set string config variable I'd say. :P 
But agreed to Justin's comment, a sanity check should probably be added to SWS.
