### ISSUE TITLE
Future plans for LiveConfigs

### ISSUE THREAD

**Issue by Burtan** [reaper-oss/sws#1136]
Hi,
as I see the latest commit to the LiveConfigs file is 2-3 years old. Are there any plans for improvements or new features? I'm not experienced in C++ developement but I know kotlin/java/swift quite well. I want to add a feature that makes it possible to switch multiple tracks instead of only one per config. I just want to make sure that there isn't something similiar going on already :D.

**Comment by nofishonfriday** [comment]
Hi,
currently the only regular SWS contributors are me, @cfillion and @swstim as maintainer afaik.
Nothing planned regarding this feature from my side at least. 

If you want to get started be sure to take a look at the [Wiki](https://github.com/reaper-oss/sws/wiki) and shout if you need help. :)

**Comment by Burtan** [comment]
What's the recommended build environment? I'm coming from IntelliJ. I just downloaded the community version from Visual Studio. Do I have to copy the build extensions into Reaper each time I wanna test it?

**Comment by cfillion** [comment]
You can create a symbolic link (that's what I do) or configure visual studio to copy the dll into your resource directory. By default the VS project is configured to copy into some `$(REAPER_DIR)\plugins`.

**Comment by Burtan** [comment]
I also realized that the LiveConfigs.h and cpp files contain multiple classes. Is this good practice for this project? I'm used to smaller classes and the guides I found yet about C++ also propose this. So I might try some refactoring for the LiveConfigs functionality.

**Comment by Burtan** [comment]
What would be the best place for general questions? I don't want to spam with single issues :D

**Comment by nofishonfriday** [comment]
For general questions I'd suggest the Reaper [developer forum](https://forum.cockos.com/forumdisplay.php?f=3) and there's also a 'REAPER Professionals' [Slack](https://slack.com) workspace which has a developer channel.
If you [PM](https://forum.cockos.com/member.php?u=6870) me your email, I can send you an invite (I think, just joined recently myself.)
