### ISSUE TITLE
SWS Auto Color/Icon/Layout close Reaper when using auto track layout

### ISSUE THREAD

**Issue by TobbeT** [reaper-oss/sws#1147]
Hi,

When I activate "Options - Auto track layout" and create new tracks and give them a name and the hit TAB key go get to next track for naming, Reaper closes down. Deactivate the issue is gone.

And why does MCP Layout showing in TCP Layout column and TCP Layout is showing in Icon column? Looks wierd.

![Screenshot from 2019-05-01 22-23-42](https://user-images.githubusercontent.com/76429/57040590-3302ea00-6c60-11e9-9562-6f8e093f57f4.png)

SWS/S&M Extension version: 2.10.0 #1 built on Feb 6, 2019
Reaper for Linux 64Bit

**Comment by cfillion** [comment]
Thanks! I forgot about this. It's the same as #911. It appears to be a bug on REAPER's side. I've posted a bug report with details: https://forum.cockos.com/showthread.php?t=220400.

**Comment by nofishonfriday** [comment]
@cfillion 
Do you think the misplaced entries is a Linux specific issue?
Here on Win it looks ok at least.

**Comment by cfillion** [comment]
Yes, it's most likely a bug in SWELL's implementation of list views on Linux. I haven't investigated yet though. Could be a SWS bug.
