### ISSUE TITLE
FR: Split items at time selection, else at edit cursor, crossfading to the left (or centered)

### ISSUE THREAD

**Issue by gaw0319** [reaper-oss/sws#1156]
Two of the SWS actions that I find to be vast improvements on the original editing behavior of Reaper are the "SWS: Split items at time selection (if exists), else at edit cursor" and "SWS/AW: Split selected items at edit cursor w/crossfade on the left".

The time-selection-aware split gives Reaper's splitting on-par functionality with other DAWs, and is a necessity for an efficient workflow in my opinion. Reaper's default, unchangeable 'always crossfade to the right' behavior always struck me as clumsy, because it is far easier to split an item and have the crossfade intrude on a transient, compared to if that crossfade always went to the left, or if it was centered around the split point. Since Reaper currently has no options to change the default direction of auto-crossfades, these actions are the only way to do it.

The "SWS/AW: Split selected items at edit cursor w/crossfade on the left" feature is another great improvement, although I'd love to see both actions combined into a more comprehensive split action: "SWS: Split items at time selection (if exists), else at edit cursor, w/crossfades on the left", or alternatively, a few actions that split with the crossfade centering on the split point (Similar to auto-crossfade behavior in Samplitude, for example).

Thanks for the consideration!

**Comment by nofishonfriday** [comment]
Hi,

_I'd love to see both actions combined into a more comprehensive split action: "SWS: Split items at time selection (if exists), else at edit cursor, w/crossfades on the left",_

I've just added a script to [ReaPack](https://reapack.com/) called _Split items at time selection, elese at edit cursor, crossfading to the left_ you could try.

(Note that my ReaPack repository needs to be enabled in ReaPack first to see my scripts:
https://github.com/nofishonfriday/ReaScripts)

If you try it, let me know if it's what you're looking for. :)

**Comment by gaw0319** [comment]
This is wonderful, thank you much for the willingness to implement this!

I got a chance to try it out, and so far so good- I did notice a few things that I wanted to ask about:
-When splitting an item without a time selection, I'm given a "No time selection active" error. After I click okay, the item splits as usual. In the SWS action, the error seems to not occur, or has been bypassed in some way. I'm not sure if this is an easy fix or not.
-When splitting up items within a time selection, the first of the two crossfades in the time selection appears to the right. Is it possible to also have this occur to the left as well?
-I'm not 100% sure, but it seems like the crossfades created with the action do not follow the default crossfade-on-split length as set in the Reaper preferences, although they do follow the shape.

Thank you again for the help with this, it is very much appreciated!

**Comment by nofishonfriday** [comment]
Hi,
thanks for the feedback.

> -When splitting an item without a time selection, I'm given a "No time selection active" error. After I click okay, the item splits as usual. In the SWS action, the error seems to not occur, or has been bypassed in some way. I'm not sure if this is an easy fix or not. Splitting items with a time selection active does not give the error though.

Ah yes, it's because I'm using Reaper's native action "Item: Split items at time selection" which shows this pop up if no time selection set.
I've just updated the script in ReaPack (v1.02) which should fix it. (Be sure to run 'Synchronize packages' to see it.)

> -When splitting up items within a time selection, the first of the two crossfades in the time selection appears to the right of the range beginning point (the second one appears to the left of the end point). Is it possible to have both of these crossfades appear to the left of the markers on the time selection range?
> -I'm not 100% sure, but it seems like the crossfades created with the action do not follow the default crossfade-on-split length as set in the Reaper preferences, although they do follow the shape.

Well, this script currently just combines "Item: Split items at time selection" (as mentioned above) and " SWS/AW: Split selected items at edit cursor w/crossfade on left" with some logic in between ("if no split at time selection happened, run the AW action" - so it was very straighforward to do in its current version.

Changing the splitting behaviour as you suggest would require coding an entirely new split function which I don't have capacity for currently, sorry to say.

Though, you could
- ask in the  [scripting forum](https://forum.cockos.com/forumdisplay.php?f=3) if someone is up for it
- ask if it gets implemented natively in Reaper

**Comment by gaw0319** [comment]
Great, that fix worked wonderfully for me! In regards to the time selection first-crossfade-on-split, that's totally understandable- I'm not so familiar with what it takes to create scripts or code functions in Reaper, but I imagine stepping outside the realm of normally available functions would be a bit tedious. In a way, the time selection split does make sense, since it keeps the resulting object length is exactly within the time selection. Odd enough, the split-auto-crossfade length also seems to be all sorted now, so I'm guessing it was probably just user error on my part.
Thank you again for the help putting this script together! It really is hugely appreciated, it's working great for me, and has replaced my default split shortcut key. As limited as Reaper's default auto-crossfade options are, it's a relief to see a lot of it being adjustable through third party customization. With as much as I manually crossfade and edit things during mixes, I'll be getting many thousands of uses out of this script!

**Comment by nofishonfriday** [comment]
Nice to hear it's useful for you, you're welcome.

**Comment by nofishonfriday** [comment]
closing as 'implemented via script'.
