### ISSUE TITLE
Linux builds

### ISSUE THREAD

**Issue by koulaxizis** [reaper-oss/sws#1162]
Hello! 

I've been using your awesome extension on Windows for a really long time and I'd like to use it on my Linux laptop too.

I run the native Linux version of Reaper, so I don't use WINE.

Are there any plans on releasing a pre-compiled SWS package for Linux?

**Comment by cfillion** [comment]
For now, there are pre-compiled versions of SWS available here: https://cfillion.ca/files/sws/ and older ones here: http://landoleet.org/.

**Comment by koulaxizis** [comment]
Awesome!! Thanks a lot! :D
