### ISSUE TITLE
BROKEN: Remove sends from selected tracks

### ISSUE THREAD

**Issue by daxliniere** [reaper-oss/sws#1166]
Hey guys,
**SWS/S&M: Remove sends from selected tracks** does nothing, I'm sorry to report.

REAPER v5.979+dev0625 x64
SWS v2.10.0 #1 (6 Feb 2019)

**Comment by cfillion** [comment]
It works fine here, can you share an minimal project that demonstrates the issue?

**Comment by daxliniere** [comment]
Ahh, I think I just worked out why! Try it with a Hardware send = no dice.
Definitely need an action that does removes hardware sends, but I can see that someone might like the current behaviour for certain reasons.
Perhaps the current action could be adapted as a second action?

**Comment by cfillion** [comment]
"Remove hardware outputs of selected tracks" on ReaPack should take care of that. 😸
