### ISSUE TITLE
Region Playlist - Data storage

### ISSUE THREAD

**Issue by ksawaia** [reaper-oss/sws#1172]
Hello.  I am looking for the location that the region playlist stores its data in so I can make an app to easily export setlists for my other band members.  Can you tell me where this data stores locally?  Thanks!

**Comment by nofishonfriday** [comment]
Hi, it's stored within the REAPER project file (.rpp).
![region playlist](https://user-images.githubusercontent.com/7658194/61951995-f458a380-afb2-11e9-94cb-299ee2ba9117.jpg)

**Comment by nofishonfriday** [comment]
closing as 'answered'.
