### ISSUE TITLE
REQ: Duplicate action: SWS/S&M: Remove all envelopes for selected tracks

### ISSUE THREAD

**Issue by daxliniere** [reaper-oss/sws#1175]
Hey team,
Could somebody please duplicate the existing action **SWS/S&M: Remove all envelopes for selected tracks**  (_S&M_REMOVE_ALLENVS) and create a version with a confirmation dialogbox?

For example, the native action **Envelope: Clear envelope** first displays a dialogbox asking if you're sure.

Thank you for your consideration!
Dax.

**Comment by nofishonfriday** [comment]
Would a script do which displays a prompt (confirmation dialog) accordingly and if confirmed calls the existing action?, Same outcome I'd think, but I'd prefer this variant to duplating it in SWS tbh.
If so I could add it to my ReaPack repo.

**Comment by daxliniere** [comment]
It would work for me, but it's a bit dangerous to have an action which wipes all automation without prompting first. Is it difficult to duplicate an existing action? I figured not.

**Comment by nofishonfriday** [comment]
>  it's a bit dangerous to have an action which wipes all automation without prompting first.
Point taken. :)
Wouldn't be difficult to duplicate it indeed, my thinking was something like: if we duplicate this one, which other potentially dangerous actions with no prompt get duplicated next -> bloat here we go.

But ok, would be fine by me and I'd do it, would like to get opinion from other SWS contributors though.

**Comment by nofishonfriday** [comment]
@daxliniere 
An idea I had is doing it via an entry in the ini file. So user could put the line _RemoveAllEnvsSelTracksPrompt=1_  in the ini file if a prompt is wanted. If this line isn't there (or set to =0) it's without prompt.
That would avoid the action duplication (which I'm still not much a fan of tbh), wouldn't change existing behaviour but still get the posibility of a prompt if desired.

What do you think, would that cover your request?

**Comment by daxliniere** [comment]
Excellent line of thinking, man!

Personally, I think it would be better to ship with the safety on, but I can work with either.

**Comment by daxliniere** [comment]
In other words, I think the action should show the prompt by default, which can be disabled in the INI file.

**Comment by daxliniere** [comment]
Can you write a line to the INI file from SWS? As in, when the SWS update is released, it's first job is to write that value if it doesn't already exist.
