### ISSUE TITLE
All mouse solo actions ignore sends

### ISSUE THREAD

**Issue by StephanRoemer** [reaper-oss/sws#1181]
All mouse solo actions like "toggle play and solo..." will mute the sends (routing) of the current track, regardless of the setting in the preferences.
This is rather counterproductive. Could SWS respect the setting in the preferences or maybe add a second batch of actions "toggle play and solo in-place...."?

<a href="https://imgur.com/pkO6lvz"><img src="https://i.imgur.com/pkO6lvz.png" title="source: imgur.com" /></a>

**Comment by nofishonfriday** [comment]
@StephanRoemer 
Could you test with this SWS version please and let me know if it works as expected?
https://www.dropbox.com/s/vxvv12kdebfrkvj/reaper_sws-x64.dll?dl=0

(note that the .dll name has changed compared to last SWS version)

**Comment by StephanRoemer** [comment]
Wow, it does! Nofish, sooooo awesome! Thank you, thank you, thank you!!!!

**Comment by nofishonfriday** [comment]
Cool, thanks for testing.
It was a rather easy fix actually.

Btw. you can continue using this version if you want until next SWS (beta) gets released officially as it also contains all the other stuff that'll be in there.
https://gist.github.com/nofishonfriday/efc32c9c37953a7ba1abb2701eadddee

You wouldn't get an automatic update notice then but you'll probably spot it in the forum anyway I'd assume. :)

**Comment by StephanRoemer** [comment]
Amazing changes! Thanks nofish, will definitely keep that version in Reaper 😝 
Will definitely notice, when the official one gets released, since I'm always watching the forums :)
