### ISSUE TITLE
Menu updates!

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#119]
_From [swstim](https://code.google.com/u/swstim/) on April 18, 2010 05:20:28_

There's a lot of new SWS features, and the old "Extensions" menu is getting
long in the tooth.  I think the menu should be totally restructured to
reflect the best and most usable features.

If anyone has any ideas about menuing, please comment!

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=119_

**Comment by swstim** [comment]
Out of date.
