### ISSUE TITLE
Fix Linux instructions wiki

### ISSUE THREAD

**Issue by madskjeldgaard** [reaper-oss/sws#1190]
Hello

Thanks for your great work here. I love the SWS extensions and use them everyday. I recently switched to linux and followed your instructions for the build process (https://github.com/reaper-oss/sws/wiki/Building-the-SWS-Extension#linux), which mostly was pretty good but the last line `ln -s `pwd`/reaper_sws64.so .../REAPER/Plugins` is confusing and at least I couldn't figure out what to do with it. Instead, on my Ubuntu Studio machine, I would recommend `cp reaper_sws64.so ~/.config/REAPER/UserPlugins/` which would copy the .so file to the appropriate location (which will then free you up to delete all source code for sws you downloaded for the build process as well. 

Thanks

**Comment by cfillion** [comment]
Fixed, thanks!
