### ISSUE TITLE
FR: Loudness - add dual mono scanning mode (was: Bug in SWS - problem detected about loudness)

### ISSUE THREAD

**Issue by charlyromero** [reaper-oss/sws#1209]
Hello, I use SWS a lot, they are very useful to me. But I detected a measurement problem with loudness

It turns out that a while ago I found a contradiction in the reading of the integrated between Youlean and what the SWS measured. There were exactly 3LU of difference

I made measurements with white noise clips. And testing. I found where the error was

Apparently: it does not measure items that are "mono" correctly. With stereo, there is no problem. But with the "mono", there is 3dB difference.

The sound intensity result is even perceptible to the listening, so here I attach a project where you can make the measurements, compare readings between Youlean and SWS, and draw your own conclusions from this error.

https://mega.nz/#!SkAFTI7A!lXn_a8XFYLOO9BK0e2l18KT3mxn9prR2CqseDZL4vLU

1st Item: white noise, stereo in -8LUFS for both Youlean and SWS
2nd Item: white noise, mono at -5 for Youlean and -8 for SWS (bug)
3rd Item: white noise, stereo in -5 for Youlean and for SWS

This not only happens with white noise, it also happens to me with mono recordings that I make, there is always that bug present.

Conclusion: LUFS reading from SWS is failing for mono items. Even using "High precision mode" 

thank you

**Comment by nofishonfriday** [comment]
Replied [here](https://forum.cockos.com/showthread.php?p=2192327#post2192327)

As stated in the [linked comment](https://github.com/jiixyj/libebur128/issues/42#issuecomment-213695127) by the libebur128 developer, there seems no consensus how this should be handled 'correctly' and personally I also tend to to agree to this argument: so I wouldn't consider it a bug:
> while other organizations consider that the standard shouldn't trick the measure to compensate lack of standard conformance on the end user side. That would also create the issue that players that do enforce a pan law would then play the mono files with a different perceived loudness.

**Comment by charlyromero** [comment]
It is true, because what deceives in loudness is the dual mono output, which adds 3dB. Anyway, many times you work with voices or mono tracks, which will then be exported in stereo, adding those 3dB difference. It would be practical to add a function that compensates for that difference in item reading. Something like: read items as dual mono

**Comment by nofishonfriday** [comment]
> It would be practical to add a function that compensates for that difference in item reading. Something like: read items as dual mono

I've changed the title of this issue accordingly.
