### ISSUE TITLE
Loudness Bug: process item of short duration

### ISSUE THREAD

**Issue by charlyromero** [reaper-oss/sws#1212]
Process item of short duration: It causes an error in Reaper and the program is closed

With all due respect, I made a video to illustrate the problem https://youtu.be/5oALTVQxFjQ

With the latest version to date: 2.10.0 # 1 built on Feb 6 2019

Of Course, thank so much!

**Comment by cfillion** [comment]
This should be fixed in this development build: [sws-2.11.0.0-Windows-x64-2fc46c3e.exe](https://ci.appveyor.com/api/buildjobs/6yu5wyug8xhrcbxy/artifacts/build%2Fsws-2.11.0.0-Windows-x64-2fc46c3e.exe).

**Comment by charlyromero** [comment]
Ok Thank you very much for your prompt response, I hope you get it out soon in the official releases

**Comment by cfillion** [comment]
(Note that if you use the build above, you may not get an update notification when the official 2.11.0 will be released.)
