### ISSUE TITLE
BUG: reaper.CF_GetTrackFXChain(track)

### ISSUE THREAD

**Issue by Edgemeal** [reaper-oss/sws#1222]
reaper.CF_GetTrackFXChain(track) doesn't work if track has a name.

https://forum.cockos.com/showthread.php?t=227119

**Comment by cfillion** [comment]
Oops! Should be fixed in this build: https://ci.appveyor.com/api/buildjobs/c23xlweucosxlhow/artifacts/build%2Fsws-2.11.0.0-Windows-x64-f6a295cd.exe.

**Comment by cfillion** [comment]
Here's a better fix that ensure CF_GetTrackFXChain returns the correct FX chain even if two tracks with opened FX chain use the same number + name across multiple projects: https://ci.appveyor.com/api/buildjobs/iwbya322lbylam66/artifacts/build%2Fsws-2.11.0.0-Windows-x64-13f7e19a.exe.
