### ISSUE TITLE
wiki: New build instructions are broken (on Linux)

### ISSUE THREAD

**Issue by madskjeldgaard** [reaper-oss/sws#1224]
Hi
Last time I built SWS on Linux the instructions were quite different. Now there is only the one "Usage" section which I am trying to get through but there are errors / missing commands in the code. I may try the old linux instructions in stead but just so you know, these are the errors I found in the current instructions:

Under step 2, there seems to be a type where submodules is in plural when git seems to only understand submodule in singular:
```
# Step 2: Fetch dependencies (TagLib and WDL)
git submodules update --init
```
should be 
```
# Step 2: Fetch dependencies (TagLib and WDL)
git submodule update --init
```
Then, in step 4 it fails: 
`cmake -B build -DCMAKE_BUILD_TYPE=Debug`

results in "CMake Error: The source directory "/home/mads/sws/build" does not appear to contain CMakeLists.txt. Specify --help for usage, or press the help button on the CMake GUI."

Thanks

**Comment by cfillion** [comment]
Looks like you are using a version of CMake older than 3.13. (Fixed the git submodule typo)

**Comment by madskjeldgaard** [comment]
> Looks like you are using a version of CMake older than 3.13.3. (Fixed the git submodule typo, thanks!)

aha, you are right: On Ubuntu 18.04 Cmake is version 3.10.2

**Comment by cfillion** [comment]
On Ubuntu 18.04 you can install the latest CMake from the Snap Store (`snap install cmake --classic` or through Ubuntu Software, then run using `snap run cmake ...`), or the .sh installer on https://cmake.org/download/ (or build from source...). Ubuntu 19.04 and 19.10's main repositories have 3.13.4.

Alternatively you could use this automated Linux x86_64 build of SWS: https://ci.appveyor.com/project/reaper-oss/sws/builds/28677859/job/8sycu3g12j0ajobo/artifacts.

**Comment by madskjeldgaard** [comment]
removing my old version using `sudo apt remove cmake`and installing the latest via snap worked like a charm. Now I can sucessfully build SWS and all seems good and well. Thanks a lot!
