### ISSUE TITLE
sws-2.11.0.0-Windows-x64-5db88c1a.exe detected as containing a Trojan

### ISSUE THREAD

**Issue by gatesphere** [reaper-oss/sws#1233]
Tried downloading the new pre-release on Windows 10 x64, and Windows Defender kept flagging it as containing a trojan and deleting it.

Ran the file through VirusTotal and received quite a few hits: https://www.virustotal.com/gui/file/0877ca99113a747992ea480472f6a382db1691e983eb1d8e3a677b377fc40243/detection

Either these are false positives due to heuristics, or the installer package on the site is compromised.

**Comment by cfillion** [comment]
I submitted the Windows installer to Microsoft for analysis.

For some reason most detections vanish if I remove the main SWS DLL from the installer. https://www.virustotal.com/gui/file/0c4d5572aebd23c2ae7c3d8872f5e7e31e7bc7f32b252a89a0163ba54f4d7f62/detection

Although the DLL by itself is not being flagged. https://www.virustotal.com/gui/file/2790b1a482adbfb4b2a8d0a96380571fc07c6ef389c5cb673866362112dfef5a/detection

Removing the the check for running reaper.exe processes fixes all but one remaining detection. https://www.virustotal.com/gui/file-analysis/OTgyNTMzY2EwY2VjMjlkZmI2MjA0MTYxYWU5ZjRjMTg6MTU3NTU4NTI5NA==/detection
