### ISSUE TITLE
FR: Please export win32 API GetSystemMetrics

### ISSUE THREAD

**Issue by Breeder** [reaper-oss/sws#1235]
Guys, I have these cool functions I use on my private build of REAPER ReWorked to span many windows across all monitors. It's really a joy to be working with mixer or MIDI editor using all available monitors - in my current case, two 1080p monitors.

I would like to port this to public build, but because each person has different monitor setup I need some way to read that data.

If you could export [GetSystemMetrics](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics), that would help a ton in this case. Thank you!

**Comment by cfillion** [comment]
`NF_Win32_GetSystemMetrics` has been added in v2.12.0.
