### ISSUE TITLE
[v2.11.0.0 beta] 'SWS/wol: Set selected envelope height to maximum' scrolls envelope out of viewport (sometimes)

### ISSUE THREAD

**Issue by nofishonfriday** [reaper-oss/sws#1240]
report:
https://forum.cockos.com/showthread.php?p=2212495#post2212495

I can repro here too:
![wol Set selected envelope height to maximum](https://user-images.githubusercontent.com/7658194/70378230-4f65b400-191e-11ea-9c6f-37495e85e399.gif)

Can't repro so far with v2.10.0 (regression?)

**Comment by nofishonfriday** [comment]
commenting out Justin's code and using the legacy code instead seems to fix:
https://github.com/reaper-oss/sws/blob/08d3c6fce05191347092a55df6dd5d4764f1de9c/Breeder/BR_Util.cpp#L2259-L2267

**Comment by cfillion** [comment]
Yeah, git bisect also found c3c4310228fc6414dd4758f4901ca11bdbd11f8c to be the first bad commit.

**Comment by nofishonfriday** [comment]
I don't understand wjat's wrong with Justin's code currently but I think I can say using the legacy code again  instead wouldn't be that good either because there's the  `ENV_GAP` constant used wihich with the introduction of AIs is no longer a constant it seems.
![env gap](https://user-images.githubusercontent.com/7658194/70380420-a037d580-193b-11ea-98f6-51ffa58715e2.gif)

(That's also the problem with the envelope point detection offset I think:
https://github.com/reaper-oss/sws/issues/954, point 2)

**Comment by cfillion** [comment]
For some reason `GetMediaTrackInfo_Value(parent,"I_TCPY")` always returns zero (I'll investigate why later, maybe post a bug report). This could be a good workaround:

```diff
diff --git a/Breeder/BR_Util.cpp b/Breeder/BR_Util.cpp
index 9239c82c..bddbe32f 100644
--- a/Breeder/BR_Util.cpp
+++ b/Breeder/BR_Util.cpp
@@ -2258,12 +2258,18 @@ int GetTrackEnvHeight (TrackEnvelope* envelope, int* offsetY, bool drawableRange
 
 	if (GetEnvelopeInfo_Value)
 	{
-		WritePtr(offsetY, 
-			(int) GetMediaTrackInfo_Value(parent,"I_TCPY") + 
-			(int)GetEnvelopeInfo_Value(envelope,drawableRangeOnly ? "I_TCPY_USED" : "I_TCPY") 
-			);
+		int trackY = static_cast<int>(GetMediaTrackInfo_Value(parent, "I_TCPY"));
 
-		return (int)GetEnvelopeInfo_Value(envelope,drawableRangeOnly ? "I_TCPH_USED" : "I_TCPH");
+		if(!trackY)
+			trackY += GetTrackHeight(track, &trackY);
+
+		const int envelopeY = static_cast<int>(
+			GetEnvelopeInfo_Value(envelope, drawableRangeOnly ? "I_TCPY_USED" : "I_TCPY") );
+		const int envelopeHeight = static_cast<int>(
+			GetEnvelopeInfo_Value(envelope, drawableRangeOnly ? "I_TCPH_USED" : "I_TCPH"));
+
+		*offsetY = trackY + envelopeY;
+		return envelopeHeight;
 	}
 
 	// legacy - REAPER v5.981 and earlier
```

Either that or always using `GetTrackHeight`.

**Comment by nofishonfriday** [comment]
While at it, what do you think about bumping min. required version to 5.982? GetEnvelopeInfo_Value() ` was added there, could then be made mandatory and we could remove that legacy code altogether?

v5.979 - June 18 2019
v5.982 - August 17 2019
- only two month difference. :)

**Comment by cfillion** [comment]
Better solution:

```cpp
SCROLLINFO si{sizeof(SCROLLINFO), SIF_POS};
CoolSB_GetScrollInfo(GetArrangeWnd(), SB_VERT, &si);

const int trackY = si.nPos + static_cast<int>(GetMediaTrackInfo_Value(track, "I_TCPY"));

```

I'm fine with removing the legacy code (it was a bit tight when we started working on 2.11, but now it's 4 months old...). Oddly enough the additions of GetEnvelopeInfo_Value and tracks's I_TCPY/I_TCPH didn't make it to the final changelog...

**Comment by nofishonfriday** [comment]
This should also fix the envelope detection offset with `BR_MouseContext` I mentioned above I'd expect,  as it's the only place where ENV_GAP is used (apart from take envelopes but there it's fine because it hasn't changed).

Could then be also added to changelog. :)

**Comment by cfillion** [comment]
The envelope element hit detection offset does not appear to be fixed. `ENV_GAP` is still being used in BR_MousUtil.cpp and BR_Util.cpp.

**Comment by nofishonfriday** [comment]
Yeah, I just tried. :(
Would have been to good. :P
