### ISSUE TITLE
FR: Add SWS/NF: Toggle swing grid in MIDI editor

### ISSUE THREAD

**Issue by Breeder** [reaper-oss/sws#1243]
It would be nice to have a toggle action for swing so it completes the whole MIDI editor action set which currently consists of:
SWS/NF: Toggle triplet grid
SWS/NF: Toggle dotted grid

**Comment by juanriccio** [comment]
... and groove grid!

**Comment by StephanRoemer** [comment]
Yes, +1!

**Comment by nofishonfriday** [comment]
added in v2.12.0
