### ISSUE TITLE
FR: Add arrange grid actions that take into account dotted/triplet

### ISSUE THREAD

**Issue by Breeder** [reaper-oss/sws#1244]
Currently we have
- SWS/AW: Toggle dotted grid
- SWS/AW: Toggle triplet grid

But when these are engaged, actions like
- Grid: Set to 1/2
- Grid: Set to 1/4
- etc...

are set to off and instead these are used:
- Grid: Set to 1/3 (1/2 triplet)
- Grid: Set to 1/6 (1/4 triplet)
- etc...
- 

Would be nice to have a dedicated set of SWS actions that report toggle state no matter if one uses dotted and triplet grid. Cycle actions editor can't be used here because it would need IF that looks at 3 commands, and currently it can only look at 2 commands. Maybe it can nest commands - I will probably try that approach and let you know so maybe this FR becomes moot.

It would also be nice to have a dedicated action
-SWS/AW: Toggle swing grid
so it toggles dotted and triplet SWS actions off automatically _(that would make the behavior same as the MIDI editor which is much more natural than current Arrange implementation)_

P.S.
When one uses Swing grid, there are no problems here. I guess Cockos should fix this on their end, but maybe someone in SWS also wants to see this fixed so sharing here

**Comment by StephanRoemer** [comment]
Agreed, huge +1

**Comment by nofishonfriday** [comment]
added in SWS v2.12.0

**Comment by StephanRoemer** [comment]
Woah, aweomse nofish! Any ETA for an alpha?

**Comment by nofishonfriday** [comment]
v2.12.0 (and later) is already out as public beta for a while. :P
https://www.sws-extension.org/download/pre-release/
It's just that this issue was still open so I closed it now.

**Comment by StephanRoemer** [comment]
Ah my bad. I thought this is about NextGrid()!

**Comment by nofishonfriday** [comment]
Incidently I've just worked on this too. :)
If you're interested in testing (which would help) grab the build from here:
https://github.com/reaper-oss/sws/pull/1449#issuecomment-722523516

and post in that issue what you find.
Thanks.

**Comment by StephanRoemer** [comment]
Hey nofish, of course I will test this, very happy you already released a test build this!

**Comment by nofishonfriday** [comment]
Oops, sorry for deleting your comment (a glitch on my side) :)

**Comment by StephanRoemer** [comment]
No worries 😆
