### ISSUE TITLE
error about silent installation in the Windows installer

### ISSUE THREAD

**Issue by qt06** [reaper-oss/sws#1247]
When I run the windows installer with the silent parameter /S, it appears some errors.
1. The grooves were installed at the driver C root directory.
2. The installer don't support to specify directory.

Finally,, I wish the installer can support the silent parameters. Such as: sws.exe /S /D "e:\abc\reaper"

**Comment by cfillion** [comment]
Thanks for reporting this! Fixing for the next update. You can try it here under "Visual Studio 2019": https://github.com/reaper-oss/sws/pull/1255#issuecomment-565788965.
