### ISSUE TITLE
Decrease selected envelope points cut by a 1/3

### ISSUE THREAD

**Issue by funkbuqet** [reaper-oss/sws#1248]
After updating to Reaper 6.0, the action **SWS/BR: Decrease selected envelope points by X db** only decreases the db by 1/3 the value of X.

**Comment by nofishonfriday** [comment]
Which SWS version are you using?

**Comment by funkbuqet** [comment]
I downloaded and installed the latest version (v2.10.0 #1) for 64-bit
Windows to make sure I had the most up to date version. But the problem
persisted.

Ben Robinson
BRobinson.TRG@Gmail.com
(916) 947-9425

**Comment by nofishonfriday** [comment]
Should be fixed already in the v2.11.0 beta:
http://www.sws-extension.org/download/pre-release/

If you could test and report back that would be nice.

**Comment by funkbuqet** [comment]
That worked. Issue resolved. Thank you.

Ben Robinson
BRobinson.TRG@Gmail.com
(916) 947-9425

**Comment by nofishonfriday** [comment]
Thanks for reporting back.
