### ISSUE TITLE
'SWS/S&M: Unselect offscreen items' not working for items that are vertically offscreen.

### ISSUE THREAD

**Issue by Bird-Bird** [reaper-oss/sws#1250]
Footage of behaviour: https://streamable.com/429oi

I also cannot get the following actions to work:
- SWS/S&M: Toolbar - Toggle offscreen item selection (top)
- SWS/S&M: Toolbar - Toggle offscreen item selection (bottom)

These actions work as expected:
- SWS/S&M: Toolbar - Toggle offscreen item selection (right)
- SWS/S&M: Toolbar - Toggle offscreen item selection (left)

**Comment by nofishonfriday** [comment]
Confirmed here.

**Comment by daxliniere** [comment]
I recall reporting something similar a few years ago with _S&M_TGL_OFFSCREEN_ITEMS
I wanted to have it as a toolbar icon that 'warned' me when I was about to do something stupid like delete an item that was selected as part of a group but not within the viewport at the time.

In fact, it would be really cool if the delete action was modified to combine this offscreen feature, but that's for another thread...

**Comment by nofishonfriday** [comment]
@daxliniere 
You do know that they light up when assigned to a toolbar button and selected items are offscreen?
https://github.com/reaper-oss/sws/pull/1262#issue-356043066

So wouldn't that be a sufficient warning mechanism or do I misunderstand?

**Comment by daxliniere** [comment]
I would be perfect warning if it worked reliably. :)
