### ISSUE TITLE
Bug: SWS Notes window Wrap text UTF-8 bug

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#1252]
Hi,

In SWS Notes window, when unchecking the Wrap Text messes all the non ASCII characters (é,à etc) in the text editing window (these errors are then propagated to the items notes).

Demo:

![img](https://i.imgur.com/tad3opp.gif)

REAPER 6.01 and SWS 2.11.0

Thx!

**Comment by cfillion** [comment]
Good catch! It's getting the text in UTF-8 but setting it using an ANSI function.

**Comment by cfillion** [comment]
Wrap text is also broken on macOS and Linux... there it only reopens the dialog box without actually wrapping the text.

**Comment by cfillion** [comment]
@X-Raym The builds are here if you'd like to try the fix early: https://github.com/reaper-oss/sws/pull/1254#issuecomment-565787159.
