### ISSUE TITLE
Contextual toolbars: option to close toolbar(s) when clicking anywhere outside

### ISSUE THREAD

**Issue by mkruselj** [reaper-oss/sws#1260]
I'm not sure if this is possible, but I'm wishing for this more and more. The auto-close option is not particularly useful in certain cases, because it only allows you a single click on the toolbar...

Here's an example contextual toolbar:

![image](https://user-images.githubusercontent.com/2393720/71238695-11489700-2305-11ea-9734-c4ad8489d328.png)

It'd make a ton of sense to just close it automatically if I click away outside of the toolbar itself.

**Comment by cfillion** [comment]
Like this? I'm not sure whether the original behavior should be preserved though. Adding a new option might be more challenging.

![Screen capture](https://i.imgur.com/f9pIg1K.gif)

You can try it with this build: [sws-2.11.0.0-Windows-x64-autoclose-toolbars-ae44fb8d.exe](https://ci.appveyor.com/api/buildjobs/kdoij37qteketq9l/artifacts/build%2Fsws-2.11.0.0-Windows-x64-autoclose-toolbars-ae44fb8d.exe).

**Comment by mkruselj** [comment]
Yeah like that!

**Comment by cfillion** [comment]
> Ah, it requires that you first click on any of the toolbar buttons or toolbar itself

This is likely caused by the "Set toolbar to foreground on load" option being disabled. By default contextual toolbars don't have focus when opened.

**Comment by mkruselj** [comment]
Ha! You are correct. Now it works like I want it to. Brilliant!
