### ISSUE TITLE
Contextual toolbars: cannot open MIDI toolbars in non-MIDI editor contexts?

### ISSUE THREAD

**Issue by mkruselj** [reaper-oss/sws#1261]
Is this true? I can't seem to get this working. I wanted to have the same shared CC lane toolbar between MIDI editor and inline MIDI editor, but the toolbar doesn't open for inline MIDI editor. Tried to assign the same toolbar to other arrange view contexts (TCP, MCP, whatev), but no workie.

Is it possible to fix this?

**Comment by mkruselj** [comment]
Can anyone confirm this?

**Comment by cfillion** [comment]
Confirmed, contextual toolbars fail to detect the MIDI Inline Editor is under the mouse unless the Arrange context also has a toolbar assigned.

Opening MIDI toolbars on non-MIDI contexts works here though. However running actions form the MIDI Editor Action List requires the full MIDI editor to be open.
