### ISSUE TITLE
Various issues with new 'Multimonitor Aware v2' HiDPI mode.

### ISSUE THREAD

**Issue by Joe90Prod** [reaper-oss/sws#1264]
The new 'multimonitor aware v2'  HiDPI mode introduced in 6.02 dev1219 seems to break functionality of the all of the 'move window to cursor' actions such as 'SWS/BR: Move active floating track FX window to mouse cursor (horizontal: middle, vertical: middle) '. 

My specific use case is - main monitor is 4K and 200% scaling, second monitor 1080 and 100% scaling.  Win 10 x64.  The issue occurs when the window I'm trying to move is on the high res, scaled main monitor  and the mouse cursor is on the lower res unscaled second monitor.  Nofish mentioned on the forum that the issue should be raised here, so that's what I'm doing. 

Also, various SWS/Reapack windows are looking odd and jumbled in this new HiDPI mode.  Justin mentioned this - https://forum.cockos.com/showpost.php?p=2220991&postcount=12

**Comment by cfillion** [comment]
Fixing the window sizing bug as per Justin's comment. I'm also working on a solution for the "Move active floating track FX window" actions. If there are other actions not working right with Per-Monitor v2 DPI awareness, they would have to be fixed on a case-by-case basis.

Could you check if these builds behave nicely with your screen setup and multimonitor aware v2 mode?

- [sws-2.11.0.0-Windows-x64-hidpi-a142da95.exe](https://ci.appveyor.com/api/buildjobs/uafmq6q04wb5gj33/artifacts/build%2Fsws-2.11.0.0-Windows-x64-hidpi-a142da95.exe)
- [reaper_reapack-x64.dll](https://ci.appveyor.com/api/buildjobs/jvi4m49clnvw0o0u/artifacts/build%2Freaper_reapack-x64.dll)
