### ISSUE TITLE
BUG: Intermittent SWS/BR: Insert new envelope point at mouse cursor using value at current position (obey snapping)

### ISSUE THREAD

**Issue by daxliniere** [reaper-oss/sws#1266]
Hey guys,
I noticed on my laptop that _BR_ENV_POINT_MOUSE_CURSOR only works some of the time with REAPER v5.99x64 using the Dec 7th build of SWS. (2.11.0.0)

Happy holidays,
Dax.

**Comment by cfillion** [comment]
Seems to work as expected here. What does it do when it "doesn't work"? Double check that the envelope is selected and the main window is focused (unless the shortcut's scope is set to Global).

**Comment by daxliniere** [comment]
Hey Christian, thanks for looking into this.
I'm not sure what to tell you, but using it as I have always done, about 90% of the time, the action does literally nothing. It's an action I've been using solidly for probably over 5 years, so I know it intimately well (how and when it should work).
Are you running Reaper 5.99? (I'm pretty sure I need a new licence for 6.)

**Comment by cfillion** [comment]
Yes, I tried on 5.99 (I haven't upgraded to v6 yet). Could you try [this build](https://ci.appveyor.com/api/buildjobs/swm6x6jy32bud3h9/artifacts/build%2Fsws-2.11.0.0-Windows-x64-debug-createenvpointmouse-36a7d652.exe)? It will print debug messages to the ReaScript console when that action is run. If it is stopping prematurely for some reason, it should give clues where to look. Copy/paste the output when it works vs when it doesn't here.

**Comment by fakemaxwell** [comment]
Working:

Hello CreateEnvPointMouse
	testing position and visibility: 96.862693 and 1
	validating ID: -1 and 0
	Not Tempo
ByeBye CreateEnvPointMouse

Not Working:

Hello CreateEnvPointMouse
	testing position and visibility: 92.498198 and 0
ByeBye CreateEnvPointMouse

**Comment by cfillion** [comment]
Confirmed, thanks! It was the same bug as #1240. It happens when the arrange view is scrolled.

It should be fixed in this build: [sws-2.11.0.0-Windows-x64-fix-scroll-to-envelope-78e5aa32.exe](https://ci.appveyor.com/api/buildjobs/4thbaxnu9osbrhaa/artifacts/build/sws-2.11.0.0-Windows-x64-fix-scroll-to-envelope-78e5aa32.exe).
