### ISSUE TITLE
SWS/AW pan mode issue

### ISSUE THREAD

**Issue by Fra3L** [reaper-oss/sws#1267]
SWS/AW Set selected tracks pan mode to ... 
Has stopped working correctly.
Changes may or may not happen in TCP but fail in MCP.
When switching from other modes such as "Dual Pan" the panning changes but not the image file.  
Changes occur after tracks are unselected
Using REAPER 6 
I hope this was the correct forum, Thanks

**Comment by cfillion** [comment]
Fixing, thanks!

Note that this is only a visual glitch. The effective track pan mode is actually changed immediately.
