### ISSUE TITLE
SWS unindent selected tracks - BUG with nested tracks

### ISSUE THREAD

**Issue by highvoltaged** [reaper-oss/sws#1275]
This one is very hard to describe in words, so i made a screenshot.
http://prntscr.com/qj9mze

In this scenario, if you use action "SWS unindent selected track(s)" on track #3, it gets correctly unindented, but everything under track #4 gets indented one step.

Thanks
Matt

**Comment by cfillion** [comment]
Fixing for the next version, thanks! You can try it beforehand using the builds listed here: https://github.com/reaper-oss/sws/pull/1278#issuecomment-570906356.
