### ISSUE TITLE
FeatureRequest: API-access to S&M-Subtitles

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#1276]
I recently toyed around with the subtitles-feature of SWS, which inserts tons of markers for a subtitle-track. I tried to edit the subtitles, BUT the subtitles weren't updated in the subtitle-window, as it doesn't read them from the regions/markers, but from the extension-valuestore S&M_SUBTITLE

So, I would love to have get/set access to the following:

```
<EXTENSIONS
    <S&M_SUBTITLE
```

so I could update that and synchronize the stored subtitles with the texts in the markers/regions.

**Comment by nofishonfriday** [comment]
X-Raym requested this also some time ago, so I added these:
[NF_GetSWSMarkerRegionSub( )](https://www.extremraym.com/cloud/reascript-doc/#NF_GetSWSMarkerRegionSub), [NF_SetSWSMarkerRegionSub()](https://www.extremraym.com/cloud/reascript-doc/#NF_SetSWSMarkerRegionSub)

**Comment by mespotine** [comment]
Thank you :1st_place_medal:
