### ISSUE TITLE
"SWS/wol: Set selected envelope height to maximum" doesn't seem to take into account automation item lane (like 16 pixels?)

### ISSUE THREAD

**Issue by Breeder** [reaper-oss/sws#1279]
Title says it all:
"SWS/wol: Set selected envelope height to maximum" doesn't seem to take into account automation item lane (like 16 pixels?) while scrolling/zooming the envelope to the max

**Comment by Breeder** [comment]
Also, I'm not sure how this scales with dpi, so that too needs to be taken into account (I haven't tested much DPI stuff, so I'm not sure if you can just multiply with DPI modifier or you gotta check for pixel sizes for each DPI scale)

**Comment by cfillion** [comment]
Confirmed! This happens in REAPER v6 only. The scrolling doesn't have that weird offset in v5 (assuming the condition for triggering bug #1240 isn't met).
