### ISSUE TITLE
Region Playlist: "Move edit cursor when clicking regions" state resets when restarting Reaper

### ISSUE THREAD

**Issue by daleonov** [reaper-oss/sws#1289]
**Way to reproduce:**
In Region Playlist **right click -> Options -> check "Move edit cursor ..."**. Save project, close Reaper, launch again and open the project, that option is always unchecked. If you just close and recall project without closing Reaper, it's fine. When you close Reaper, it gets reset.

Same behavior on **PC and Mac, Reaper 6.03 and SWS 2.11.0**, but had this issue for at least a year.

I want to use this feature for live playback, so I can switch between the songs on stage by just clicking on the name of the region. But having to manually check this box every time isn't cool, especially during extremely brief line checks on stage.

**Request**
Make it persistent global setting or at least add an action to automate toggling this box during startup. Thank you!
![sws playlist bug](https://user-images.githubusercontent.com/5140018/72526424-71d0e280-3877-11ea-9af9-bbd78e1fa35b.png)

**Comment by cfillion** [comment]
Thanks! That option was actually being saved as "Seek playback when clicking regions" (overriding that option). Fixing for the next version.

**Comment by daleonov** [comment]
That was fast, thank you! cheers
