### ISSUE TITLE
Project Management > project list not loaded

### ISSUE THREAD

**Issue by daeavelwyn** [reaper-oss/sws#1293]
Hello,

I got an issue with SWS extensions project management since Reaper 6 (I guess...).  I'm using Reaper v6.03 - January 13 2020 on windows 10 entreprise LTSC 1809.  SWS 2.11 08d3c6fc 7 dec 2019

Steps :
1-  open projects in multiple tabs in Reaper  
2-  go to Extensions > project management > save list of open projects
3-  save the file (on my desktop in my case)
4-  save project modifications and close Reaper
5-  open Reaper
6-  go to extensions > Project Management > Open projects from list...

Expected behaviour : 
Reaper should open every projects previously saved in the rpl file in different tabs

Observed behaviour : 
Reaper open and close each project listed in the RPL file.

Here is the content of my RPL file : 
`X:\owncloud\Sigma 5\whistleblower-intro\intro-whistleblower_rstructure-rojava.rpp
X:\owncloud\Sigma 5\WhistleBlower3\WhistleBlower3.rpp
X:\owncloud\Sigma 5\whistleblower4\whistleblower4.rpp
`

Let me know if I can make futher tests to help solving this issue :)

**Comment by cfillion** [comment]
I can reproduce a regression in SWS v2.11.0 (fixing that!), but v2.10.0 should correctly open the projects in new tabs. Can you double check the SWS version you're using?

**Comment by daeavelwyn** [comment]
Hi cfillion,

Yes, you a re right, i'm using sws 2.11 08d3c6fc 7 dec 2019, sorry for this error :-/
