### ISSUE TITLE
API Missing Doc: Tag Lib "track"

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#1302]
Hi,

I discover that you could also set "track" to SNM_ReadMediaFileTag, to set track number.

this isn't shown in the doc : https://www.extremraym.com/cloud/reascript-doc/#

Thx !

**Comment by nofishonfriday** [comment]
Actually both `SNM_ReadMediaFileTag` and `SNM_TagMediaFile` support 'track' tag, both undocumented.
Adding to the doc, thanks.
