### ISSUE TITLE
CF_GetTrackFXChain

### ISSUE THREAD

**Issue by Edgemeal** [reaper-oss/sws#1305]
reaper.CF_GetTrackFXChain(track), returns nil if track is a folder.

**Comment by cfillion** [comment]
Ah, good catch. It's searching for the FX chain window by title and folder tracks have " (folder)" appended.

**Comment by Edgemeal** [comment]
Ya, my FindWindow code missed "(folder)" too so was curious if your function had that covered, hopefully its the last catch! ;-)

**Comment by Edgemeal** [comment]
This function also fails when the fx chain window is in the docker.
