### ISSUE TITLE
FNG Groove tool needs updating for REAPER 6 CC shapes

### ISSUE THREAD

**Issue by nofishonfriday** [reaper-oss/sws#1307]
report (and confirmed here):
https://forum.cockos.com/showthread.php?p=2242119#post2242119

When having set CC shapes other than square they are resetted to square when applying a groove.

![gif](https://i.imgur.com/DPTZ6p2.gif)

From a brief look, the newly added `ENV` line in the `<SOURCE MIDI` state chunk would have to be taken into account in the Groove tool (1st token: CC shape, second token: ?, 3rd token: bezier tension).

![gif](https://i.imgur.com/Bp1qNUZ.jpg)

**Comment by dacameron** [comment]
Just responding to the PM Olli sent me. Shouldn't be too hard to fix. Not sure when I'll get time though. When is reaper 6 due to be out?

**Comment by nofishonfriday** [comment]
Hi,

nice, thanks for getting back.
Reaper 6 is already out, but the bug just showed up recently. :)

Note that the SWS build process has changed meanwhile, it's now cmake based (no more VS/XCode project files):
https://github.com/reaper-oss/sws/wiki/Building-the-SWS-Extension

**Comment by cfillion** [comment]
All actions that construct a `RprMidiTake` in non-read-only mode are affected. (Such as "SWS/FNG: Select muted MIDI notes in active MIDI editor".)

The MIDI take gets corrupted: any Note or CC event after the first ENV chunk line is duplicated (increasing the length of the MIDI source)!

![Screencap](https://i.imgur.com/6DyWQ2S.gif)

**Comment by nofishonfriday** [comment]
It's mentioned in [original report](https://forum.cockos.com/showthread.php?p=2242119#post2242119) ("and extend item, and some data will be copied later. ") but somehow missed it when putting here. :/
