### ISSUE TITLE
Add option to create more snapshot create & recall actions in the S&M.ini file.

### ISSUE THREAD

**Issue by Infrabass** [reaper-oss/sws#1310]
Hi!

I know we can expand the number of slots available for the SWS resource window (up to 255 if I'm correct) by moding the S&M.ini file but I can't find a line related to snapshot actions.
I find 12 snapshots actions a little bit short for more demanding workflow.
It would be awesome!

**Comment by nofishonfriday** [comment]
From the SWS change log (old entry from 2014, admittedly I missed this too till now):
> Snapshots: the default number of recall actions is now configurable in REAPER.ini
> Edit the key "DefaultNbSnapsRecall" in the section [SWS] (quit REAPER before editing this file!)

Number of 'Save as snapshot n' actions can't be set dynamically currently though.

**Comment by Infrabass** [comment]
Awesome!
I didn't know there were some SWS options in the Reaper.ini file

**Comment by cfillion** [comment]
New recall actions are automatically added as additional snapshots are created.

I think it makes sense for both of these actions to have their quantity configurable via S&M.ini like all the other SWS dynamic actions. Working on a patch (with `DefaultNbSnapsRecall` automatically moved into S&M.ini)...

I don't know whether new "Save as snapshot" actions should also be added as new snapshots are created. Any opinions?

Also `DefaultNbSnapsRecall` is currently unbounded, so big values can break REAPER as it can attempt to register more actions than is possible within the 16-bit command ID limit. Migrating to S&M.ini will also fix that by limiting it to 255.

**Comment by nofishonfriday** [comment]
> I'm not sure whether new "Save snapshot n" actions should also be added as new snapshots are created. Any opinions?

If you make the default quantity configurable I'd think it should be fine as is.
