### ISSUE TITLE
FR: Action: Track: Open/close UI for INPUT FX #1-8 on last touched track

### ISSUE THREAD

**Issue by FlubnubBub** [reaper-oss/sws#1311]
Action: Track: Open/close UI for INPUT FX #1-8 on last touched track

Input FX could use some love.

**Comment by nofishonfriday** [comment]
This Lua script seems to work here.

```
local FX_number = 1 -- set desired FX # here, 1-based

local track = reaper.GetLastTouchedTrack()
if track ~= nil then 
  local fxIdx = 0x1000000+(FX_number-1) -- 0x1000000 accesses input / monitoring FX
  if reaper.TrackFX_GetFloatingWindow( track, fxIdx) ~= nil then -- is floating?
    reaper.TrackFX_Show(track, fxIdx, 2) -- close
  else
    reaper.TrackFX_Show(track, fxIdx, 3) -- float
  end
end
```

Let me know if it does it for you.

**Comment by FlubnubBub** [comment]
This is great.  It doesn't toggle.  Once the fx is floating, sending the command again has no effect.  I don't really need it to toggle for my purposes.  
Much appreciated.

**Comment by nofishonfriday** [comment]
Toggling works here when assigning the script to a shortcut with modifier (e.g. Ctrl+I), I think these are always 'passed through', but not when assigning to a 'pure' shortcut (e.g. I).

Anyway,  would you think the request is sufficiently covored so we can close this issue? :)

**Comment by FlubnubBub** [comment]
I tried assigning a global shortcut with modifier, and also non-global.  It still doesn't toggle on my system (Win 7/64).   But honestly, I don't need it to toggle, so I'm happy.  Let's close 'er.
