### ISSUE TITLE
Deficient heal after "SWS/BR: Split selected items at stretch markers"

### ISSUE THREAD

**Issue by Buy-One** [reaper-oss/sws#1316]
This was reported on the forum some time ago without conclusive response. 

https://forum.cockos.com/showpost.php?p=2236384&postcount=2759
https://forum.cockos.com/showpost.php?p=2236675&postcount=2763

I haven't found the issue entry in the tracker and without being able to know on whose side the issue is I repeat the report.

What's not getting healed with the native action "Item: Heal splits in items" is the 1st stretch marker split to the right of the loop divider notch. Splits of any other type get healed regardless of the loop mode.

GIF animation:

https://stash.reaper.fm/38153/Deficient%20Heal%20after%20Split%20at%20Stretch%20Markers.gif
https://stash.reaper.fm/38155/Regular%20splits%20heal%20VS%20Stretch%20markers%20splits%20heal.gif

Thank you

**Comment by cfillion** [comment]
As nofish observed on the forum (https://forum.cockos.com/showpost.php?p=2236428), this is not a SWS bug. It can be duplicated with the native split actions without SWS being installed. The bug is within REAPER's built-in split or heal feature.

**Comment by Buy-One** [comment]
I've done some more testing and confirm that it's REAPER's bug.
