### ISSUE TITLE
BR_TrackFX_GetFXModuleName bug with Video Processor in chain

### ISSUE THREAD

**Issue by L-B-X** [reaper-oss/sws#1326]
Hi nofish et all,

Just a heads up - don't know if this has been mentioned yet as I haven't read the entire thread - but found a bug in a function I use quite a bit.

BR_TrackFX_GetFXModuleName

The bug is that it ignores video processor entries in the FX list.

and because it ignores them - all the fx indexes become out of sync for any subsequent fx in the chain.

So say I have

FX 0: ReaEQ
FX 1: Video Processor
FX 2: ReaComp

looping through 0-2 track fx indexes and running BR_TrackFX_GetFXModuleName on the index - you get

FX 0: ReaEQ.dll
FX 1: ReaComp.dll
FX 2: <nothing>

I'm guessing it's just not looking out for the <VIDEO_EFFECT tag or maybe it gets confused by the additional < > characters used to identify the CODE section.

An example of video effect chunk data:

Code:
```
<VIDEO_EFFECT "Video processor" ""
<CODE
// Item fades affect video
input_track(0) > 0 ? (
  input_info(0,project_w,project_h,0,ta=0);
  ta < 1 ? (
    gfx_blit(input_next_item(0),1);
    (gfx_a=ta)>0 ? gfx_blit(0,1);
  );
);
>
CODEPARM 0.0000000000 1.0000000000 0.0000000000 0.0000000000 1.0000000000 0.0000000000 1.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000
>
FLOATPOS 1695 1479 897 553
FXID {FE26B8AD-3BC4-478F-A131-BE729344B478}
WAK 0 0
```

Anyway - thought I'd mention this. And as always - thanks for all your work on this amazing extension - without it - it would be impossible to create pretty much all of my scripts.

Thanks,
Leon.

**Comment by cfillion** [comment]
Fixing, thanks!

**Comment by nofishonfriday** [comment]
@cfillion Thanks. 
[NF_TakeFX_GetModuleName()](https://www.extremraym.com/cloud/reascript-doc/#NF_TakeFX_GetModuleName) expectedly has the same issue currently (as it also uses the SNM_FXSummaryParser).

**Comment by cfillion** [comment]
> edit:
> I just noticed this now for some reason but it's NF_TakeFX_GetModuleName vs BR_TrackFX_GetFXModuleName. Mine should maybe be renamed (NF_TakeFX_GetFXModuleName) for consistency?

Yes, with 2.11 being labeled as a "bleeding-edge" release, I think some backward-incompatible changes is acceptable until the next "stable" release.

**Comment by nofishonfriday** [comment]
Thanks.
Glitch in current whatsnew (https://github.com/nofishonfriday/sws/blob/sws-2020-01/whatsnew.txt#L78):
+Rename NF_TakeFX_GetModuleName to NF_TakeFX_GetModuleName (for consistency with BR_TrackFX_GetFXModuleName)
should be
+Rename NF_TakeFX_GetModuleName to NF_TakeFX_Get**FX**ModuleName (for consistency with BR_TrackFX_GetFXModuleName)
