### ISSUE TITLE
BR_EnvSetPoint() wrong point value

### ISSUE THREAD

**Issue by bFooz** [reaper-oss/sws#1327]
This is a regression.

The value supplied to BR_EnvSetPoint is not obeyed and the resulting point value is too high or low in some cases.
```
BR_Envelope = reaper.BR_EnvAlloc(envelope, false)
active, visible, armed, inLane, laneHeight, defaultShape, minValue, maxValue, centerValue, type, faderScaling = reaper.BR_EnvGetProperties(BR_Envelope)
value1 = reaper.BR_EnvValueAtPos(BR_Envelope, editCursor) --get value of underlaying envelope

--create new point
reaper.BR_EnvSetPoint(BR_Envelope, -1, editCursor, value1, defaultShape, true, 0)
```

BUG - the created point has the max value
EXPECTED - the point should have the same value as the underlaying envelope before it was created

**Comment by cfillion** [comment]
This 2.10 regression concerning fader scaling volume envelopes was fixed in version 2.11.

https://www.sws-extension.org/download/pre-release/
