### ISSUE TITLE
Bug: BR_SetMediaSourceProperties set section timing issue

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#1330]
Hi !

So I was trying to make a simple action to activate Section section from media item properties but it seems there is something wrong with BR_SetMediaSourceProperties has timing is not respected...

Look at the screenshot below

![demo](https://i.imgur.com/cbWhaph.gif)

```lua
    local item = reaper.GetSelectedMediaItem( 0, 0 )
    local take = reaper.GetActiveTake(item)
    if take and not reaper.TakeIsMIDI(take) then

        retval, section, start, length, fade, reverse = reaper.BR_GetMediaSourceProperties( take )
        reaper.BR_SetMediaSourceProperties( take, true, start, length, fade, reverse )
        
      end
      
      reaper.UpdateArrange()
```

Thx for taking a look !

**Comment by cfillion** [comment]
It seems to work here (SWS 2.12/REAPER 5.99 & 6.14). Am I missing any steps?

![Screencap](https://i.imgur.com/kCi5Tcy.gif)

**Comment by X-Raym** [comment]
@cfillion Can you try with section not starting at source start ? This was my case.

**Comment by cfillion** [comment]
That was it, thanks! The take's start offset is automatically updated. Add this to the script:

```lua
reaper.SetMediaItemTakeInfo_Value(take, 'D_STARTOFFS', 0)
```

**Comment by X-Raym** [comment]
@cfillion Thanks for debugging ! One single line ? Well, then maybe it doesn't need to be fixed. But I don't see any reason why keeping the start offset at the original position... it produces kind of unpredictable results, so handling that right from the SWS function can avoid bad surprises. :P

**Comment by cfillion** [comment]
A script could set a different start offset before calling `BR_SetMediaSourceProperties` and not expect it to override that change. 

`BR_SetMediaSourceProperties` could be used to change some one of the source's properties (eg. a script that shifts the section by *n* seconds), for which resetting the source offset would be undesirable.

**Comment by X-Raym** [comment]
Well this could be done only under certain conditions like the take isnt already a section, and sectionnisset to true (so in this case it mimic the click of the Section button in media explorer window) but I get your point. We have a one line fix on script side so we can considered this fixed !
