### ISSUE TITLE
BUG: Loudness doesn't work for items with take volume automation

### ISSUE THREAD

**Issue by teeramusic** [reaper-oss/sws#1335]
None of the loudness features work for items with take volume automation

**Comment by nofishonfriday** [comment]
Which SWS version are you using?
Current beta contains a fix* for this.
https://www.sws-extension.org/download/pre-release/

*added in v2.10.0:
>Fix item Loudness analysis if take contains vol. envelope and item position not 0.0

**Comment by teeramusic** [comment]
I'm using the latest stable (2.10.0 #1 Feb 6, 2019) but I'll try grabbing the beta. Will using the beta make my reaper less stable?

**Comment by nofishonfriday** [comment]
Closing because likely fixed in v2.10.0 and no feedback from OP.
