### ISSUE TITLE
"SWS/FNG: Show only used CC lanes" does not restore "Program/Bank Select" lane

### ISSUE THREAD

**Issue by icalvo** [reaper-oss/sws#1344]
It instead sets three separate CC Lanes for "00 Bank Select MSB", "32 Bank Select LSB" and "Program" instead of the very useful "Program/Bank Select" lane that reunites all of them and shows the events as "pencils" with labels with the selected program name.

"SWS/BR: Show only used CC lanes (detect 14-bit)" shows a similar behavior, except it creates a weird "00/32 Bank Select" 14bit lane and the "Program" lane.

My suggestion would be instead to create the "Program/Bank Select" lane when you detect any Bank/Program MIDI events. I don't think the standard CC lane representation is of any use for these kind of events.

Before action:
![image](https://user-images.githubusercontent.com/187623/81128741-4f57f780-8f42-11ea-85f3-bd711670d650.png)

After action:
![image](https://user-images.githubusercontent.com/187623/81128675-1ddf2c00-8f42-11ea-9972-3c8353b3411e.png)

**Comment by icalvo** [comment]
`GetUsedCCLanes` at `BR_MidiUtil.cpp` does never return lane 131 ("Program/Bank Select"). Check https://github.com/icalvo/sws/commit/cd1c77d77470fb2df56bb44faa76341267276d93 at my fork for an implementation proposal. It adds 131 when it sees a Program Change. 

With this change, all these actions ("SWS/FNG: Show only used CC lanes", "SWS/FNG: Hide unused CC lanes", "SWS/BR: Show only used CC lanes (detect 14-bit)") behave better in the sense that they do add a 131 lane, or do not remove it when a PC MIDI event is there.

I still don't like the fact that that the "Show" actions add the pretty useless 00, 32 and PC lanes. In my local repo I also have a quite opinionated tuning of `ShowUsedCCLanes` at `Finger/MidiLaneCommands.cpp` that removes those lanes and never adds them. I understand that you could use 00 and 32 as non-standard CC controllers, but the standard behavior should be not to clutter your lanes.

**Comment by nofishonfriday** [comment]
@icalvo 
Want to submit a pull request with your fix? :)

**Comment by icalvo** [comment]
Certainly! I wanted first to discuss whether you want simply to add/remove the 131 lane. or do more within the actions. But I find it logical to leave the simple logic of "I add every possible lane that will show info for the selected item, no matter if it is useful or not". My problem is that then I lack a set of actions: "Hide CC lane NNN" for all NNN (same as "Set CC to NNN"). That way I could set up my desired behavior with a custom action like:

1. "SWS/FNG: Show only used CC lanes" (with my patch this creates
2. "Hide CC lane 000"
3. "Hide CC lane 032"
4. "Hide CC lane PC"

So I will submit a PR for the simple thing and then I will create a feature request for the "Hide CC lane NNN" and see if I can implement it.
