### ISSUE TITLE
Contextual toolbars lost partial open functionality in Reaper 6.09

### ISSUE THREAD

**Issue by mattpirog** [reaper-oss/sws#1347]
Contextual toolbars will no longer open over the Arrange view track area or empty track area. Under mouse cursor open/close or exclusive. Tried with multiple themes including the default reaper 6. 

When hitting run or an assigned hot key in the previously mentioned areas, reaper thinks [toggle master track visible] was intended
![SWS_reaper_bug_01](https://user-images.githubusercontent.com/65033464/81426730-9bb05c80-9127-11ea-8737-5b4a052cdb6b.PNG)

**Comment by cfillion** [comment]
Is this SWS 2.10? Support for REAPER 6 was added in SWS 2.11.

https://www.sws-extension.org/download/pre-release/

**Comment by mattpirog** [comment]
Ahaa! Thank you very much. I was reluctant to install pre-release or beta
builds. But 2.12 has fixed the issue.

Please pardon the bug noise.
