### ISSUE TITLE
 FR: Auto Color/Icon/Layout : copy-paste rule info without track selection messing it up

### ISSUE THREAD

**Issue by djabthrash** [reaper-oss/sws#1351]
Hi !

As pointed out in the now closed https://github.com/reaper-oss/sws/issues/1350, when creating new rules Auto Color/Icon/Layout, i often add a new rule, and copy/paste rule info from another rule into my new rule, as a starting point, and then tweak the new rule from there (changing the filter, etc).

I found out that if you happen to have no tracks selected in your Reaper project (which can happen if you just open Reaper to tweak your Auto Color/Icon/Layout), then if you select a rule line and "Ctrl + C" it to copy it, you get an "error" window with the following message :
"no tracks selected"

Screenshots : 

No tracks selected : 
![Untitled 4](https://user-images.githubusercontent.com/65073777/81474841-4ef08280-9208-11ea-9bba-b0ad8198bbc1.jpg)

At least one track selected : 
![Untitled 3](https://user-images.githubusercontent.com/65073777/81474894-b0185600-9208-11ea-9a54-ef5dba3a0837.jpg)

No tracks at all (so no track selected) : 
![Untitled 1](https://user-images.githubusercontent.com/65073777/81474916-dc33d700-9208-11ea-97b3-edbabbc58146.jpg)

I think it should be nice to be able to edit your Auto Color/Icon/Layout without needing to select any tracks in your project, since when you chose to apply Auto Color/Icon/Layout, it does it to ALL the tracks in your projects, regardless of your track selection, so track selection should not be considered in the Auto Color/Icon/Layout workflow.

Furthermore, if you select tracks in your project, and then try to copy paste info from one rule to another in Auto Color/Icon/Layout, then it copy-pastes tracks instead of copy/pasting rule info in Auto Color/Icon/Layout, as shown below : 

1) i add a new rule in Auto Color/Icon/Layout : 

![Untitled 3](https://user-images.githubusercontent.com/65073777/81475238-3fbf0400-920b-11ea-81a9-143d04a5075c.jpg)

2) i select at least one track (named "RT") to be able to copy rule #51 info in Auto Color/Icon/Layout :

![Untitled 4](https://user-images.githubusercontent.com/65073777/81475240-49486c00-920b-11ea-93b6-46b81dca790d.jpg)

3) i select rule #55 (my new rule) in Auto Color/Icon/Layout (NB : my track "RT" is still selected) : 

![Untitled 5](https://user-images.githubusercontent.com/65073777/81475241-4f3e4d00-920b-11ea-8e65-3346cc9a72ea.jpg)

4) i "Ctrl+V" on rule #55 (my new rule) in Auto Color/Icon/Layout, and instead of pasting rule #51 info into rule #55, it copies my "RT" track in the TCP :

![Untitled 6](https://user-images.githubusercontent.com/65073777/81475244-54030100-920b-11ea-8bac-553edd6a3bd2.jpg)

I'm pretty sure back then (even until very recently) you could just copy-paste rule info from one rule to another in Auto Color/Icon/Layout, and track selection in your TCP/MCP would not mess with it.
Now it's impossible to do so, which is a shame.

It would be great to fix this !

**Comment by cfillion** [comment]
Auto Color does not support copy/pasting rules. The Ctrl+C and Ctrl+V shortcuts just goes straight to REAPER which informs that it cannot copy selected tracks when no tracks are selected.

You can, however, use Ctrl+C and Ctrl+V after opening the edit field for any of the rule's column by double-clicking.

**Comment by djabthrash** [comment]
@cfillion : you're totally right, thank you !
For some reason i thought you could copy/paste entire lines (which might be a handy feature, but is technically complicated if not impossible to implement as you said), but i guess in the past i just copy/pasted info from one field to another instead of doing entire lines.

I'll close the FR then !
