### ISSUE TITLE
Actions: SWS/S&M: Dump action list (all but custom actions) and SWS/S&M: Dump action list (custom actions only)

### ISSUE THREAD

**Issue by Buy-One** [reaper-oss/sws#1357]
Both actions create a dump of the entire action list due to having the same command ID as the action SWS/S&M: Dump action list (all actions) namely _S&M_DUMP_CUST_ACTION_LIST.

When copying their names what gets copied is the name of the action  SWS/S&M: Dump action list (all actions).

Need their own command IDs

**Comment by cfillion** [comment]
Looks like it's been that way since these two actions were added in 2016... Fixing!

**Comment by Buy-One** [comment]
Thank you
