### ISSUE TITLE
Bug: NF_TakeFX_GetModuleName - docs only have two parameters, while Lua demands 4

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#1366]
In Lua NF_TakeFX_GetModuleName needs 4 parameters but the docs only have two

` boolean retval, string name = reaper.NF_TakeFX_GetModuleName(MediaItem item, integer fx)`

After some tests, it seems like the function expects as additional parameters:

` boolean retval, string name = reaper.NF_TakeFX_GetModuleName(MediaItem item, integer fx, string name, integer buf_sz)`

I'm not sure, if I got this right, so it's difficult to use the function properly...

**Comment by cfillion** [comment]
This was fixed in SWS 2.12 (and the function was renamed to `NF_TakeFX_GetFXModuleName`).
