### ISSUE TITLE
(nitpick) Item property interpolator shows wrong 'enabled' symbol

### ISSUE THREAD

**Issue by nofishonfriday** [reaper-oss/sws#1371]
https://forum.cockos.com/showthread.php?p=2275857#post2275857 (same here).

**Comment by nofishonfriday** [comment]
https://github.com/reaper-oss/sws/blob/master/Xenakios/PropertyInterpolator.cpp#L781

replacing with
ListView_SetItemText(GetDlgItem(g_hIIdlg, IDC_IIACTPARLIST), nm->iItem, 0, g_IIproperties[nm->iItem].enabled ? "\u2022" : "");

seems to work here for displaying the bullet, but not sure it's ok to do?

**Comment by cfillion** [comment]
The issue is caused by PropertyInterpolator using the ANSI Windows API functions (rather than the Wide functions) without enabling WDL's utf8 wrappers.
