### ISSUE TITLE
reaper.BR_GetMouseCursorContext() not working on TCP, MCP 

### ISSUE THREAD

**Issue by estrica2000** [reaper-oss/sws#1381]
At least for OSX catalina:
returns as result window: unknown and so no result for sections : Tracks and envelopes or empty
Except in MCP, Master track returns: window:mcp
segment:empty

**Comment by cfillion** [comment]
Update SWS: v2.10 doesn't support REAPER 6, only v2.11 and newer does.

https://www.sws-extension.org/download/pre-release/

**Comment by estrica2000** [comment]
thank you! yes yes! :)
