### ISSUE TITLE
reaper.BR_EnvSetProperties killing/ P_EXT for envelopes

### ISSUE THREAD

**Issue by estrica2000** [reaper-oss/sws#1385]
When setting a P_EXT for envelopes with reaper.GetSetEnvelopeInfo_String(Envelope, "P_EXT:example", "Some value", true)

and after use reaper.BR_EnvSetProperties , those P_EXT disappear. but if repeated they stay:
Check the gif: https://imgur.com/pJVn4AZ

Using  this lua : 
--====================================================================
function msg(param)
     reaper.ShowConsoleMsg("\n"..tostring(param));
end

Envelope = reaper.GetSelectedEnvelope(0)
--====================================================================
if Envelope == nil then msg ("Select an envelope") return false end
--====================================================================

reaper.GetSetEnvelopeInfo_String(Envelope, "P_EXT:example", "Some value", true)

retval, value = reaper.GetSetEnvelopeInfo_String(Envelope, "P_EXT:example", "", false)
msg ("P_EXT:example holds value:"..value)

local br_env = reaper.BR_EnvAlloc(Envelope, false )   
    reaper.BR_EnvSetProperties( 
      br_env, 
      true,
      true, 
      true, 
      true, 
      10, 
      0, 
      true
   )   
   --====================================================================
reaper.BR_EnvFree( br_env, true )
-- after using reaper.BR_EnvAlloc the value disappears but only on the first run on that envelope
retval, value = reaper.GetSetEnvelopeInfo_String(Envelope, "P_EXT:example", "", false)
msg ("P_EXT:example holds value:"..value)

**Comment by nofishonfriday** [comment]
Thanks for the test script, confirmed.

**Comment by estrica2000** [comment]
Thank you nofish for the commit! i have no idea where to get the new SWS version with this fix, so i can test it. Could anyone tell me?

**Comment by nofishonfriday** [comment]
If you're on Win/Linux, build for testing are here:
https://github.com/reaper-oss/sws/pull/1387#issuecomment-648542578

**Comment by estrica2000** [comment]
Thank you ! unfortunetly not: OSX ! i guess i'll have to wait! any chance to know how often and where i should look for in the future?

**Comment by nofishonfriday** [comment]
@estrica2000 
Took longer than expected that I can do Mac builds again (had to upgrade system),
but if you're still interested, here's a Mac version with the potential fix:
https://www.dropbox.com/s/lf8y6pqlfkx4bp0/reaper_sws-x86_64.dylib?dl=1

(If you test let me know how it goes. :))
