### ISSUE TITLE
Regression: double-config-variable "uiscale" is not returned anymore properly

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#1390]
I just noticed, that SWS doesn't return all config-variables anymore properly.

For instance, the config-variable uiscale do not return correct values. As it's double, I suspect, that there's a bug introduced in SWS_GetDoubleConfigVar.

uiscale should change between 2.6483502156774e-314 and  -1.#QNAN when clicking a MediaItem
and between 5.2635442471209e-315 and -1.#QNAN when clicking within track-envelopes,

This broke numerous functions in my Ultraschall-API...

Tested on Windows 7, Reaper 6.11x64 and both SWS 2.10.0(where it worked) and 2.11.0(where it didn't).

I will look into it, if I can find other variables not working anymore.

**Comment by cfillion** [comment]
It's a 32-bit value, so `SNM_GetIntConfigVar` should be used instead. SWS_GetDoubleConfigVar reads 64-bit so in 2.10 it's reading out of bounds.

The value of `uiscale` never seems to change here no matter where I click though...

**Comment by cfillion** [comment]
Here's a list of all the configvars listed in your documentation sorted and grouped by their location in memory along with their reported sizes: https://gist.github.com/cfillion/b1b68ef67636fd121878c91203d170c2/raw/f59fca278481132facd0f8e5e025c466ba35ef66/configvars_layout.txt. The list is split into global and project variables.

**Comment by mespotine** [comment]
Hmm, that's weird. I made a LiceCap  on Windows, which shows, that it actually works on Windows. And only as double, not as integer.

![uiscale](https://user-images.githubusercontent.com/4251851/86604081-3355ee00-bfa5-11ea-9c00-7a8fc3144b59.gif)

I'm pretty sure that I successfully tested it on Mac and Linux too back then, when I made use of this "feature" but haven't tested it again recently.
I wonder, if that had something to do with a fix in the SNM_GetDoubleConfigVar-function, as I had reported a bug in it some time ago which lead to potential crashes. Maybe this fix also influenced this behavior. I also think, that Reaper added some parts of "clickstate" into the 64bit-value but not as configvar, but rather "by accident"(for lack of a better term).

Anyway, if there's nothing you can do about it, I may better see into a feature-request then to get the clickstates.

**Comment by mespotine** [comment]
Oh, and regarding some of the invalid config-vars: Some of them, like afxcfg, are only accessible, after they've been set in the UI of Reaper once.
afxcfg is for cfg applying fx for glue and such things. Before setting that, you can't access it.

I think, this goes for some of the other invalid ones too...

**Comment by cfillion** [comment]
> I wonder, if that had something to do with a fix in the SNM_GetDoubleConfigVar-function, as I had reported a bug in it some time ago which lead to potential crashes.

Yes, that's the source of the fix. Before 2.11, SWS did not care if it was reading (or worse: writing!) memory outside of a config var. That behavior was highly unsafe. So the new code ensures that it can only read/write the correct amount of bytes.

Any script that relies on some interesting bit of internal data to be next to a configvar's value is unreliable to begin with.

- 32-bit configvars can now only be accessed with `SNM_{Get,Set}IntConfigVar`
- 64-bit configvars by `SNM_{Get,Set}DoubleConfigVar` and the upcoming `SNM_{Get,Set}LongConfigVar`
- 1-byte configvars (such as `projsmpterateuseproj`) can no longer be accessed, so I'll add `SNM_{Get,Set}CharConfigVar` for those
- Array configvars (such as `video_decprio`) and pointers (guessing `g_config_project` is one) are not supported.

**Comment by mespotine** [comment]
I think it would be better to include them to the currently existing functions, just to keep scripts relying on that working.

BTW: some configvars are also available as strings, using get_config_var_string. Any chance for adding writing support for them as well?
It's just a handful that are accessible with that, but some look quite handy to have, if one wants to dynamically change default-paths:

default paths:
altpeaksopathlist
altpeakspath
defrenderpath
defsavepath
mididefcolormap

recfile_wildcards - wildcards for new recording-files
video_decprio - decoder-priority for video-formats

Probably useless, as there are other means to get them:
g_config_project - (a string of the filename but only accessible with GetIntConfigVar)
lastthemefn5

**Comment by cfillion** [comment]
> I think it would be better to include them to the currently existing functions, just to keep scripts relying on that working.

Yeah, the more I think about the more it makes sense to abstract away the underlying size of the data type in the existing Int/Double functions rather than adding one function for each type. On the matter of compatibility though, 1-byte ints and 32-bit floats configvars never worked properly in SWS. For instance, `uiscale` is supposed to read as `1.0`.

I'll look at whether writing string vars is safe and what's up with the other "invalid" vars like afxcfg later.
