### ISSUE TITLE
Notes window on Mac

### ISSUE THREAD

**Issue by garygiles63** [reaper-oss/sws#1393]
HI

Having an issue with the number of characters Notes S&M will show on a Mac, on a PC its fine.  Also in item setting/Item Notes, it also show all the characters typed. Is this a settings issue or is this a bug?

Look forward to your reply.

Regards
Gary

**Comment by mespotine** [comment]
What kind of issue do you actually have with the number of characters? What happens exactly compared to PC?

Best way is probably adding a LiceCap/screenrecording, which shows, what you mean.

**Comment by cfillion** [comment]
This was fixed in SWS 2.12. You can get it from https://www.sws-extension.org/download/pre-release/.
