### ISSUE TITLE
Pre-release 2.13.0.0 breaks script that used to work with 2.10.0.0 (zooming actions)

### ISSUE THREAD

**Issue by Breeder** [reaper-oss/sws#1395]
This is the script, it's called 'Zoom - Toggle full zoom to selected items, automation items and selected points in active envelope (time selection or full project if no selection)'

https://pastebin.com/JuX1baXA

When zooming to items, something gets wrong with scroll position. The script is using SWS actions to zoom selected tracks. I tried removing obvious things like PreventUIRefresh() but still no luck.

**Comment by Breeder** [comment]
I know there were some fixes to zooming code when it comes to envelopes recently (this script fixes this internally because it was written before these fixes were released in SWS) so maybe that's where the bug happened? I think cfillion did these envelope fixes? Maybe he can get to the bottom of this? I mean, the script is simple, it simply saves track selection, selects new tracks, zooms to them and then restores track selection. 

The horizontal zoom part of the script works, it's the vertical zooming that seems to be affected by the recent changes (lines 388 to 454 of the script from the first post of this issue)

**Comment by cfillion** [comment]
Can you share duplication steps and details on the scroll position you're getting now vs before? At first glance that script appears to be working here with SWS 2.12.0 in REAPER 6.12 on macOS&Windows: https://i.imgur.com/KGlfu6X.gif.

**Comment by Breeder** [comment]
Ah, it has something to do with cycle actions!!!!

I use cycle action to wrap this script, this is the cycle action:
https://stash.reaper.fm/39948/Screenshot%202020-07-09%2013.35.21.png

Can you try with this project (item and track selection are different at purpose)
https://stash.reaper.fm/39947/test.rpp

2.10. result:
https://stash.reaper.fm/39949/Screenshot%202020-07-09%2013.32.54.png
2.13 result:
https://stash.reaper.fm/39950/Screenshot%202020-07-09%2013.38.08.png

**Comment by cfillion** [comment]
Confirmed, this happens when "SWS: Toggle zoom to selected tracks and time selection" is used while PreventUIRefresh is active. Looking into why that is...

```lua
reaper.PreventUIRefresh(1)
reaper.Main_OnCommand(reaper.NamedCommandLookup('_SWS_TOGZOOMTT'), 0)
reaper.PreventUIRefresh(-1)
```
