### ISSUE TITLE
Increasing the number of slots for shortcuts to plugins

### ISSUE THREAD

**Issue by Emelowsky** [reaper-oss/sws#1399]
I would like to increase the number of free slots because now their number is 100. 
It is not enough, but it causes the attempt to add a shortcut for plug 101 to end with the following message: "All FX shortcut arę in use.  Please delete a shortcut in order to ad a new one. "  

When you use a MIDI controller to run plug-ins, where any effect can be triggered directly from it, it becomes irritating.  
Can you ask to increase the number of slots to at least 300?  - for future safety :) 

I searched the files a bit and found that it was a file called "reaper-fxoptions.ini".  
Maybe it can be somehow increased without the need to update?  
I would be very grateful!

Thank you in advance! :)

**Comment by nofishonfriday** [comment]
This is about functionality provided by Reaper natively, not by SWS, so SWS can do nothing about it.

**Comment by nofishonfriday** [comment]
This is about functionality provided by Reaper natively so SWS can do nothing about it., sorry.
There's already an existing feature request you could bump:
https://forum.cockos.com/showthread.php?t=232919
