### ISSUE TITLE
Intall issue - Destination folder; 'next' greyed out

### ISSUE THREAD

**Issue by t0mniscient** [reaper-oss/sws#1402]
I'm running Windows 10. I'll run the .exe file and start the setup wizard. I'll click 'I agree', to which it takes me to the next display, which is titled: "SWS Extension x64 Setup: Installation Folder".

I then (logically) click the 'Browse...' button, to which another window pops up ('Browse For Folder'). No matter which folder I choose, or where I select, the 'OK' button is always greyed out. Subsequently, the 'Next' button on the window prior is greyed out. I'm stuck here. I've downloaded both the 32 as well as 64 bit versions and I get the same issue. I've also downloaded them in different browsers and that doesn't make a difference either. Help?
![reaper-issue](https://user-images.githubusercontent.com/69225147/89359893-e3963f80-d694-11ea-8166-f853dc492111.png)

**Comment by cfillion** [comment]
Select the folder where REAPER (reaper.exe) is installed.
