### ISSUE TITLE
FEATURE Request : SWS track notes need to be duplicated with their tracks (or maybe simply as an option)

### ISSUE THREAD

**Issue by lowlou** [reaper-oss/sws#1415]
Hello :).

I would need to have a way to duplicate tracks with their notes. The Reaper classic "duplicate tracks" action doesn't duplicate the notes, and it would be super important for me to have notes duplicated, because I use notes to trigger certain functions via a script. To be honest that's a bummer :(. Notes have the potential not only to write lyrics, or mix critics, but also be used as conditions inside scripts.

Now I understand that for everyday use, you might not want notes to be duplicated with tracks, but maybe we could have an option ? Or maybe you could come up with a new SWS action that duplicate selected tracks also with their notes ? 

I would deeply appreciate if you'd consider this feature request :). Thank you very much !
xxxxxxxxxxxxxxxxxxxxx
Louis

**Comment by cfillion** [comment]
SWS notes are not duplicated because they are stored separately from the tracks in the project. Since v5.975 REAPER has a way for extensions and scripts to store per-track data that would make this cleanly possible. However switching to using it would require quite the overhaul...

Here's a script that duplicates tracks preserving SWS notes:

```lua
local notes = {}
for i = 0, reaper.CountSelectedTracks(nil) - 1 do
  local track = reaper.GetSelectedTrack(nil, i)
  table.insert(notes, reaper.NF_GetSWSTrackNotes(track))
end

reaper.Main_OnCommand(40062, 0) -- Track: Duplicate tracks

for i = 0, reaper.CountSelectedTracks(nil) - 1 do
  local track = reaper.GetSelectedTrack(nil, i)
  reaper.NF_SetSWSTrackNotes(track, notes[i + 1])
end
```

**Comment by lowlou** [comment]
Oh man... I don't know what to say at this point... You're amazing <3... I really needed this :). Thank you so so much Cfillion :) !!!

**Comment by lowlou** [comment]
Cfillion came up with a script in LESS THAN 12 MINUTES PEOPLE !!!!!!!!!!

**Comment by lowlou** [comment]
L.E.G.E.N.D 🥇 
xxxxxxxxxxxxxx
