### ISSUE TITLE
CF_GetTakeFXChain doesn't return hwnd for docked FXChain - Bug or Docs-issue

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#1416]
CF_GetTakeFXChain seems to return the HWND only for FXChain-windows, who aren't docked. 
If that's the only way to handle it, I suggest to add a small explanation to the docs to clear up possible confusion.

**Comment by cfillion** [comment]
Which version of SWS? Support for docked FX chains was added in v2.12.

There are additional fixes (unrelated to the dock) to that function queued for the next update (dev builds at https://github.com/reaper-oss/sws/pull/1396#issuecomment-656342588).

**Comment by mespotine** [comment]
Ok, I'm not on the 2.12-prereleases yet, so if it's already done, I think I can close the issue.

Thanx for the heads up :)
