### ISSUE TITLE
Bug-reaper.BR_GetMouseCursorContext()

### ISSUE THREAD

**Issue by ArchieScript** [reaper-oss/sws#1420]
The "reaper.BR_GetMouseCursorContext()" function in a deferred script breaks the tooltip in the MIDI editor
https://avatars.mds.yandex.net/get-pdb/2839338/14c6c548-5478-4603-b380-8af584d1306a/orig

**Comment by cfillion** [comment]
The root cause comes from REAPER itself: reading the item state chunk somehow affects the MIDI Editor tooltips.

```lua
function t()
  local me = reaper.MIDIEditor_GetActive()
  local tk = reaper.MIDIEditor_GetTake(me)
  local it = reaper.GetMediaItemTake_Item(tk)
  reaper.GetItemStateChunk(it, '', false)

  reaper.defer(t)
end

t()
```

However while debugging this I also found an unrelated bug that does memory corruption when using `BR_GetMouseCursorContext` over the piano roll keyboard, so thanks!
