### ISSUE TITLE
Past a certain size, S&M_Cyclactions.ini doesn't seem to register latest action IDs.

### ISSUE THREAD

**Issue by lowlou** [reaper-oss/sws#1436]
Hello 

Is there a ceiling over which you can't create new cycle action ? I have currently 632 cycle action, after importing a set of 160 actions, and only some of these new actions are registered in the action list. In the Cycle action editor, I can't "run" these action, the right click run - function is greyed up. Is there any way to make this work ? I'm not even done with my setup, I'd need to create new actions on top of the 630 actions :/ ...

**Comment by cfillion** [comment]
Is the ID inside parenthesis? This would indicate registration failed or they were not registered. Try modifying those actions and applying, in case there are validation errors.

(There is a [global limit](https://forum.cockos.com/showthread.php?t=243459) on how many actions (extension actions/custom actions/scripts) can be registered in REAPER in total, but I doubt you're hitting that...)

**Comment by lowlou** [comment]
Oh yes ok you are right Cfillion, some are into parenthesis. What is weird is that some are validated when others are not , when they are all essentially small variation of the same action. The only thing that varies is two actions : S&M_PASTE_TRACKFXCHAIN that goes from slot 40 to slot 204 and a SWS Console track renaming via "n" instruction : the name is different for each action. 

Here is a picture : 

[URL=https://www.casimages.com/i/201031092221921568.png.html][IMG]https://nsa40.casimages.com/img/2020/10/31/mini_201031092221921568.png[/IMG][/url]

I don't understand why some of these actions are working, and others not. 

The SWS.ini is enabling 255 fx chains. The FX chains are correctly stored in the Reaper FX chain folder.

The S&M_Cyclaction.ini seems fine too... 

Any idea what could cause this ?

**Comment by cfillion** [comment]
What is the validation error message?

**Comment by lowlou** [comment]
The validation message error is truncated sadly : https://www.casimages.com/i/201031093641326285.png.html

I can't explode all these actions or they are too long and Reaper crashes when I apply changes (I notice that above 300ish lines, Reaper can crash when applying changes). 

Ok and after a few tests, I notice that any cycle action I create now has its ID inside parenthesis :( ...

**Comment by lowlou** [comment]
Here is my S&M_Cyclaction.ini 

https://gofile.io/d/j1HKr7

**Comment by lowlou** [comment]
I must have crossed a threslhold, becasue I can't create any new Cycle action, and, well, that sucks :(.

**Comment by lowlou** [comment]
Could it be that my S&M_Cyclaction.ini is around 1 MO ?

**Comment by lowlou** [comment]
Ok Christian, I'll switch to french quickly : merci d'avoir regardé. J'ai bien l'impression que j'ai atteint une limite de Reaper, ou bien des SWS, parce que mes actions ont pas d'erreurs, elle sont refusées parce que "apply change" échoue à tout calculer (depuis quelques temps ça prend des plombes, au moins 1 minutes de par le nombre d'action et leur longueur)... C'est un peu la cata si c'est le cas parce que ma config est pas finie du tout, et là ça me stoppe complètement. 

Je sais pas si t'es affilié avec la SWS team, mais ça vaudrait le coup de régler le problème du message de validation tronqué lorsque trop long

ENGLISH : I think SWS cycle action editor fails to "apply changes" when there is too much to calculate. It takes a long time to process and results in the latest actions IDs being ignored.

**Comment by lowlou** [comment]
Guys I'm just blocked here, I can't configure Reaper anymore with the extension tools... Can anybody from SWS/S&M investigate on this issue ? 

_Past a certain size, the S&M_Cyclactions.ini doesn't seem to register latest action IDs._

**Comment by nofishonfriday** [comment]
Hi,

although I understand it's blocking your work, try to be a little patient please. :)
It's only a few developers working on SWS currently and doing it all in their spare time.
Looks like cfillion is already on it.

**Comment by lowlou** [comment]
I totally get it, I'm absolutely sorry and don't want to push anybody, and it's sunday, I just have trouble to get my ideas come thru in english, this is why I post several messages (plus the fact that I encounter several linked problems). I know SWS/S&M people are not paid and so I try to manage my expectations too. Please be sure I appreciate SWS team work, and I support them as much as I can now and going forward.

**Comment by cfillion** [comment]
Can you try again with the builds from https://github.com/reaper-oss/sws/pull/1440#issuecomment-720185850? It should display all validation errors.

**Comment by lowlou** [comment]
Ok I'll try Right now, please give me a few minutes :). Thanks for your help so far !

**Comment by lowlou** [comment]
Cfillion, I've installed the build and I've "apply change" again. This time I have the full error log, it's not truncated anymore :) ! It only mentions action that could be improved with explodes. No mention of other more serious errors. Still, I have the same result as before : the last action IDs, from around 500 to 600 are all into parenthesis. I'm pretty sure they have no mistakes in them because other actions _exactly like them_ are registered fine.

**Comment by cfillion** [comment]
Interesting. Could you send me your S&M.ini and reaper-kb.ini? (So I can see how many actions SWS registers + how many custom actions and scripts there are. REAPER has a global limit on actions.)

**Comment by lowlou** [comment]
Here it is : 

https://gofile.io/d/wkkuik

**Comment by lowlou** [comment]
With your file, I have the same result, and my startup action is not acting as usual, it does something else, but it might not be related, I don't know.

**Comment by lowlou** [comment]
Oh ok I see, you tried with empty actions replacing the original actions... No luck :(... I don't know what's happening...

**Comment by lowlou** [comment]
Here is my reaper.ini, of it can be of any use : 

https://gofile.io/d/I6Kj5S

**Comment by lowlou** [comment]
Ok I've tried to find a solution to this, and it seems that the problem is caused by the max number of actions/custom/cycle/scripts you were talking about at the begining. I cleaned some custom actions I don't use anymore and I manage to get some of the previously non-registered actions registered. This number of action limit, maybe it could be interesting to increase it, but I guess that's something that has to be delt with within Reaper, not necessarily SWS :/ ...

**Comment by lowlou** [comment]
Just an idea : what could be quite useful is to have a way to know how many action/custom/cycle/script slot one has left before hitting the ceiling... Maybe something that could find its way into a SWS update ? :)

**Comment by lowlou** [comment]
I see you don't respond, and this is no problem. Thank you for your help (really), and I hope you have a good week :).

**Comment by cfillion** [comment]
I don't think it's possible to accurately predict how many possible actions are remaining. I'll add an error message when a cycle action fails to be registered.
