### ISSUE TITLE
Global notes broken (contains garbage)

### ISSUE THREAD

**Issue by Sam13** [reaper-oss/sws#1450]
Depending the text the global notes seem to be broken.
To reproduce:
- Start Reaper
- Change global notes to following text:
[text-breaks-global-notes.txt](https://github.com/reaper-oss/sws/files/5505954/text-breaks-global-notes.txt)

- Save project
- Start Reaper again
- Global notes do not contain the text entered before
- Examine _%AppData%\Roaming\REAPER\SWS_Global notes.txt_ -> Contains garbage
![image](https://user-images.githubusercontent.com/2196081/98459463-4408b180-219b-11eb-9e3a-af482566e73c.png)
[SWS_Global notes.txt](https://github.com/reaper-oss/sws/files/5505955/SWS_Global.notes.txt)

Reaper v6.15/x64, SWS 2.10.0, Windows 10

**Comment by cfillion** [comment]
This was fixed in v2.12.0.
