### ISSUE TITLE
Buggy UI of the Cycle action editor when dragging actions up or down

### ISSUE THREAD

**Issue by lowlou** [reaper-oss/sws#1456]
If a cycle action has lots of actions in it (meaning that you can't see all of them all at once on your screen, and you have to use the scrollbar) the action of selecting an action and dragging up or down to re-position it creates a lot of flickers/unexpected user interface bug. It makes the drag and drop virtually impossible to use with long cycle action :one has to rely on cut and paste instead. No big deal, as there is this solution, but I guess a bug report won't hurt. Note that if the cycle aciton is short and you get to see all its action on the cycle action editor window, there is no bug at all.

Latest Reaper official release, Windows 10 up to date, latest SWS.

Thanks & have a nice day.

**Comment by cfillion** [comment]
Confirmed. This also affects region playlists and autocolor.
