### ISSUE TITLE
Major issue with SWS playlist and tempo changes

### ISSUE THREAD

**Issue by ayskura** [reaper-oss/sws#1462]
I just discovered the Playlist in SWS and I love it. I can rearrange regions etc and make structures quickly... only problem I am having is: When I make an arrangement I like in playlist and then I click the EDIT PROJECT button and I create a new arrange (either in new tab or overwrite the current one) the regions get reordered as from the playlist BUT all the tempo changes aren't moved with the region. Actually all the tempo changes get deleted and there is a common tempo for all region which isn't correct! Am I doing something wrong here?

thank you 

PS 
another issue: if I have the tracks grouped the region does't cut them within the border but copy the full lenght of the audio file creating overlaps and a general mess. It took me a while to figure out I had to ungroup tracks to make it work. Still tempo changes aren't copied though

**Comment by cfillion** [comment]
Confirmed, tempo changes are not handled at all currently.

> nother issue: if I have the tracks grouped the region does't cut them within the border but copy the full lenght of the audio file creating overlaps and a general mess.

This was fixed in [v2.11](https://www.sws-extension.org/download/pre-release). #1118

**Comment by ayskura** [comment]
ok just found another issue:in the original track I had a routing of FXs in send and when I EDIT PROJECT and create a new one all the sends are gone and there are no FXs in the new song. The FXs track where not copied. It might be because they were hidden from the TCP but visibe in the Mixer?

**Comment by johngeorgewright** [comment]
> This was fixed in v2.11. #1118

Both editing in place and in to a new tab are still effected in v2.12.1.
