### ISSUE TITLE
"Float previous/next FX" actions does not cycle if the last/first FX is offline

### ISSUE THREAD

**Issue by cfillion** [reaper-oss/sws#1474]
Reported by USR on the forum: https://forum.cockos.com/showpost.php?p=2360077

> Hi, I noticed that the following two actions seem to have a little bug. I use sws-2.12.1.0-Darwin-x86_64-4ae1b75b and REAPER v6.15 in Mac OS 10.11.6, but the bug seems to have been there for a while.
> 
> _S&M_WNONLY1 / SWS/S&M: Float previous FX (and close others) for selected tracks
> _S&M_WNONLY2 / SWS/S&M: Float next FX (and close others) for selected tracks
> 
> _S&M_WNONLY1 gets stuck at the last slot of the FX chain if the FX is offline, whereas it’s supposed to skip the offline FX and float the second last one. _S&M_WNONLY2 behaves the same way when the FX in the first slot of the chain is offline.

**Comment by nofishonfriday** [comment]
I've been looking into this a couple of days ago and could confirm.
Unfortunately I din't understand the relevant code enough to fix.
(The [fix](https://github.com/reaper-oss/sws/blob/0c9955904b83bf5eb88350583aceaf44badf3a8c/SnM/SnM_Window.cpp#L901) I added sometime ago for offline FX seems to work for offline FX 'in-between' online ones but not in the specific case here).
