### ISSUE TITLE
"Xenakios/SWS: Choose new source file for selected takes" doesn't recall last path

### ISSUE THREAD

**Issue by babag1** [reaper-oss/sws#1483]
been using this action lately and finding it doesn't remember the last path used. for me, that results in a LOT of extra clicks as it always starts with the home directory and my files are quite far from there. would be very helpful if it came back to the previously used path when it is run again. 

thanks,
babag

**Comment by jeremybernstein** [comment]
This appears to be a Windows-only issue, macOS does this automatically. Investigating.

**Comment by nofishonfriday** [comment]
Working fine here too (Win10), so closing this due to no feedback from OP.
