### ISSUE TITLE
request : more toolbars

### ISSUE THREAD

**Issue by lowlou** [reaper-oss/sws#1484]
Hello ! 

So this is a pretty big request, and I don't know if it"s feasable, but here we are. I (and others before me) have asked in the Reaper forum for more toolbars, 16 being a limiting factor for some people, but there is no sign of any new toolbars being implemented natively in Reaper. 

Question is : could it be something that SWS could provide via the extension ? 

If so consider this message a new feature request :p !!!

xxxxxxx
louis

**Comment by nofishonfriday** [comment]
Sorry to say, but I'm rather sure it's on REAPER side to implement this and SWS can do nothing about it, so I'm closing this.
(@cfillion if you think otherwise feel free to reopen.)

**Comment by lowlou** [comment]
ok thx :)
