### ISSUE TITLE
envelope contextual toolbar opens where there is no envelope 

### ISSUE THREAD

**Issue by mccrabney** [reaper-oss/sws#1488]
thanks for your software!

i have had unpredictable behavior with contextual toolbars for a while, and finally found out why.

if you have AI in the media lane with background envelope disabled, and if you -

1 - move mouse cursor vertically over an empty track area while triggering "SWS/BR: Exclusive toggle contextual toolbar under mouse cursor, preset [n]"

2 - you will see that the "envelope" context gets triggered at the position where the last envelope point existed, even though there is no envelope context under mouse cursor.

see this. you can tell the "envelope" toolbar by the "move on/move off" text, and the "arrange" toolbar by the grid options.

https://i.imgur.com/zhsOaU9.gif

**Comment by nofishonfriday** [comment]
confirmed here.
