### ISSUE TITLE
Building failure on a Raspberry Pi

### ISSUE THREAD

**Issue by tglanfield** [reaper-oss/sws#1490]
Following the instructions at: https://linuxmusicians.com/viewtopic.php?t=20783

SWS_VERSION 2,12,1,2
cc (Raspbian 8.3.0-6+rpi1) 8.3.0
Linux mixer 4.19.71-rt24-v7l #3 SMP PREEMPT RT Tue Dec 17 17:24:54 GMT 2019 armv7l GNU/Linux

In file included from /home/terry/Development/sws-build/WDL/WDL/jnetlib/../heapbuf.h:45,
                 from /home/terry/Development/sws-build/WDL/WDL/jnetlib/connection.h:61,
                 from /home/terry/Development/sws-build/WDL/WDL/jnetlib/httpget.h:46,
                 from /home/terry/Development/sws-build/WDL/WDL/jnetlib/httpget.cpp:12:
/home/terry/Development/sws-build/WDL/WDL/jnetlib/../wdltypes.h:195:69: error: size of array ‘wdl_assert_failed_unsigned_char’ is negative
 typedef char wdl_assert_failed_unsigned_char[((char)-1) > 0 ? -1 : 1];

**Comment by cfillion** [comment]
Your WDL is newer than the one provided in this repository as a submodule. The correct build instructions are at https://github.com/reaper-oss/sws/wiki/Building-the-SWS-Extension.

**Comment by tglanfield** [comment]
Thanks Christian.
