### ISSUE TITLE
Groove files ordering messed up (on Linux)

### ISSUE THREAD

**Issue by elcalenx** [reaper-oss/sws#1494]
When I open the Groove Tool, the list of grooves is in apparently random order. I would expect it's meant to be alphabetical... This obviously makes it somewhat annoying to use. I tried searching the issue tracker and Reaper forums, but couldn't find much, apart from a brief mention that someone else had the same issue...

I'm on Linux (64-bit Debian testing), with SWS v2.12.1.2, and a recent dev build of Reaper (although this problem has persisted for some time).

![Screenshot from 2021-01-09 16-37-21](https://user-images.githubusercontent.com/45395376/104094323-fdb5f880-5298-11eb-80fd-07ffdc1a3ff4.png)

**Comment by cfillion** [comment]
WDL/SWELL does not currently implement the `LBS_SORT` style that the Groove tool window relies upon on Linux. I've submitted a [patch](https://github.com/cfillion/WDL/commit/e7d0267879a2b0a202547a3a1cf23b477af4a82f).
