### ISSUE TITLE
Bug: "Xenakios/SWS: Rename takes and source files..." deletes file with the same name on MAC.

### ISSUE THREAD

**Issue by AZpercussion** [reaper-oss/sws#1498]
I had need to rename manually several items.
But by accident I named one take the same as the another. And the old source file has been deleted.
It works normally on PC. Just renames take, but not source.
On MAC it deletes file!!

**Comment by nofishonfriday** [comment]
This should (hopefuly) be fixed already for next (pre-)release: https://github.com/reaper-oss/sws/pull/1492

**Comment by AZpercussion** [comment]
It warns when filename already exists, thats good update. But on mac that's still potentially dangerous function. Because it still deletes already named files with the same name.
By the way, the button Yes is in focus on prompt, that is more dangerouse.
