### ISSUE TITLE
Bug: "SWS/BR: Move active floating track FX window to mouse cursor" don't work on master track.

### ISSUE THREAD

**Issue by mikekravets** [reaper-oss/sws#1499]
Hi ! I have two screens, and found this script very useful. But it don't work with master track. Can you help with solution ?
Here is video example.
https://drive.google.com/file/d/1EusdwhmTWqS27cl6eA8bfaWvedikNTvP/view?usp=sharing
(Probably some other scripts also have strange behavior with MT, but can not remind them now)

**Comment by cfillion** [comment]
I'm not sure whether this is a bug. The action name states it only moves windows of *track FX*. The master track is special, so it can be argued that the action is working as intended...

The general version of the action, "SWS/BR: Move active floating window to mouse cursor", should work with floating master track FXs.

**Comment by mikekravets** [comment]
@cfillion So if you can not reproduce it - problem is on my side .. this script is great, because Reaper has no option to choose where to open new added FX by default, second screen is only for analyzer. Didn't found solution on reapers forum, maybe you can advice something ?)

**Comment by cfillion** [comment]
I can reproduce it, I meant that I believe this is the expected behavior of the "track FX" action. It doesn't consider master, monitoring and take FX as "track FX". You can instead use the similarly named action (without "track FX") to move that master FX window to the correct monitor.

**Comment by mikekravets** [comment]
Understood, found it, works, thank you so much, Regards !)
