### ISSUE TITLE
Update Version Build Date in Splash About Window

### ISSUE THREAD

**Issue by WHAMMBO** [reaper-oss/sws#1503]
![Capture](https://user-images.githubusercontent.com/50641110/107120383-63c37a80-685b-11eb-822b-58197dc808e2.JPG)

**Comment by cfillion** [comment]
v2.10.0 really dates back from 2 years ago. The latest updates are available at https://www.sws-extension.org/download/pre-release/ (latest from 2020-12-27).

We're expecting a new stable release to be posted to the homepage very soon though, stay tuned!

**Comment by WHAMMBO** [comment]
That splash screen is from the version of SWS I downloaded just recently from your site.

Did you really mean to not have a current date on your build? It should say '2020-12-27' shouldn't it?

Eric B.

**Comment by cfillion** [comment]
The version on the main website is currently v2.10.0 from 2 years ago.
