### ISSUE TITLE
Bug: Region Playlist Edit button shows column view toggles

### ISSUE THREAD

**Issue by reaperblog** [reaper-oss/sws#1506]
v2.12.13
Clicking the Edit Project button in Region Playlist window shows the visible columns context. Also right-clicking nearly anywhere in the window shows this context.

Expected - only seeing this context when right-clicking column header

![image](https://user-images.githubusercontent.com/19919860/107276339-b17ce600-6a07-11eb-9057-1a8dd4c50659.png)

**Comment by cfillion** [comment]
Ah, oops. Looks like this bug has been in the Windows pre-release builds since May. Fixing!
