### ISSUE TITLE
'BR_GetMouseCursorContext' broken in latest official release (v2.12.1 #3)

### ISSUE THREAD

**Issue by amagalma** [reaper-oss/sws#1509]
When I run eel scripts that used to work before updating, I now get the message:
'BR_GetMouseCursorContext': expected 3 arguments maximum

**Comment by cfillion** [comment]
Do you have a minimal code example that works in 2.10 but not in 2.12?

**Comment by amagalma** [comment]
I have an old personal script. I just deleted the fourth argument and now it works.. Did the API used to take four arguments in the past? Anyway.. we can close this issue.. Thanks! :)

**Comment by cfillion** [comment]
Before 2015 it accidentally had an extra `int` argument.
