### ISSUE TITLE
"SWS/S&M Remove all envelopes for selected tracks" incremental behavior

### ISSUE THREAD

**Issue by Buy-One** [reaper-oss/sws#1511]
The action deletes track envelopes but instead of doing it in one go it does so in increments, with every run halving their number to the extent their number permits. Doesn't matter whether the envelopes are shown or hidden, sit in their own lanes or in media lane. Don't know if this was the intent, but if it was the title of the action doesn't reflect it.

![SWS-S M Remove all envelopes for selected tracks](https://user-images.githubusercontent.com/61803004/107860914-e1cee500-6e4a-11eb-8f0a-9611ad876ee7.gif)

**Comment by nofishonfriday** [comment]
Are you running the recently (officially) released SWS v2.12.1.3 ?
(That bug looks familiar from an older SWS version but should be fixed in the current one.)

**Comment by Buy-One** [comment]
Yes, it's fixed in the latest release. Sorry about trouble.
