### ISSUE TITLE
region playlist nested markers and regions

### ISSUE THREAD

**Issue by mozart999uk** [reaper-oss/sws#1512]
Not sure if this is a bug or feature ....

I have various regions defined with markers within them.  

![Regions and markers](https://user-images.githubusercontent.com/70143874/108040354-1c947100-7035-11eb-8122-27bd7cb2821e.png)

When I add the regions to the playlist I get this  warning

![Playlist warning](https://user-images.githubusercontent.com/70143874/108040297-0b4b6480-7035-11eb-80e7-dd608b9942be.png)

I use markers a lot in my project and would rather not have to delete them in order to use the region playlist.  Is there a way round this?

The regions also don't play properly.  Often playing until the reach the first marker then moving on to the next region

**Comment by mozart999uk** [comment]
Anyone had a chance to look at this?

**Comment by MauricDaniel** [comment]
it would help to at least remove the dialog.

**Comment by mozart999uk** [comment]
Not sure if this is being monitored or not.  Be great if the devs could confirm they've seen it :-)

**Comment by MauricDaniel** [comment]
Can someone at least just comment out the MessageBox that displays this message ?
I don't see what's the purpose of it anyway, and it requires a mouse click to continue, when it's obvious that if using playlist you are likely not holding a mouse in your hand.

**Comment by Szapi** [comment]
@mozart999uk When region playlist was made, there was no easy way to "schedule" regions to play automatically from code. It was kind of a hack to be honest. It only works if there are no markers inside the regions.

If my changes are approved by the SWS devs, it will be fixed :)

**Comment by mozart999uk** [comment]
> @mozart999uk When region playlist was made, there was no easy way to "schedule" regions to play automatically from code. It was kind of a hack to be honest. It only works if there are no markers inside the regions.
> 
> If my changes are approved by the SWS devs, it will be fixed :)

Great! Thanks :-)
