### ISSUE TITLE
Drag and drop user plugins for first-time download setup

### ISSUE THREAD

**Issue by JackHowa** [reaper-oss/sws#1516]
Is there an active pr or issue on debugging the user plugins flow for setup with Reaper? I am working on a workshop and was notified of this workaround. (I wouldn't have figured this out without this.) Let me know if 

1. Download reaper
2. Open reaper
3. Within reaper, search `show reaper resources`

![image](https://user-images.githubusercontent.com/5950956/109396984-f0f96c80-78f9-11eb-9e3d-9e62c5ede035.png)

4. Drag and drop installer into the user plugins folder of the actual reaper resources folder 

![image](https://user-images.githubusercontent.com/5950956/109397003-1ab29380-78fa-11eb-8e46-9250cac1de04.png)

5. See extensions sws folder as successful

**Comment by cfillion** [comment]
That is the correct way to install SWS on macOS.
