### ISSUE TITLE
OSX Big Sur 11.3beta1: Opening Cycle Action Editor crashes Reaper.

### ISSUE THREAD

**Issue by vanhaze2000** [reaper-oss/sws#1518]
- latest versions of Reaper and SWS.
- Opening Cycle Action Editor crashes Reaper immediately.

Snippet of Crash report:
Thread 0 Crashed:: reaper  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fff2029781d objc_msgSend + 29
1   com.apple.AppKit              	0x00007fff22fcd1a6 -[NSTableRowView _drawSeparatorInRect:withColor:] + 261
2   com.apple.AppKit              	0x00007fff237217f0 -[NSCachedTableRowView drawRect:] + 817
3   com.apple.AppKit              	0x00007fff22e4879b _NSViewDrawRect + 139
4   com.apple.AppKit              	0x00007fff23577e4e -[NSView _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 2115
5   com.apple.AppKit              	0x00007fff235781ec -[NSView _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 3041
6   com.apple.AppKit              	0x00007fff22e47db5 -[NSView(NSLayerKitGlue) _drawViewBackingLayer:inContext:drawingHandler:] + 967
7   com.apple.QuartzCore          	0x00007fff26c3f72d CABackingStoreUpdate_ + 190
8   com.apple.QuartzCore          	0x00007fff26ca4a1d invocation function for block in CA::Layer::display_() + 53
9   com.apple.QuartzCore          	0x00007fff26c3ec4b -[CALayer _display] + 2192
10  com.apple.AppKit              	0x00007fff22e47925 -[_NSBackingLayer display] + 475
11  com.apple.AppKit              	0x00007fff22db2bf4 -[_NSViewBackingLayer display] + 555
12  com.apple.QuartzCore          	0x00007fff26c3dc43 CA::Layer::display_if_needed(CA::Transaction*) + 813
13  com.apple.QuartzCore          	0x00007fff26d820eb CA::Context::commit_transaction(CA::Transaction*, double, double*) + 517
14  com.apple.QuartzCore          	0x00007fff26c1f7b7 CA::Transaction::commit() + 713
15  com.apple.AppKit              	0x00007fff22e5cc6c __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 285
16  com.apple.AppKit              	0x00007fff235afd47 ___NSRunLoopObserverCreateWithHandler_block_invoke + 41
17  com.apple.CoreFoundation      	0x00007fff204f1621 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
18  com.apple.CoreFoundation      	0x00007fff204f14b5 __CFRunLoopDoObservers + 543
19  com.apple.CoreFoundation      	0x00007fff204f0948 __CFRunLoopRun + 841
20  com.apple.CoreFoundation      	0x00007fff204eff2c CFRunLoopRunSpecific + 563
21  com.apple.HIToolbox           	0x00007fff28785dc3 RunCurrentEventLoopInMode + 292
22  com.apple.HIToolbox           	0x00007fff287859f6 ReceiveNextEventCommon + 284
23  com.apple.HIToolbox           	0x00007fff287858c3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
24  com.apple.AppKit              	0x00007fff22cd863e _DPSNextEvent + 864
25  com.apple.AppKit              	0x00007fff22cd6e11 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
26  com.apple.AppKit              	0x00007fff22cc9185 -[NSApplication run] + 586
27  com.apple.AppKit              	0x00007fff22c9d330 NSApplicationMain + 816
28  com.cockos.reaper             	0x000000010a903e74 start + 52

**Comment by vanhaze2000** [comment]
I updated to Big Sur 11.3 beta 3 and now opening Cycle Action editor doesn't crash Reaper anymore !

**Comment by cfillion** [comment]
Great!
