### ISSUE TITLE
API bug for finding the track under the mouse cursor

### ISSUE THREAD

**Issue by Yaunick** [reaper-oss/sws#1519]
Apparently the API bug for finding the track under the mouse cursor. I have a script for creating an item by double-clicking on a track, I use the SWS API there (I will attach the script under the post). The script assigned in mouse modifiers. However, if you create an item, then change the vertical zoom with the mouse wheel, then without scrolling and mouse clicking try to create an item again, the track is incorrectly detected, it is created 1+ track higher than expected track

![YSOSYOPAhl](https://user-images.githubusercontent.com/53025085/109626921-21d3de80-7b52-11eb-8644-e66622d799a7.gif)

Script:

[Yaunick_Insert item at mouse cursor within a measure (like in Studio One).zip](https://github.com/reaper-oss/sws/files/6067588/Yaunick_Insert.item.at.mouse.cursor.within.a.measure.like.in.Studio.One.zip)

**Comment by nofishonfriday** [comment]
Alternatively you could use native API equivalents [GetMousePosition](https://www.extremraym.com/cloud/reascript-doc/#GetMousePosition) and [GetTrackFromPoint](https://www.extremraym.com/cloud/reascript-doc/#GetTrackFromPoint).

@cfillion 
Maybe we should deprecate the SWS ones in favour of the native ones? 
(though fixing would be good nonetheless of course).

**Comment by Yaunick** [comment]
Thank you, yes, I will probably rewrite this script to the native API, but this is not one of my scripts with SWS API, where there are still different mouse contexts, in general I would like to fix it
