### ISSUE TITLE
OSX Big Sur 11.3 beta 3: "Xenakios/SWS Repeat paste" broken.

### ISSUE THREAD

**Issue by vanhaze2000** [reaper-oss/sws#1524]
Dear All, The Action Xenakios/SWS Repeat paste doesn't work for me. Latest SWS release (the 6 februari build) and Reaper release installed. OSX Big Sur 11.3 beta 3. I need this Action badly; i have to repeat paste 1 item 500 times. Others experiencing also that the Action is broken ?

**Comment by cfillion** [comment]
This action appears to work here: 1) copy an item 2) "Xenakios/SWS: Repeat paste" 3) OK = the item was duplicated the correct amount of times with the requested spacing. Feel free to re-open this issue if you're still having issues with it.
