### ISSUE TITLE
Not able to execute two CONSOLE statements  

### ISSUE THREAD

**Issue by cldswm** [reaper-oss/sws#1529]
Updated latest SWS and now unable to execute more then one CONSOLE statements in the cycle action editor.

**Comment by cfillion** [comment]
Works here (tried `CONSOLE s1` followed by `CONSOLE c0xff0000`). Do you have an example of a pair of console commands that broke in cycle actions?

**Comment by cldswm** [comment]
Hi thanks for getting , Yeah its just

CONSOLE s1

Followed by another statement

CONSOLE n 1/2 Stereo

Only the statement on the top will work and not the latter.

Im on the latest release of Reaper.

But i can confirm on a another machine with an older release it works.

Hmm

**Comment by cldswm** [comment]
> Updated latest SWS and now unable to create more then one CONSOLE statements in the cycle action editor.

Okay now trying again it has worked, i must had mis typed the commands some how. thanks!
