### ISSUE TITLE
JS_VKeys_GetState ,When the key is not released, the mouse clicks other windows, and the return value is wrong.

### ISSUE THREAD

**Issue by dangguidan** [reaper-oss/sws#1536]
The test code is as follows:
`function test()
state = reaper.JS_VKeys_GetState(0)
ret = state:byte(65)  --Key'A'
reaper.ShowConsoleMsg(ret)
reaper.defer(test)
end
test()`
When I press the "a" button, RET is 1. If I don't release the button and click the mouse to other places in windows, RET will always be 1, even if I go back to reaper. Until you click "a" again.

**Comment by cfillion** [comment]
This function is not part of SWS. It's exported by the js_ReaScript API extension: https://forum.cockos.com/showthread.php?t=212174.
