### ISSUE TITLE
BR_Win32_FindWindowEx() vs SWS 'Find' utlity window

### ISSUE THREAD

**Issue by Buy-One** [reaper-oss/sws#1556]
Manages to find SWS extension 'Find' utility window no matter what.

You may try this with all windows closed

```
hwnd = reaper.BR_Win32_FindWindowEx('0', '0', '0', 'Find', false, true)
_, text = reaper.BR_Win32_GetWindowText(hwnd)
reaper.ShowConsoleMsg(tostring(hwnd)..'\n')
reaper.ShowConsoleMsg(text..'\n')
```

**Comment by cfillion** [comment]
Can't duplicate here in a fresh install (tried on macOS and Windows).

![iReaScript](https://i.imgur.com/xwuwPu0.png)

**Comment by cfillion** [comment]
Maybe it's returning a Find window from another application? `FindWindowEx` is not limited to the REAPER process on Windows.

**Comment by Buy-One** [comment]
At the time i only had Notepad++ and Windows Explorer open. And today it returns nil. Super weird. Closing for now.
