### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by flaneurette** [reaper-oss/sws#1571]
When downloaded latest SWS and importing SWS in a Reaper Python script, I get an import error:

Snippet as where that happens:
```
    from sws_python import *
except ImportError:
    RPR_ShowConsoleMsg('Could not import SWS Python.\n')
    pass
```

Also, when I download older SWS versions, Windows defender labels it as malware, so I cannot test older versions.

**Comment by flaneurette** [comment]
Given this, do I really need to import all modules? I use SWS for the ReaChorder extension and only need MIDI manipulation. If I can import less modules, perhaps I can finetune on what module cannot be imported.

**Comment by flaneurette** [comment]
Yes, that works. Thank you cfillion!

**Comment by flaneurette** [comment]
From which version did this change? I ask, so that I can perform some checks and prompt a user to update SWS.

**Comment by cfillion** [comment]
It changed in v2.11.0 pre-release (v2.12.1 stable):

> Migrate the extension DLL to &lt;resource path&gt;\UserPlugins, reaper_sws.py to &lt;resource path&gt;\Scripts
