### ISSUE TITLE
FR: Support for action markers in Region Playlist OR an action to stop playback

### ISSUE THREAD

**Issue by Buy-One** [reaper-oss/sws#1575]
If playback was launched with Region Playlist transport it can't be stopped/paused with action markers.

So my suggestion is to either add support for action markers or alternatively (which is presumably a less labor intensive solution), to add action **SWS/S&M: Region Playlist - Stop**, because there's already one for starting playback **SWS/S&M: Region Playlist - Play** and accompanying it with a counterpart for Stop seems logical.

**Comment by nofishonfriday** [comment]
related/duplicate: https://github.com/reaper-oss/sws/issues/914
