### ISSUE TITLE
Zoom options don't respect "Lock track height"  feature

### ISSUE THREAD

**Issue by daeavelwyn** [reaper-oss/sws#1577]
Hello,

It seems track height lock is not recognize by : 
- SWS: Zoom to selected items or time selection, minimize others
- SWS: Zoom to selected items or time selection, minimize others (ignore last track's envelope lanes)
- SWS: Zoom to selected items, minimize others
- SWS: Zoom to selected items, minimize others (ignore last track's envelope lanes)

and maybe other verical zoom actions.

Step to reproduce : 

- create some tracks,
- lock their height by right clicking : "Lock track height"
- use one of the previously listed actions
- locked tracks are minimized.

**Comment by cfillion** [comment]
Enable "SWS/NF: Toggle obey track height lock in vertical zoom and track height actions".

**Comment by daeavelwyn** [comment]
Well, I guess I should have said this option was already enabled and that's the reason why I open this issue :-/

**Comment by cfillion** [comment]
Looks like it only honors the height lock on the non-selected tracks/tracks of unselected items. In other words it doesn't prevent the actions from doing the vertical+horizontal zoom on the selected tracks/selected item's tracks. That might be the intended behavior though. @nofishonfriday toughts?

Also found that those actions crash when all tracks in the project are locked. Division by zero here: https://github.com/reaper-oss/sws/blob/5d31e552ad3bcec8e03b0344d1833ea4d2f5fbf6/Zoom.cpp#L164

**Comment by nofishonfriday** [comment]
replied here: https://github.com/reaper-oss/sws/pull/1579
