### ISSUE TITLE
Support for track input and Monitoring FX chain windows in CF_GetTrackFXChain()

### ISSUE THREAD

**Issue by Buy-One** [reaper-oss/sws#1578]
~~Also reporting that in the latest version 2.12.1.3 Master track FX chain window still isn't recognized.~~ Back in July of 2020 https://github.com/reaper-oss/sws/issues/1394 Christian had said it would be included in the next version which came out half a year later as far as i understand. Was it eventually included?

**Comment by cfillion** [comment]
Getting the master track's FX chain seems to work here:

```
> reaper.CF_GetTrackFXChain(reaper.GetMasterTrack())
<userdata: 0x7ff47d959800>
```

Input/monitoring chain aren't supported, sounds like a good feature to add.

**Comment by Buy-One** [comment]
Should have been more precise, but just didn't expect it to matter.

It's not recognized using pointer obtained with GetSelectedTrack2(). This and GetMasterTrack() return different pointers for the Master track. Yet for regular tracks the pointers match.

**Comment by cfillion** [comment]
> This and GetMasterTrack() return different pointers for the Master track.

Which version of REAPER/OS? `reaper.GetMasterTrack() == reaper.GetSelectedTrack2(nil, 0, true)` is true here on 6.41 and 5.99, macOS.

A bunch of code in SWS and other scripts do equality checks with `GetMasterTrack`... if that changed some things may be broken now...

**Comment by Buy-One** [comment]
Sorry, an embarrassing mistake, i wasn't always selecting the Master track and the function returned the pointer of whatever track was selected at that moment.
