### ISSUE TITLE
BR_Win32_GetPrivateProfileString crops spaces in front of the returned string

### ISSUE THREAD

**Issue by amagalma** [reaper-oss/sws#1590]
Set "Save to timestamped file in additional directory:" in Reaper Preferences\Project to "   Backups".

Run the following in a lua script:
autosavedir = ({reaper.BR_Win32_GetPrivateProfileString( "reaper", "autosavedir", "", reaper.get_ini_file() )})[2]

The returned string is "Backups" instead of "   Backups".

**Comment by cfillion** [comment]
This trim "feature" comes from the old Windows 16-bit API. Try specifying `./ Backups` in the preferences instead. (Surrounding the value in the .ini with quotes also works, although not applicable in this specific case.)
