### ISSUE TITLE
Build 2.13: "SWS/FNG: Show only used CC lanes" doesn't work anymore

### ISSUE THREAD

**Issue by StephanRoemer** [reaper-oss/sws#1593]
Been trying to use this action in the MIDI editor, but unfortunately, it seems broken.

**Comment by cfillion** [comment]
Works here. Are you using REAPER v6.43+dev1222? None of SWS' non-main section actions works in that particular version.

**Comment by StephanRoemer** [comment]
Yes sorry, I was too slow. You were already discussing this in the 1222 pre thread.
