### ISSUE TITLE
??linux sws install??

### ISSUE THREAD

**Issue by probmatik** [reaper-oss/sws#1598]
I had no problem installing sws on windows but I cant seem to figure out how to install sws on linux armhf 64 bit.  I thought since I didn't see an install file I could just cut and paster the folders from the zip file , that didnt go well.

Please help me to understand.

**Comment by nofishonfriday** [comment]
Hi,
I'm not on Linux myself, but maybe this thread helps?
https://forum.cockos.com/showthread.php?t=210733

(ignore that the mentioned download locations for SWS have changed meanwhile since SWS Linux has become [official](https://www.sws-extension.org/) since then).

**Comment by cfillion** [comment]
Extract the archive in your REAPER resource folder (Options > Show REAPER resource path in explorer/finder). That's ~/.config/REAPER for a non-portable install.

```sh
tar -xf sws-2.12.1.3-Linux-x86_64.tar.xz -C ~/.config/REAPER
```
