### ISSUE TITLE
Global project startup action

### ISSUE THREAD

**Issue by Breeder** [reaper-oss/sws#1611]
We have:
SWS/S&M: Set project startup action
SWS/S&M: Set global startup action

One mone very useful addition could be made.

An action that is run whenever a project gets loaded in a sense that we wouldn't assign this project action to individual projects but on a global basis so it would run on ALL projects. This is different from current project startup action in a sense that it would run on all projects without a need to assign the action to a project.

These would be the actions introduced by this feature:

SWS: Clear global project startup action
SWS: Set global project startup action
SWS: Show global project startup action

P.S.
To not confuse users, maybe a little "what it is" explanation could be added to the dialog that shows startup actions.

**Comment by nofishonfriday** [comment]
Now available as seperate extension, so closing this one:
https://forum.cockos.com/showthread.php?t=269026
