### ISSUE TITLE
Request : make SWS notes fast

### ISSUE THREAD

**Issue by lowlou** [reaper-oss/sws#1614]
I notice that the SWS notes functions can get quite slow. Even simply writting things in the SWS notes is lagging in my project at this point. 

I use them a lot, they are very cool. But if I use "Script: cfillion_Duplicate tracks (preserving SWS track notes).lua" with folders (lots of tracks, 50+), the limit of current SWS notes start to show. The action takes half a minute to do its work. Heavy lifting it seems... But maybe it could be made lighter ? 

So I guess my request would be to think about making SWS notes a bit faster in the long run, for people like me that have started to use them as a very important tool. Not only to mark a few things ("change this, eq that, sample this"), but rather as an elaborate track tagging system, notes that can influence the actions of external scripts. 

SWS notes are VERY powerful. Make them go... faster please :p.
xxxxxxxx
louis

**Comment by Szapi** [comment]
It does look like the Duplicate Tracks script is sub-optimal. It is quadratic, but it could be made faster (n*logn worst case). I'm just a newcomer, but I'll see what I can do about it. I'm thinking about bulk operations. I dare not change the stored data structure for faster lookups.

**Comment by lowlou** [comment]
That would be absolutely awesome. Any improvement, even little, could have drastic positive impact, in the context of very very big Reaper projects, with extensive use of SWS notes. Thanks for answering :) ! xxx Louis

**Comment by Szapi** [comment]
Bulk operations seem problematic, I'm not sure if we could return an array to a Lua script from C++.

My second idea is we could keep the track notes array sorted by GUID at all times, and we could use binary search for lookups instead of linear search. This would speed up all existing scripts.

A hashtable would be even better, but I'm not sure if that's doable.

Anyway, I'll keep experimenting. (:

**Comment by lowlou** [comment]
Thanks guys for being commited to solving this bug... All the specifics are way way over my head, but be sure your work is highly appreciated. 
xxxxx 
louis
