### ISSUE TITLE
Can't download 2.12.1.3-template.ReaperLangPack, file not found

### ISSUE THREAD

**Issue by Ray-Lum** [reaper-oss/sws#1616]
https://www.sws-extension.org/download/featured/sws-2.12.1.3-template.ReaperLangPack

I'm going to translate the latest version, but can't get the language pack, please check it.

![屏幕截图 2022-03-03 174902](https://user-images.githubusercontent.com/51054841/156539744-3e931a42-17fb-4ea0-97c9-96238389dc26.png)
k

**Comment by nofishonfriday** [comment]
Ah yes, I'll contact the website admin to add it, meanwhile you can use the one I uploaded here:
[SWS_Template.zip](https://github.com/reaper-oss/sws/files/8182146/SWS_Template.zip)

**Comment by Ray-Lum** [comment]
Thanks a lot~ I will make a translation as soon as possible~

Ray Lum

发件人: ***@***.***>
发送时间: 2022年3月4日 8:57
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [reaper-oss/sws] Can't download 2.12.1.3-template.ReaperLangPack, file not found (Issue #1616)


Ah yes, I'll contact the website admin to add it, meanwhile you can use the one I uploaded here:
SWS_Template.zip<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Freaper-oss%2Fsws%2Ffiles%2F8182146%2FSWS_Template.zip&data=04%7C01%7C%7Cd52b09d4943c479d874d08d9fd7a010f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637819522718072071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cUsxx%2F0HJWHOrBgzioolfjKYqrj9axfpZaXQsvBUtxo%3D&reserved=0>

―
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Freaper-oss%2Fsws%2Fissues%2F1616%23issuecomment-1058720153&data=04%7C01%7C%7Cd52b09d4943c479d874d08d9fd7a010f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637819522718072071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vQCoF0XKz1tVCfgJUHAdLF5wdcG%2BZ9TyEV0a7BaO%2Ff8%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMFQR6L6YJ2QMHTOJ77DY5DU6FNYZANCNFSM5PZ6OJZA&data=04%7C01%7C%7Cd52b09d4943c479d874d08d9fd7a010f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637819522718072071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ppTJXLjxpK9xjS2I63T3yHOEROwgsJxsI5uGQlMWR%2Fg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cd52b09d4943c479d874d08d9fd7a010f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637819522718072071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lB22nnCVDvz7nJ%2FrDkfOVOnRNkjRLcCHEd556zO6oPc%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cd52b09d4943c479d874d08d9fd7a010f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637819522718072071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lr7ZdgdftUt24%2BZ98DnCRfGbDZU1BXew6DvAqrejWTI%3D&reserved=0>.

**Comment by nofishonfriday** [comment]
@Ray-Lum I've uploaded the wrong template first, sorry. 
So if you've downloaded shortly after I've replied please download it again, it's corrected now.

**Comment by Ray-Lum** [comment]
It doesn’t matter~ I had Download the latest version just now~ thank you for the notification 😊
--------------------
Ray Lum

发件人: ***@***.***>
发送时间: 2022年3月4日 23:06
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [reaper-oss/sws] Can't download 2.12.1.3-template.ReaperLangPack, file not found (Issue #1616)


@Ray-Lum<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRay-Lum&data=04%7C01%7C%7C87ed55eb36e84f10497908d9fdf08863%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637820031792759110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=X6NEj5uACqRfJr4HikjMX1x1woVD305C6cu66R87EC8%3D&reserved=0> I've uploaded the wrong template first, sorry.
So if you've downloaded shortly after I've replied please download it again, it's corrected now.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Freaper-oss%2Fsws%2Fissues%2F1616%23issuecomment-1059242279&data=04%7C01%7C%7C87ed55eb36e84f10497908d9fdf08863%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637820031792759110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=toAgEXT16ujyVua4cPFSa2aVnuw%2FY6VjpbwlM7assHE%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMFQR6NIPQ4BBSXMCRJVOXTU6IRGRANCNFSM5PZ6OJZA&data=04%7C01%7C%7C87ed55eb36e84f10497908d9fdf08863%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637820031792759110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e%2FvkJau4TUW9c3pd4%2BDPxxcYF4dtAES9nYt7vtJ7IEc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C87ed55eb36e84f10497908d9fdf08863%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637820031792759110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sTT3Z2RLrCm14a8QT25DprZuFsStvCv7iEnW4zAooCk%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C87ed55eb36e84f10497908d9fdf08863%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637820031792759110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4qBLB5ezUr4EI9asW%2BjRxBY2x97kiGoEzUM5Wpjn944%3D&reserved=0>.
