### ISSUE TITLE
SWS/BR: Copy take media source file path of selected items to clipboard - broken, doesn't copy anything to clipboard

### ISSUE THREAD

**Issue by hassee85** [reaper-oss/sws#1625]
Hi!

Can't run the action to copy the file path to the clipboard.

I have tried new projects in reaper on different drives and locations and it doesn't retrieve the file path on any audio item.

I have the latest Reaper version and running SWS 2.13.0.0 .

I have re-installed SWS but the problem persist.

Rest of the SWS actions works fine.

What could be broken? 

-----------
Windows 11

**Comment by nofishonfriday** [comment]
Confirmed on Win 10, REAPER v6.52, SWS 2.13.0.0.

**Comment by cfillion** [comment]
Oops, aa1b87a9a8f5dbf2ad622c724aa9b0de38e4479f broke this, my bad. Fixing!
