### ISSUE TITLE
Snapshots - Filter on Recall doesn't work with shortcuts

### ISSUE THREAD

**Issue by ArtemiHo** [reaper-oss/sws#1631]
Hello!

When you recall snapshots slots with SWS shortcuts (SWS: Recall snapshot) it's doesn't obey the "filter recall" function.
So it's still changing all the tracks regardless of the "Filter on Recall" toggle switch
I guess it's a bug.

It's a really nice feature that is really useful especially with keyboard shortcuts so please, notice me senpai.

Much thanks for checking!

Artemi

**Comment by nofishonfriday** [comment]
Confirmed.
![snapshots-filter-recall-bug](https://user-images.githubusercontent.com/7658194/167509954-942b8ef5-3b88-49e5-ae16-b8e9da46e0ec.gif)
