### ISSUE TITLE
LUA: BR_GetSetTrackSendInfo() instant crash if sent nil parameter name

### ISSUE THREAD

**Issue by MonkeyBars3k** [reaper-oss/sws#1636]
macOS 10.14.6
Reaper 6.57

Calling reaper.BR_GetSetTrackSendInfo() in LUA with nil as the 4th argument (parmname) causes an immediate Reaper crash any time it is invoked.

**Comment by cfillion** [comment]
Can't duplicate in REAPER 6.57, but I can confirm the bug in v6.57+dev0509 or newer.

> + ReaScript: make Lua handling of unspecified Optional const char* parameters consistent with other types/EEL2 [[t=266405](http://forum.cockos.com/showthread.php?t=266405)]


`BR_GetSetTrackSendInfo`'s `parmname` parameter isn't optional though (and EEL2 isn't affected), so guessing this is a bug on REAPER's side.

**Comment by nofishonfriday** [comment]
Fixed in [REAPER v6.58rc2](https://forum.cockos.com/showthread.php?t=266756).
