### ISSUE TITLE
Applying crossfade crash reaper

### ISSUE THREAD

**Issue by DuskAudio** [reaper-oss/sws#1638]
This issue has been around for a while, at least for me.
When i try to apply a crossfade to multiple media items and there are lanes hidden for that track , reaper crashes.
The action im using is SWS/AW: Fade in/out/crossfade selected area of selected items.
Event log says this:
Faulting application name: reaper.exe, version: 6.5.8.0, time stamp: 0x62858e81
Faulting module name: reaper_sws-x64.dll, version: 2.13.1.0, time stamp: 0x6276840f
Exception code: 0xc0000005
Fault offset: 0x0000000000107f6e
Faulting process ID: 0x2184
Faulting application start time: 0x01d86ed48efd4fc5
Faulting application path: C:\Program Files\REAPER (x64)\reaper.exe
Faulting module path: C:\Users\pedro\AppData\Roaming\REAPER\UserPlugins\ reaper_sws-x64.dll
Report ID: 59bda609-b3be-46e1-ac25-91064ed58d6f
Faulting package full name:
Faulting package-relative application ID:

Reaper forum thread:
https://forum.cockos.com/showthread.php?p=2561673#post2561673

**Comment by nofishonfriday** [comment]
@cfillion I see you've already reproduced in the forum thread, thanks.
But generally, apart from the exception code (access violation) , can we actually decipher anything from the fault offset (if so, how?)

**Comment by DuskAudio** [comment]
The steps were.
Creating a new track, recording some takes of an acoustic guitar, making some comps and then trying to crossfade the final comp, 
I remember having this issue before, never thought about posting in the forum.

**Comment by cfillion** [comment]
@nofish The fault offset points to the exact instruction that crashed:

1. Install the same release version of SWS with the corresponding code checked out in git
2. Debug reaper.exe in Visual Studio and, in the Modules window, for the SWS DLL:
    - Get its base address
    - Load debug symbols (.pdb for that exact build, in the artifacts list on AppVeyor only for 1 month after release so best to collect them)
3. Add the base address to the fault offset
4. Pause debugging and go to that address in the Disassembly window
5. `comisd xmm11,mmword ptr [rax]` = crashed comparing two doubles, one of them indirect = invalid pointer, likely null

**Comment by nofishonfriday** [comment]
Wow, thanks.

**Comment by cfillion** [comment]
@DuskAudio Should be fixed in this build: https://ci.appveyor.com/api/buildjobs/chsjjysutwj2k7cd/artifacts/build%2Fsws-2.13.1.0-Windows-x64-crossfade-empty-take-crash-7f8ec465.exe.

**Comment by DuskAudio** [comment]
I confirm this is fixed with this version. Thank you for the fix and for ultra fast reply. This means a lot for the end user ;) Best regards
