### ISSUE TITLE
 Actions with "Wait **** seconds before next action" don't work with cycle action. 

### ISSUE THREAD

**Issue by ovnis82** [reaper-oss/sws#1656]
Tested with Reaper@stock.

**Comment by cfillion** [comment]
Confirmed. According to a comment it seems this used to work around 2014. But now these actions are hard-coded in REAPER's custom action handler so they do nothing when ran by a SWS cycle action.

I suppose we could hard-code our own behavior for them... It's actually a whole range of actions that are currently no-op in cycle actions: 2000 through 2023.
