### ISSUE TITLE
Wrap text doesn't work in "Xenakios/SWS: Rename takes..."(Only in Windows)

### ISSUE THREAD

**Issue by mikekravets** [reaper-oss/sws#1671]
Hi !
I'm using ReaperBlog video scripts, and this feature is useful to rename midi items with text wrap to the next line, to create titles. It works on MacOs, but somehow does not work on Windows. Can you help with it ?
Greetings from Ukraine !
Example:
https://drive.google.com/file/d/1rCv3QNJ9-DYS1exNUlfPMT4znlzLMruB/view?usp=sharing

**Comment by cfillion** [comment]
That text field isn't meant to receive multiline input. Unfortunately, the behavior on Windows and Linux is the correct one.

(SWELL doesn't obey `~ES_MULTILINE`: every text box in REAPER on macOS is multiline.)
