### ISSUE TITLE
Paste fx series scripts for selected items is not work As expected.

### ISSUE THREAD

**Issue by vgjh2005** [reaper-oss/sws#1672]
Step to reproduce:

1. Create an empty track.
2. Add a new track fx.
3. select and copy the fx in the fx chain dialog.
4. Add a new track
5. Create some empty items.
6. Select an item.
7. Open action list.
8. Search for the action.
9. Selected an action.
10. Press run button.

Actually, the fx chain is not update at all.
Following action is tested:
SWS/S&M: Paste (replace) FX chain to selected items
SWS/S&M: Paste FX chain to selected items，20之3项
SWS/S&M: Paste (replace) FX chain (depending on focus)
SWS/S&M: Paste FX chain (depending on focus)
Reaper version: 6.66
sws: Version 2.12.1.3 98b2dbb9 built on Feb  6 2021
Windows 11 21H2 (x64) build 22000.856 x64 
Thanks!

**Comment by cfillion** [comment]
The SWS "Paste FX chain" action only work on data copied using one of the SWS "Copy FX chain" action. They don't paste individual effects. SWS doesn't have access to REAPER's own internal FX clipboard.

- SWS/S&M: Copy FX chain (depending on focus)
- SWS/S&M: Copy FX chain from selected item
- SWS/S&M: Copy FX chain from selected track
- SWS/S&M: Copy input FX chain from selected track
