### ISSUE TITLE
SWS / S&M Extensions not installing on M1 Pro Macbook

### ISSUE THREAD

**Issue by Anomia2** [reaper-oss/sws#1673]
I followed the instructions on how to install the SWS / S&M Extensions on a Macbook Pro with the M1 Pro but nothing comes up. 

I've installed the correct ARM64 versions and copied the file "reaper_sws-arm64.dylib" to the UserPlugins Folder for Reaper but no additional "Extensions" menu pops up after starting Reaper again. 

When trying to run the file itself to see what happens I get this error "zsh: exec format error:".

**Comment by cfillion** [comment]
Are you running REAPER ARM64 or x86_64 (via Rosetta)? SWS ARM64 can only run in REAPER ARM64.

Another possibility is it's getting blocked from running by macOS. If that is the case, click on "Allow Anyway" in macOS Preferences > Security & Privacy.

> When trying to run the file itself to see what happens I get this error "zsh: exec format error:".

This is normal, SWS is not a standalone executable.

**Comment by Anomia2** [comment]
I’m running the following version currently and ran REAPER ARM64 prior as far as I remember.

(Current Version)
macOS 10.15+
REAPER v6.68 - 25MB
Universal for Intel and ARM64

I reinstalled Reaper and placed the file “reaper_sws-arm64.dylib” from the sws-2.12.1.3-Darwin-arm64.dmg download in the UserPlugins folder again to check. I ran the file to have the pop under “Security & Privacy” to have me allow it to run.

I still don’t see any SWS Extensions.



From: Christian Fillion ***@***.***>
Date: Tuesday, October 11, 2022 at 11:22 PM
To: reaper-oss/sws ***@***.***>
Cc: Anomia2 ***@***.***>, Author ***@***.***>
Subject: Re: [reaper-oss/sws] SWS / S&M Extensions not installing on M1 Pro Macbook (Issue #1673)

Are you running REAPER ARM64 or x86_64 (via Rosetta)? SWS ARM64 can only run in REAPER ARM64.

Another possibility is it's getting blocked from running by macOS. If that is the case, click on "Allow Anyway" in macOS Preferences > Security & Privacy.

When trying to run the file itself to see what happens I get this error "zsh: exec format error:".

This is normal, SWS is not a standalone executable.

**Comment by cfillion** [comment]
> Universal for Intel and ARM64

Try installing the x86_64 version just in case, since REAPER's universal build contains both.

>  I ran the file to have the pop under “Security & Privacy” to have me allow it to run. I still don’t see any SWS Extensions.

Just to be sure I'm understanding right, did reaper_sws_arm64.dylib show up in Security & Privacy or you didn't see it?

**Comment by Anomia2** [comment]
I’ll try the version you mentioned.


Regarding this question “Just to be sure I'm understanding right, did reaper_sws_arm64.dylib show up in Security & Privacy or you didn't see it?” : It showed up when I manually ran the file.
From: Christian Fillion ***@***.***>
Date: Thursday, October 13, 2022 at 12:10 AM
To: reaper-oss/sws ***@***.***>
Cc: Anomia2 ***@***.***>, Author ***@***.***>
Subject: Re: [reaper-oss/sws] SWS / S&M Extensions not installing on M1 Pro Macbook (Issue #1673)

Universal for Intel and ARM64

Try installing the x86_64 version just in case, since REAPER's universal build contains both.

I ran the file to have the pop under “Security & Privacy” to have me allow it to run. I still don’t see any SWS Extensions.

Just to be sure I'm understanding right, did reaper_sws_arm64.dylib show up in Security & Privacy or you didn't see it?

**Comment by Anomia2** [comment]
SWS installed on the "x86_64" version.
