### ISSUE TITLE
“reaper_sws-arm64.dylib” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by TheQuinbox** [reaper-oss/sws#1688]
When trying to install SWS on an M1 MacBook Air into Reaper, it throws up a nice ugly error in my face:
“reaper_sws-arm64.dylib” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

Safari downloaded this file today at 2:03 AM.
Reaper 6.68, Universal, and SWS latest, ARM64.
Any ideas?

**Comment by nofishonfriday** [comment]
Please see [here](https://github.com/reaper-oss/sws/wiki/Installing-the-SWS-Extension-(for-end-users)) to unquarantine it (you'd need to adjust the command for the ARM version).

**Comment by TheQuinbox** [comment]
@nofishonfriday that fixed it, thanks! For reference, in case anyone else ever comes across this, the exact command is:
xattr -d com.apple.quarantine ~/Library/Application\ Support/REAPER/UserPlugins/reaper_sws-arm64.dylib

**Comment by cfillion** [comment]
@nofishonfriday It's also possible to authorize SWS to launch via the GUI: https://youtu.be/NDwmqJYJq9s?t=336.

**Comment by nofishonfriday** [comment]
I'll add that to the Wiki, thanks.
