### ISSUE TITLE
Functiont to cast Int2Double and Double2Int

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#1697]
I'm working a lot with the BASE64-render-strings that encode the render-information.
When encoded, part of them(fps for video, quality-ratios, etc) are integer representations of float/double-values.

The problem is: if you want to create such a string and you need to add fps to a video-render-string, you are doomed in Lua, as you can't convert a number into its integer representation to include them into the proper position.
And you can't just do number, because...it does not work.
So you can't create such strings, if floats/double are needed as their integer representation.

In Ultraschall-API, I worked around it by manually mapping the integer from the render-string to its number-representation but this is tedious and not working for people not wanting to use Ultraschall-API.

Justin wrote on askjf.com, that it's just a simple casting of int 2 float vice versa, and as C can do such things, I would like to ask for functions, who do exactly that: cast from int 2 float 2 int and from int 2 double and back 2 int.

This would allow all people creating the renderstrings or analyzing a render-string for the currently set values.

This would be awesome...

**Comment by cfillion** [comment]
string.pack / string.unpack?

**Comment by mespotine** [comment]
Thnx, will check, if it works...

**Comment by mespotine** [comment]
Hmm, I tried, but it doesn't seem to work, as I thought it would.

Here are some examples, what the casting does, when converting it from double to integer-representation:

0.1 -> 1036831949
0.2 -> 1045220557
0.3 -> 1050253722
...

65 -> 1115815936
65.1 -> 1115829043

and so on.
That's the numbers, Reaper uses in render-strings for fps or quality-settings. It's possible via casting one type into another, but I have no clue how.
Maybe string.pack does it, but I have no idea, how to attempt it...

**Comment by cfillion** [comment]
Missed the email... Where are you getting these numbers from? Binary integer and floating-point decoding/encoding to/from Lua numbers works here:

```lua
luaInteger = 1036831949
binaryInteger = string.pack('i', luaInteger)
luaFloatingPoint = string.unpack('f', binaryInteger)
```

Produces 0.10000000149012.
