### ISSUE TITLE
SNM_SetStringConfigVar and "ccresettab" ?

### ISSUE THREAD

**Issue by DaveInDev** [reaper-oss/sws#1703]
Hi, 
it seems that SNM_SetStringConfigVar  and get_config_var_string do not recognize the "ccresettab" config variable (it's the one that correspond to the string in option pref/audio/playback/cc reset override.

I noticed that this variable is not either listed in https://mespotin.uber.space/Ultraschall/Reaper_Config_Variables.html

**Comment by cfillion** [comment]
It's not a configvar so SWS can't access it either (guessing it's because REAPER parses it at load time, and wouldn't be notified to do that when configvars are externally modified)
