### ISSUE TITLE
editing keys using the control key are not handled by the SWS notes dialog

### ISSUE THREAD

**Issue by RDMurray** [reaper-oss/sws#1721]
In the notes dialog, The following keys are passed to the main window instead of working as expected:
* control+home/end/left/right
* control+shift+home/end/left/right
* Control+Z

It looks easy enough to fix; should I submit a pull request?

**Comment by cfillion** [comment]
> It looks easy enough to fix; should I submit a pull request?

If you've figured out a fix, that would be welcome!

Quickly tried something: this seems to do the trick on Windows, but not on macOS – more investigation needed...
```diff
diff --git a/SnM/SnM_Notes.cpp b/SnM/SnM_Notes.cpp
index 33652e3a..4d70d4f5 100644
--- a/SnM/SnM_Notes.cpp
+++ b/SnM/SnM_Notes.cpp
@@ -440,6 +440,8 @@ int NotesWnd::OnKey(MSG* _msg, int _iKeyState)
 			_msg->hwnd = m_hwnd; // redirect to main window
 			return 0;
 		}
+		else if(GetFocus() == m_edit)
+			return -1;
 		else if (_msg->message == WM_KEYDOWN || _msg->message == WM_CHAR)
 		{
 			// ctrl+A => select all
```

**Comment by cfillion** [comment]
Found the problem on macOS: it's the menubar triggering the main window shortcuts. The Action List search field and Media Explorer aren't affected so I looked into what they're doing.

By replacing the menubar to just have a "Edit" menu, this fixes Cmd+A and others in SWS notes, but not Cmd+Z yet. The Undo/Redo menu actions are always grayed out for some reason...

```diff
diff --git a/SnM/SnM_Notes.cpp b/SnM/SnM_Notes.cpp
index 33652e3a..48ea861a 100644
--- a/SnM/SnM_Notes.cpp
+++ b/SnM/SnM_Notes.cpp
@@ -154,6 +154,16 @@ void NotesWnd::OnInitDlg()
 	SetWindowLongPtr(m_edit, GWLP_USERDATA, 0xdeadf00b);
 	SetWindowLongPtr(GetDlgItem(m_hwnd, IDC_EDIT2), GWLP_USERDATA, 0xdeadf00b);
 
+	if(HMENU menu = SWELL_GetDefaultModalWindowMenu()) {
+		if ((menu = SWELL_DuplicateMenu(menu))) {
+			SetMenu(m_hwnd, menu);
+
+			// reaper does this, don't know why yet (seems to be working fine without)
+			// menu = GetSubMenu(menu, 0);
+			// SWELL_SetMenuDestination(menu, GetMainHwnd());
+		}
+	}
+
 	m_resize.init_item(IDC_EDIT1, 0.0, 0.0, 1.0, 1.0);
 	m_resize.init_item(IDC_EDIT2, 0.0, 0.0, 1.0, 1.0);

```

**Comment by RDMurray** [comment]
Thanks @cfillion for looking into this. To be honest I hadn't thought about macOS ☺️ Could it be that swell just doesn't support undo in edit controls? I'm not familiar with the swell source, but I don't see anything related to undo in swell-wnd-generic.cpp, where cut/copy/paste are implemented.

**Comment by cfillion** [comment]
Those *generic.cpp files are the Linux implementation of SWELL. The macOS version (in the .mm files) use native macOS controls.

Got it fully working on macOS & Windows in #. (It already worked as-is on Linux.)
