### ISSUE TITLE
Feature Request: ReaScript function that returns dBs going in and out of focused Track/ItemFX

### ISSUE THREAD

**Issue by kveberg** [reaper-oss/sws#1724]
If possible a function that can be called from a ReaScript that returns the dB-values going in and out of a focused TrackFX/ItemFX.

**Comment by cfillion** [comment]
As in measuring the audio before and after a given plugin? The only way to do that would be via inserting a plugin before/after the plugin to spy on. A ReaScript can do that by inserting two instances of JSFX.

**Comment by kveberg** [comment]
Ok, thanks =)
