### ISSUE TITLE
Vertical Zoom to selected tracks is broken with REAPER 6.76

### ISSUE THREAD

**Issue by chmaha** [reaper-oss/sws#1739]
Not much more to say but when moving back to 6.75 the action _SWS_VZOOMFIT works as expected. I rely on it for one of my ReaClassical scripts.

**Comment by cfillion** [comment]
Version [v2.13.2.0](https://www.sws-extension.org/download/pre-release/#v2.13.2.0-a3693ad5) adds support for REAPER v6.76's vertical zoom overhaul.
