### ISSUE TITLE
Snapshots deleted?

### ISSUE THREAD

**Issue by divedive** [reaper-oss/sws#1748]
SWS Snapshots are getting deleted. Anyone else seeing that?

**Comment by bzeffren** [comment]
I experienced this yesterday as well

**Comment by nofishonfriday** [comment]
https://github.com/reaper-oss/sws/issues/1743#issuecomment-1499551614

**Comment by bzeffren** [comment]
Switched to Reaper v6.78+dev0406 per ☝️ comment and it seems to be working ok now. Thanks @nofishonfriday 
Will know for sure after a few days, since for me the issue started four days into a project.

**Comment by nofishonfriday** [comment]
REAPER 6.79 which contains this fix was just released, so closing this issue.
If it should still persist after updating, please open a new issue.
