### ISSUE TITLE
Region Playlist becomes empty intermittently

### ISSUE THREAD

**Issue by idanez** [reaper-oss/sws#1749]
The issue is: I add all my regions to the playlist and save the project. Sometimes, event without closing the project or the playlist tab, simply by changing tabs, to the mixer for instance and back to the playlist, it becomes empty. 

Othertimes it stays for the same session, but when I close Reaper and get back to it another day, the playlist is empty again.

I can`t tell the exactly steps to reproduce the issue because it is intermitent, I use Reaper/SWS in a HighSierra Macbook Pro.

**Comment by nofishonfriday** [comment]
Which Reaper version?
If you're on Reaper v6.76 and above and the issue began to show just recently then it's likely [this issue](https://github.com/reaper-oss/sws/issues/1743).
Today a Reaper pre-release was released which should fix (see [here](https://github.com/reaper-oss/sws/issues/1743#issuecomment-1499551614)).
