### ISSUE TITLE
SWS: Minimize selected tracks(s) + Lock Height on Doesn't Obey Minimum Height

### ISSUE THREAD

**Issue by r3coil23** [reaper-oss/sws#1752]
When you have a folder with Track Height Locked, and call "SWS: Minimize selected tracks(s)", the folder will not be set to the minimum default track height, but to something like 1 pixel. When the Track Height is unlocked the "SWS: Minimize selected tracks(s)" works correctly.

**Comment by nofishonfriday** [comment]
Confirmed. 
It happens regardless if 'SWS/NF: Toggle obey track height lock in vertical zoom and track height actions' is enabled or not.
Tested with SWS 2.13.2.0.

![#1752](https://github.com/reaper-oss/sws/assets/7658194/72105142-59b9-4413-9aaf-9e833564e933)
