### ISSUE TITLE
Crash when using 'SWS: Vertical zoom to selected tracks, minimize others'

### ISSUE THREAD

**Issue by JJ3n** [reaper-oss/sws#1756]
Worked until the latest Reaper update (6.79), now crashes everytime I click the action 'SWS: Vertical zoom to selected tracks, minimize others'.

**Comment by cfillion** [comment]
I can't duplicate a crash on 6.79 with either SWS v2.13.2 (recommended) nor v2.12.1. Tried on macOS 10.14.

- What are the exact steps needed to trigger a crash starting from a blank project?
- Please attach a crash report (report window on macOS or in the event viewer on Windows)

**Comment by JJ3n** [comment]
I just click the button or use my shortcut to trigger the 'SWS: Vertical zoom to selected tracks, minimize others' action and it crashes. Attached you'll find the crash report

[CrashReportforSWS.txt](https://github.com/reaper-oss/sws/files/11395853/CrashReportforSWS.txt)

**Comment by cfillion** [comment]
Thanks for the report! This bug occurs when all tracks in the project have their height locked and "SWS/NF: Toggle obey track height lock" is enabled.

**Comment by JJ3n** [comment]
Unlocking the track height (which I have no idea on why I would have locked it in my track template in the first place) fixed the crashing instantly. Thanks a lot!

**Comment by cfillion** [comment]
Thanks for the report! This bug occurs when all tracks in the project have their height locked and "SWS/NF: Toggle obey track height lock" is enabled.

It was fixed in v2.13 a while ago. You are running v2.12.1.3 which is over two years old. The latest version is available here: https://www.sws-extension.org/download/pre-release/.
