### ISSUE TITLE
Master track is treated as a folder parent and regular tracks as folder children by 3 actions

### ISSUE THREAD

**Issue by Buy-One** [reaper-oss/sws#1764]
SWS: Select only parent(s) of selected folder track(s)  
SWS: Select parent(s) of selected folder track(s)
SWS: Unselect parent(s) of selected folder track(s)

Is this by design?  If it's a bug I think it's worth keeping in mind that user custom/cycle actions may rely on the current behavior so it's best if a fix is backward compatible, such as 3 new actions with the originally intended behavior.

![Master as parent, regular track as folder child](https://github.com/reaper-oss/sws/assets/61803004/ea78df11-91e5-45b7-a742-df95d61ad3fb)

**Comment by cfillion** [comment]
Yes, it seems to be by design. The master track is explicitly considered as if it were a folder track with depth level -1. I think that's conceptually correct as it matches the behavior of the "Parent send" checkbox in the routing dialog.

**Comment by Buy-One** [comment]
OK
