### ISSUE TITLE
"SWS: Vertical zoom to selected tracks" not working in Reaper 6.80 on Windows 10.

### ISSUE THREAD

**Issue by spammusubican** [reaper-oss/sws#1767]
The action SWS: Vertical zoom to selected tracks (_SWS_VZOOMFIT) no longer works after updating to Reaper 6.80 on Windows 10.

Doing some basic testing _SWS_VZOOMFIT_NO_ENV also seems to be broken, but _SWS_VZOOMFITMIN and _SWS_VZOOMFITMIN_NO_ENV both continue to operate as expected.

(SWS version v2.12.1.3)

**Comment by cfillion** [comment]
Update SWS to 2.13.2 for support of REAPER v6.76's enhanced vertical zoom. https://www.sws-extension.org/download/pre-release/
