### ISSUE TITLE
Request for more regions in goto/select

### ISSUE THREAD

**Issue by Oeyvind** [reaper-oss/sws#1771]
The current SWS extensions offer an action to "Go to/select region 1 (obeys smooth seek)", it is available for regions 1,2,3,4. Would it be possible to offer more regions? 10 regions would be good.

**Comment by cfillion** [comment]
It's customizable via a setting:

1. Options > Show REAPER resource path in explorer/finder
2. Open `S&M.ini` in a text editor
3. Close REAPER
4. Search for `S&M_GOTO_SEL_REGION=4`
5. Edit the number and save
6. Start REAPER

**Comment by Oeyvind** [comment]
Ah, that is perfect. Thank you!

fre. 23. juni 2023 kl. 14:26 skrev Christian Fillion <
***@***.***>:
