### ISSUE TITLE
want to install SWS Bleeding Edge Build but getting an error

### ISSUE THREAD

**Issue by raaphorst** [reaper-oss/sws#1774]
I have SWS already installed but want to upgrade to the newest version. Downloaded the [sws-2.13.2.0-Darwin-x86_64-a3693ad5.dmg](https://www.sws-extension.org/download/pre-release/sws-2.13.2.0-Darwin-x86_64-a3693ad5.dmg) for my Intel Mac. When opening the DMG I cannot drag the dylib into UserPlugins. When I click on UserPlugins it says it can't find that folder. Is this a bug?

**Comment by cfillion** [comment]
Yes, it it's a very old bug (though reported recently: #1757). See the comment in that other report for the correct location of UserPlugins. (Closing this one as duplicate.)

In recent versions of macOS there is an additional step required to authorize SWS to run: https://github.com/reaper-oss/sws/wiki/Installing-the-SWS-Extension-(for-end-users)#macos.
