### ISSUE TITLE
SWS v2.9.6 Error with Scripts in Reaper

### ISSUE THREAD

**Issue by clayblair** [reaper-oss/sws#1777]
Running the latest version of Reaper and SWS. Keep getting this error when using custom scripts that i know work. I got them from another engineer who uses them daily. I am not a developer. I am just trying to figure this out so I can use them.

<img width="1728" alt="Screen Shot 2023-07-23 at 2 32 59 PM" src="https://github.com/reaper-oss/sws/assets/24196984/a3b50a3a-d41d-4429-bf9a-d80cb45c3005">

**Comment by cfillion** [comment]
What is the script in question? The screenshot only shows a custom action.

**Comment by clayblair** [comment]
Its a number of scripts but here is the basic one. The Lufs normalization is tied into several other scripts but this is the basic one. 

--[[
 * ReaScript Name: nofish_Set normalize loudness to X LUFS max momentary target value
 * Version: 1.0
 * Author: nofish
 * About:
 *  This script works together with "nofish_Normalize loudness of selected items active take to X LUFS max momentary - no prompt.lua"  
 *  Set the LUFS max momentary target value here than use above script to normalize to this target value.   
 *  The target value is persistent across REAPER projects.  
--]]


--[[
 * Changelog:
  
 * v1.0 - September 8 2017
    + initial release
--]]

function preventUndo()
end
reaper.defer(preventUndo)

function promptUser()
  if reaper.HasExtState("NF_normalizeToMaxMomentaryLUFS_noPrompt", "momentaryTargetLUFS_noPrompt") then
    caption = reaper.GetExtState("NF_normalizeToMaxMomentaryLUFS_noPrompt", "momentaryTargetLUFS_noPrompt")
  else
    caption = "-23"
  end
    
  retval, target_string = reaper.GetUserInputs("Normalize to momentary max. LUFS", 1, "Target level:", caption)
  
  if retval then 
    if tonumber(target_string) then
      reaper.SetExtState("NF_normalizeToMaxMomentaryLUFS_noPrompt", "momentaryTargetLUFS_noPrompt", target_string, true)
      -- gets stored in "reaper-extstate.ini"
    else -- not a number
      promptUser()
    end
  else -- pressed 'Cancel'
    reaper.SetExtState("NF_normalizeToMaxMomentaryLUFS_noPrompt", "momentaryTargetLUFS_noPrompt", caption, true)
  end
end

promptUser()

**Comment by cfillion** [comment]
(Closing this because it's not a SWS issue or feature request.)
