### ISSUE TITLE
Increase/Decrease Metronome volume actions appear not to work

### ISSUE THREAD

**Issue by kevinlong206** [reaper-oss/sws#1778]
I tested this on both macOS  (12.6 Monterey, M1 macbook air)
as well as my Windows 11 laptop.

Reaper 6.81 (latest stable) in both cases, latest SWS Extension download (2.12.1.3).

ARM build (mac) and 64 bit build (Windows) respectively.

Could not get these actions to have any effect with either keyboard or MIDI assignments.

**Comment by kevinlong206** [comment]
> It changes "Primary beat volume" in Options > Metronome/pre-roll settings.

Thanks, that is what I expected it to do, but I'll do some more testing as it seems like it may be working at least on my Windows machine with keyboard shortcut. Curiously doesn't seem to work when the metronome settings window is open, despite me assigning Global+TextFields scope to the shortcut.. hmm

**Comment by cfillion** [comment]
Because of the way REAPER allows extensions and scripts to modify these settings, it cannot know that the value changed and update the slider in the window. However the new volume is actually set and audible. It's just not visually shown until the window is closed and opened again.
