### ISSUE TITLE
add _sws to the missing sections of the template file

### ISSUE THREAD

**Issue by tohubohu38** [reaper-oss/sws#1783]
Hello, to facilitate the translation of sws, could you please add undercore sws  _sws  attached to each section of the sws template? Some sections do not contain the word sws.
In fact, to translate sws with Justin's new langpackedit software, we can't merge the two files (langpack + sws) permanently, because when in the langpackedit filter we want to remove not-in-template lines, we can't exclude sws by writing: not-in-template NOT sws.
This means we always have to separate the two files when translating or making modifications. This is not practical.
The sws template contains, for example, the common or fx sections...etc... For all these sections, it would be sufficient to add common_sws and fx_sws...etc
Thank you very much
Tohubohu

**Comment by cfillion** [comment]
Most strings in the common and fx section are meant to be referring to REAPER's translated string rather than having a SWS-specific copy of them.

For the other strings that don't belong in those sections, correcting that now would break years of existing langpacks...

**Comment by cfillion** [comment]
> are the strings in these sections already in reaper's langpack

Most of them. `[common]` also contains SWS-specific strings that are used in more than one other section (to avoid having to translate the same thing twice). Those have a `^` prefixed in the other sections.
