### ISSUE TITLE
Accessibility: In the FX container SWS actions to move the FX up or down would be useful to speed up work

### ISSUE THREAD

**Issue by Lo-lo78** [reaper-oss/sws#1788]
Hi everyone, I'm an OSARA user on Reaper and like many users of this DAW. If you have installed OSARA you certainly have SWS.
Thanks to your extensions on Reaper you have given the concrete possibility to understand how Reaper is a brilliant DAW in terms of accessibility.
There are now FX containers in Reaper 7.
Excellent work has been done on accessibility on OSARAma 
It would be interesting if in the next release of SWS two actions could be developed to move the plugin up or down in the FX container.
In practice it would be a replication of two already existing actions:
"SWS/S&M: Move selected FX up in chain for selected tracks"
"SWS/S&M: Move selected FX down in chain for selected tracks".
These two actions affect the track's FX chain.
Would it be possible to replicate them for the FX container?
Thank you for the work that has been done all these years.
👍
Greetings!

Sorry for the English! :))

**Comment by cfillion** [comment]
Closing in favor of #1781.
