### ISSUE TITLE
Actions to select item envelope

### ISSUE THREAD

**Issue by tohubohu38** [reaper-oss/sws#1789]
To create custom actions, the following important actions are missing from the native actions, sws, or reapak script: 

Actions

- select item volume envelope 
- select item pan envelope
- select item mute envelope
- select item pitch envelope

**Comment by Buy-One** [comment]
@tohubohu38 What would be the use case for these actions?

**Comment by tohubohu38** [comment]
Hello,
Any type of custom action concerning take envelope points is almost impossible.
For example, create a button to delete all the take volume envelope points of the selected item or of all the items in the track or fixed lane.
Or
Reduce the number of points of all the take volume envelopes of all the items in the track or fixed lane. 
Etc...
If this isn't convincing, I can explain it better...

**Comment by Buy-One** [comment]
OK. Take a look at the 4 scripts [HERE](https://github.com/Buy-One/REAPER-scripts/tree/main/Envelopes). Hope they'll be of use.

**Comment by nofishonfriday** [comment]
I think we can close this as the request is implement by scripts (thanks @Buy-One).
