### ISSUE TITLE
Accessibility:  in items SWS actions to move the FX up or down the FX chain could be very useful

### ISSUE THREAD

**Issue by Lo-lo78** [reaper-oss/sws#1790]
Hi everyone!
It would be very useful to have two actions that move the FX up or down in the selected item as well.
For the moment on SWS it is only possible to do this in the track's FX chain.
I am referring to the actions:
"SWS/S&M: Move selected FX up in chain for selected tracks"
"SWS/S&M: Move selected FX down in chain for selected tracks"
Thanks and good job!

**Comment by Buy-One** [comment]
Hi

You're welcome to try scripts available [HERE](https://github.com/Buy-One/REAPER-scripts/tree/main/FX)

`Move selected take FX down in the chain.lua`

`Move selected take FX down up the chain.lua`

**Comment by Lo-lo78** [comment]
@Buy-One 
Hi, I didn't find the lua scripts you reported to me on ReaPack.
I tried to update the xml and then searched the action list but nothing came up regarding the takes or items.
Do you have the xml that has these scripts?
Thank you!

**Comment by Buy-One** [comment]
I gave a direct link to the repo from where you can download them. My repo isn't compatible with ReaPack.

**Comment by Lo-lo78** [comment]
@Buy-One 
Thank you!
Both actions work well...
👍

**Comment by Lo-lo78** [comment]
@Buy-One 
I am closing this issue because it has been resolved.
Thank you!

**Comment by Lo-lo78** [comment]
@Buy-One 
I'm trying both actions and they work.
There is only a small system cursor focus issue.
The plugin moves up or down but if I immediately move the cursor I am at the top of the FX chain.E' possibile risolvere questo problema di focus?
The problem can arise when the FX chain is very large. Obviously if there are two or three plugins it's not a problem.
Thank you!

P.S.
Sorry if I closed the issue and then reopened it.
I noticed it later.

**Comment by Buy-One** [comment]
Hi

Since it's no longer a SWS extension issue, i propose to move the discussion to my repo issue tracker at https://github.com/Buy-One/REAPER-scripts/issues

Please describe the issue there in greater detail, preferably with screenshots and animations.
