### ISSUE TITLE
action to select the two end points of a segment in an envelope.

### ISSUE THREAD

**Issue by Javiramallo** [reaper-oss/sws#1793]
Hello friends. Here is a REAPER Lover with very little knowledge of how to achieve something like this.

In short, I have been looking for a long time for something that, at first glance, seems simple. I hope it is!

 **This is an action to select the start point and end point of a segment of an envelope.**

My intention is to assign this action to a "mouse modifier", for example double click on a segment of a volume envelope and have these points selected and from there, move them up or down using the keyboard instead of the mouse.

I don't know if anyone could help me with this.

Thanks in advance.
Javier.

**Comment by Buy-One** [comment]
If i understand the use case correctly this can be done with the following native actions

`Envelope: Select points in time selection` (not by double click but close)
`Item edit: Move items/envelope points up/down one track/a bit`

**Comment by Javiramallo** [comment]
Hi Buy-one. Thanks for answer!

There is not a Previous time selection!

**Comment by Buy-One** [comment]
What do you mean by `previous time selection`?

**Comment by Javiramallo** [comment]
Sorry. I'll try to explain myself better. What i am trying is to get an action to select starting point and the final point of a segment of an envelope.

In your answer where you wrote this: 
> If i understand the use case correctly this can be done with the following native actions
> 
> `Envelope: Select points in time selection` (not by double click but close) `Item edit: Move items/envelope points up/down one track/a bit`

I understood that you meant that if I do a time selection, there is already an action which select the endpoints in the time selection. 

However, the action I am looking for, try to select de two points of the segment regardless the time selection. In short, this action is nos  time selection depend. 

I do not know if now I am explaining myself better!

Thank Buy-One.

**Comment by Buy-One** [comment]
I see. In REAPER terminology a segment is a line between exactly 2 points with no points in between. If between two points there're other points you have more then one segment. So in your case what should define the "segment", how many points is a segment? The program cannot know that unless you tell it, such as by creating a time selection or a Razor edit area.

**Comment by Javiramallo** [comment]
For me a segment is a line between two points! For if help I am attaching a capture where I mark in red several segments in order to clarify what i am calling a segment!
![segmets](https://github.com/reaper-oss/sws/assets/19627705/b63507b9-5369-4159-aa75-800636bc6852)

**Comment by Buy-One** [comment]
Hi

You're welcome to try the script

`Select envelope segment points under mouse cursor.lua`

available [HERE](https://github.com/Buy-One/REAPER-scripts/tree/main/Envelopes)

**Comment by Javiramallo** [comment]
OMG! Thank you for the effort. Works perfectly in regular envelopes. Unfortunately, I caught two issues:

Issue 1:   do not work inside AI.
Take a look the GiF.
![ISSUE 1 - fail in the Automation Item](https://github.com/reaper-oss/sws/assets/19627705/27bd0aea-509c-4f1c-8314-82e7aa3e12a1)

Issue 2: If there are some points selected inside an AI them, they remain selected! Regardless you do other points selections in other envelope zone!
Take a look the GIF: 
![ISSUE 2 - fail points inside Automation item remain selected!](https://github.com/reaper-oss/sws/assets/19627705/ebb70f8a-f51f-4a75-874a-6110f771f161)

Please, let me know how can I "buy one" for you please.!

**Comment by Buy-One** [comment]
The 2d problem i already know how to fix and i will. 

The 1st one not sure yet because i tested with AIs and it worked. I believe i will need a minimal example project or a track template  where it doesn't work.

**Comment by Javiramallo** [comment]
Thanks!  

I am attaching a .zip file with a simple project!  
In this project you'll notice that, with the new Script, It is posible to select segments out the AI  but not inside them.  

[Sample Selecting Points inside AI fail lowres.zip](https://github.com/reaper-oss/sws/files/13324994/Sample.Selecting.Points.inside.AI.fail.lowres.zip)
Let me know if you can't reproduce this behaviour, please.   

Thanks, in advanced.

**Comment by Buy-One** [comment]
Thank you.

**Comment by Buy-One** [comment]
Just updated the script. Please try the latest version at the same link,

**Comment by Javiramallo** [comment]
Hi BuyOne.

Now it works perfect! magic for me!
I appreciate your effort.  I am very grateful!!!.

Please, give me a way to buy you some beers!

**Comment by Buy-One** [comment]
Great. Buy yourself and your biddies a bear and have a drink to my health.  :^D

**Comment by Buy-One** [comment]
OK, i'll take a look

**Comment by Javiramallo** [comment]
I did some investigation  for if it help!

![ISSUE 4 - investigation](https://github.com/reaper-oss/sws/assets/19627705/a63857d9-d706-45f4-8b28-5acc2e513524)
![ISSUE 5 - investigation 2](https://github.com/reaper-oss/sws/assets/19627705/3fde4742-4850-4c29-9f42-7750c77fa86a)

**Comment by Buy-One** [comment]
@Javiramallo

Hi

Just updated the script, please try [the new version](https://github.com/Buy-One/REAPER-scripts/blob/main/Envelopes/BuyOne_Select%20points%20of%20envelope%20segment%20under%20mouse%20cursor.lua).

**Comment by Javiramallo** [comment]
Thx a lot. I'll check it deeply and keep you informed!

**Comment by Buy-One** [comment]
Okie dokie. If there're any more issues, please open a ticket in the [issue tracker](https://github.com/Buy-One/REAPER-scripts/issues) of my repo at so that we don't unnecessary clutter SWS issue tracker with unrelated convos.

**Comment by cfillion** [comment]
Closing this since it can be solved by a script.

**Comment by Javiramallo** [comment]
THX
