### ISSUE TITLE
Accessibility: When I use the "Track: View FX chain for master track" action it is not possible to move the plugins up or down in the master track

### ISSUE THREAD

**Issue by Lo-lo78** [reaper-oss/sws#1794]
Hi if I select the master track and do the action:
"Track: View FX chain for current/last touched track"
SWS actions:
"SWS/S&M: Move selected FX up in chain for selected tracks"
""SWS/S&M: Move selected FX down in chain for selected tracks"
They work well.
But if I go to the FX chain of the master track using the action:
"Track: View FX chain for master track"
SWS actions do not move plugins up or down.
This last action of Reaper is very convenient because it does not deselect the track you are working on.
For example:
I'm on track 5 and I make the shortcut connected to the action:
"Track: View FX chain for master track"
and if I exit the FX chain I find myself in the TCP in track 5 and not in the master track.
Is it possible to create various actions where you can move the plugins throughout Reaper's FX chains?
For Monitor FX it's not essential but for track master items and FX containers I think it can help the workflow.
Thank you all for your work!
"

**Comment by cfillion** [comment]
Is the master track selected? If not, you'll need to use "SWS: Select master track" before "SWS/S&M: Move selected FX up/down in chain for selected tracks".

**Comment by Lo-lo78** [comment]
@cfillion 
The action:
"Track: View FX chain for master track"
can't it have two actions that move the plugins up or down only when the FX chain is open?
Thanks anyway for your interest!

**Comment by cfillion** [comment]
Create a custom action containing the following three actions:
- Track: Unselect all tracks
- Track: View FX chain for master track
- SWS: Select master track

Then after running that "SWS/S&M: Move selected FX down in chain for selected tracks" (or up) will take effect on the master track.

**Comment by Lo-lo78** [comment]
@cfillion 
Yes, you can create a custom action. Surely there is no problem with the mouse but I use the keyboard.
The problem is another.
For example:
I'm on track 5, I make the shortcut to go directly to the FX chain, I move the plugin and with the "esc" key I return to track 5.
With the custom action I have the master selected and I lose the selection of track 5.
Yes, I already tried but this was exactly what I wanted to avoid.
That is, losing track selection.
Thank you!

**Comment by Buy-One** [comment]
There're scripts by me2beats available via ReaPack

[me2beats_Save selected tracks.lua](https://github.com/me2beats/reapack/blob/master/Tracks/me2beats_Save%20selected%20tracks.lua)
[me2beats_Restore selected tracks.lua](https://github.com/me2beats/reapack/blob/master/Tracks/me2beats_Restore%20selected%20tracks.lua)

The first can be included in the custom action before the action which selects the Master track. The second can be run manually after managing the Master track FX chain.

**Comment by cfillion** [comment]
There are also ones built-in into SWS:

- SWS: Save current track selection
- SWS: Restore saved track selection

**Comment by Lo-lo78** [comment]
@cfillion 
@Buy-One 
I've tried both solutions and they don't work with custom actions.
With SWS actions we basically emulate the action:
"Track: View FX chain for master track"
Identical effect.
When I open the master's FX chain the plugins don't move and I return to the previously selected track.
With ReaPack actions:
"me2beats_Save selected tracks.lua"
"me2beats_Restore selected tracks.lua"
It does not work well. It always goes to a wrong track and I have to occupy another shortcut in the keymap.
When using the computer keyboard, shortcuts are very important.
My hypothesis is that if the master track is not visible in the TCP the plugins do not move.
This is why the @cfillion proposal is perfect in theory but it doesn't work.
When the action occurs in the custom action:
"SWS: Restore saved track selection"
it's as if the master track is no longer selected and perhaps not visible in the TCP and works exactly like the action:
"Track: View FX chain for current/last touched track"
this keeps the selected track and maybe you don't see the master track in the TCP and it behaves like the custom action?
I think it's harder than I thought!
I'm blind and I don't know if it's a visual issue but certainly if the master track is not selected the plugins in the fx chain don't move.

Sorry for the English.
THANK YOU!

**Comment by cfillion** [comment]
The following custom action works here (tested on Windows w/ SWS 2.13.2 and upcoming 2.14):

1. SWS: Save current track selection
2. Track: Unselect (clear selection of) all tracks
3. Track: View FX chain for master track
4. SWS: Select master track
5. SWS/S&M: Move selected FX down in chain for selected tracks
6. SWS: Restore saved track selection

**Comment by Buy-One** [comment]
>Maybe we can do more with cycle actions?

If shortcuts must be used sparingly, then a step cycle action could be a solution, it will have two states activated with a single shortcut. At its first step it'd save track selection and select the Master track and at its second step it'd restore the original track selection.

**Comment by Lo-lo78** [comment]
@Buy-One 
It's not perfect but the cycle action works:

1. _SWS_SAVESEL; Description: Save current track selection
2. 40297; Description: Track: Unselect (clear selection of) all tracks
3. 40846; Description: Track: View FX chain for master track
4. _SWS_SELMASTER; Description: Select master track
5. !Step; Description: ----- Step -----
6. _SWS_RESTORESEL; Description: Restore saved track selection

It's almost perfect. If I press the escape key to exit the FX chain I have to redo the shortcut to go to the saved track.
The advantage is that I only use one shortcut.
The perfection would be that if I press the escape key it automatically returns to the previously saved track without making the shortcut twice.
Maybe Cockos should create another section for the FX chain for the keymap. This solves everything!
Thanks you are fantastic!

**Comment by Buy-One** [comment]
Depending on your workflow the action **SWS/S&M: Close all FX chain windows** could be added to the second step of the cycle action. This will obviate usage of Esc to close the Master track FX chain, but will close other open FX chain windows as well which could be a disadvantage.

**Comment by Lo-lo78** [comment]
@Buy-One 
yes I know the action and for those who are blind it is very useful with the screen reader when working with those who can see.
Sometimes windows overlap visually and with the screen reader you don't know it. While I work in a track it is possible that the viewer sees other windows.
I try to assign another shortcut and insert this action. Perhaps it will be possible to automate the entire process.
Thank you!

P.S.
How useful would a section for a keymap for the FX Chain be. ;))
Maybe in the future Justin will.

**Comment by Lo-lo78** [comment]
@Buy-One 
It works perfectly!
👍
