### ISSUE TITLE
cycle action editor - apostrophe

### ISSUE THREAD

**Issue by tohubohu38** [reaper-oss/sws#1797]
in the cycle action editor, could you please add the possibility of putting an apostrophe in the title of a cycle action?
 (it's for the langpack)

thanks

**Comment by cfillion** [comment]
Yes, I think that would be OK (but will need to double-check on Windows to be sure). Single and double quotes have special meaning for Windows and SWELL's .ini parser however that is only if at the start and end of the value. This it never the case for cycle action names.

The cycle action editor currently accepts quotes as part of the command name. There does not seem to be a reason to inconsistently disallow them for the cycle action's name.

The limit was added in d5d5f0c6ec8b8c9fd1d61300792bbd30ec69a5f9.

**Comment by tohubohu38** [comment]
thks
how do I test?
where is the sws pre release file please?
thanks

**Comment by cfillion** [comment]
Are you on Windows? If so, try creating a cycle action with these two commands in that order:

![Screen Shot 2023-11-14 at 14 13 32](https://github.com/reaper-oss/sws/assets/4297676/67eabf51-4312-438a-a758-36a954ab8600)

Apply then restart REAPER. Check if the two commands loaded correctly.

In S&M_Cyclaction.ini it should be like this (except for the action number and the action name):
```ini
Action10=Test Cycle|"a'b`c"|40001|
```

If so there shouldn't be a problem allowing those characters in the cycle action names as well.

**Comment by tohubohu38** [comment]
I'm sorry but I don't understand much.
I tested on mac before sending the issue. and not on windows
and it gave me a warning message when I wrote - ...l'enveloppe... -  in the title of a cycle action.

**Comment by cfillion** [comment]
Done, I've checked on Windows and it works fine. There will be builds you can try out in the pull request linked above (in a hour or so).

**Comment by tohubohu38** [comment]
thank you very much
where can I download the build please?
thanks

**Comment by cfillion** [comment]
The download links are in @AppVeyorBot's comment in the pull request #1798.
