### ISSUE TITLE
Feature Request:  > SWS: Toggle Ruler Red When Track(s) Armed For Recording

### ISSUE THREAD

**Issue by DomMcsweeney** [reaper-oss/sws#1813]
Thanks to SWS, there is the Toggle Ruler Red Whilst Recording action - very useful!

Would it be possible to request a similar action for when track(s) are currently armed but not yet recording?

It would help warn and prevent against those cases where one mistakenly records on the wrong tracks, and has to undo, that are out of view from TCP. Especially if mixer is hidden and the tcp/project view is zoomed into just one or two tracks.

Thanks!

ps. I originally posted in the forum, here: https://forum.cockos.com/showthread.php?t=286024

**Comment by Buy-One** [comment]
@DomMcsweeney

Will a script do? The script will have to constantly run in the background to monitor the state.

**Comment by Buy-One** [comment]
Please try this one

>[Color ruler if tracks are record armed.lua](https://github.com/Buy-One/REAPER-scripts/blob/main/Project%20properties/BuyOne_Color%20ruler%20if%20tracks%20are%20record%20armed.lua)

**Comment by Buy-One** [comment]
The thing is that in the original script line 7 (indicated in the error message) is occupied by the script header which is commented out and normally cannot throw any error. Needless to say that on my end this problem doesn't occur.

It's possible that the script was downloaded incorrectly, like an HTML page for example. Please make sure that you use the download button on the script page. If you do and the script still produces the error,  i guess i will need to see your version of the file, the actual code.

**Comment by Buy-One** [comment]
Great!

**Comment by Buy-One** [comment]
No prob, glad it's useful.

**Comment by Buy-One** [comment]
Yes, in this respect in particular the SWS extension is shining. Look for Startup actions in the SWS menu.

**Comment by Buy-One** [comment]
Actually no. REAPER has a kind of under-documented feature of external file which is picked up by the program on startup without  having to be imported into the Action list. It must be named` __startup.lua` (or `__startup.eel` but now it's less relevant) and paced in the root of the `\Scripts` folder.

So to run another script or action on startup using this file it must contain the following code:

`-- between the quotes insert the command ID of a script/native action/custom action/SWS cycle action`
`local COMMAND_ID = "" ` 
`reaper.Main_OnCommand(reaper.NamedCommandLookup(COMMAND_ID), 0)`
