### ISSUE TITLE
TCP track selection status displays incorrectly after running 'Show/Hide in TCP' SWS actions

### ISSUE THREAD

**Issue by robotronald** [reaper-oss/sws#1814]
After running custom actions that contain SWS actions changing TCP visibility (e.g. SWS: Show selected track(s) in TCP) tracks are still showing as selected in the TCP after they have been unselected.

I've attached a gif showing it occurring.

I reported this on the Reaper forums as a bug and @schwaaa replied:
"If this is only happening after running extension functions, it's possible the extension is calling PluginPreventUIRefresh() incorrectly."
https://forum.cockos.com/showthread.php?p=2742160#post2742160

Further info:
Manually running actions to unselect the tracks doesn't correct the display: Track: Unselect (clear selection of) all tracks, SWS: Restore saved track selection, etc. still shows the multiple tracks as selected in the TCP.

This only affects tracks currently visible on screen, if I scroll up or down the other offscreen tracks are showing correctly (unselected)

The TCP track selection display only corrects itself when selecting a new track or forcing a redraw with:
reaper.TrackList_AdjustWindows(false)

Gif attached showing:
1. Running custom action that selects then unselect the tracks (all containing text gr.6. in track name)
2. All 'unselected' tracks still showing as selected
3. Muting only affects the actually selected track, doesn't affect the tracks incorrectly showing as selected.
4. Scrolling up/down shows the offscreen tracks are showing correctly
5. Ctrl clicking another track corrects the problem and track selection status is showing correctly.
![track selection status display bug](https://github.com/reaper-oss/sws/assets/153739889/9f2825f6-4b47-4d29-b870-ca277c04e050)

**Comment by robotronald** [comment]
Just to add - I think that this only started occurring after I updated Reaper to v7 (7.06 x64, Windows 10). Running latest SWS - v2.13.2 pre-release build (January 16, 2023)

**Comment by cfillion** [comment]
What is the exact custom action that duplicates the issue? Is it a custom action or a SWS cycle action? Cycle actions have an option to toggle whether PreventUIRefresh is used, enabled by default. REAPER custom actions don't have that.

"SWS: Show selected track(s) in TCP" does not use `PreventUIRefresh` and does use `TrackList_AdjustWindows`.

**Comment by robotronald** [comment]
It's a custom action. Most of the custom actions have a lot of actions in them but I've recreated it in this one:

Custom: Show ch1
  Script: Lokasenna_Select tracks by name - ch1.lua
  SWS: Show selected track(s) in TCP, hide others
  Track: Unselect (clear selection of) all tracks

It also occurs with:
Custom: UNARM ch1.in
  Script: Lokasenna_Select tracks by name - ch1-loop1.lua
  Xenakios/SWS: Set selected tracks record unarmed
  Track: Unselect (clear selection of) all tracks

I wasn't sure if the lokasenna script might affect it but I removed the SWS actions from each of these custom actions and the problem didn't occur.

**Comment by cfillion** [comment]
Thanks, I've narrowed it down a bit and the issue seems to be on REAPER's side. I've reported it there: https://forum.cockos.com/showthread.php?t=287651.
