### ISSUE TITLE
libgdk is not found

### ISSUE THREAD

**Issue by anwyn** [reaper-oss/sws#1819]
SWS extensions stopped loading with REAPER 7.07 (approx, I skipped some minor versions).
It complains that the symbol gdk_display_get_default can not be resolved.

In  CMakeLists.txt I found:

```
   pkg_search_module(GDK REQUIRED gdk-3.0 gdk-2.0)
    # not linking: REAPER takes care of loading GDK via the SWELL_WANT_LOAD_LIBRARY mechanism
    target_include_directories(sws PRIVATE ${GDK_INCLUDE_DIRS})
```

So REAPER is supposed to resolve it, but it apparently isn't.
If I append `-lgtk-3` to the link command in `build/CMakeFiles/sws.dir/link.txt`, everything works again.

This is REAPER 7.07 x86_64 on Gentoo Linux.

**Comment by cfillion** [comment]
Are you using a custom build of libSwell.so? The stock one provided by REAPER preloads `libgdk-3.so.0`.

To compile SWELL with GDK preloading enabled:

```sh
make PRELOAD_GDK=1
```

**Comment by anwyn** [comment]
OK, that narrows it down. I recently switched to the using the new official reaper-bin package of Gentoo, after using my home-brew ebuild for the last years. I was under the impression that it is just a repackage of the REAPER distribution, but it turns out, the package compiles libSwell. 

So it's a Gentoo problem, not a SWS problem.

Thank you!

**Comment by zx2c4** [comment]
@anwyn You're probably not going to like this... See what happened here: https://github.com/gentoo/gentoo/commit/11e9d2b71083796008f9970f40325a52f144f7ed

Let me know if you have any ideas on it.

**Comment by zx2c4** [comment]
Nevermind, fixed here: https://github.com/gentoo/gentoo/commit/f4f730bc7a927f902c83c01931e02a337ee09706

**Comment by zx2c4** [comment]
Sent upstream here: https://github.com/justinfrankel/WDL/pull/22
