### ISSUE TITLE
SWS LiveConfig monitor window Bug #bug

### ISSUE THREAD

**Issue by DavidsonAudioMulti** [reaper-oss/sws#1831]
With the latest version of Reaper 7 and the SWS extensions 2.13 there is a problem with the live config monitor window saving properly after reloading a project. At fist when using Live configs one can see the preload option by clicking then scroll the mouse wheel to set numbers. Upon re entering a project the live config monitor becomes un responsive to clicks and scroll wheel and saves I think something wrong in the reaper ini file for the monitor window. If I delete this entry in the ini and reload reaper live config monitor window works again for that session. Upon exiting and reopening reaper something is getting overwritten that kills the monitor window insteraction with the mouse.

You must close and reopen reaper for the bug to appear in the LiveConfig monitor.. Window 10 pro 64bit updated to latest windows update.

Can you please fix this I would like to update a live config project but I am fighting this monitor window acting oddly default theme 6.0 
![problemee](https://github.com/reaper-oss/sws/assets/47409222/b2ff24e0-ee79-4ac0-a714-bfc664ae2660)

**Comment by DavidsonAudioMulti** [comment]
Reverting to SWS 2.10 seems to resolve the issue have not tried 2.11 but 2.12 and 2.13 had same issues what could be happening here?

**Comment by cfillion** [comment]
Fixing, thanks!

**Comment by DavidsonAudioMulti** [comment]
Thank you for taking a look! I will give it a try soon.
