### ISSUE TITLE
"SWS/AW: Render tracks to ..." does not exclude muted items.

### ISSUE THREAD

**Issue by cool9-MK** [reaper-oss/sws#1837]
Actions:
SWS/AW: Render tracks to stereo stem tracks, obeying time selection
SWS/AW: Render tracks to mono stem tracks, obeying time selection
does not exclude muted items. After rendering, the sound from the muted items is also present in the final render.

**Comment by cfillion** [comment]
Can't duplicate, muted items are silent in the rendered stem here.

Those actions are just wrappers over REAPER's "Track: Render selected area of tracks to stereo stem tracks (and mute originals)" and "Track: Render selected area of tracks to mono stem tracks (and mute originals)" actions.

If there's some setting or condition where muted items are rendered, it would come from those not SWS.

**Comment by cool9-MK** [comment]
Sorry, there was a mistake on my part. The command is working fine. I should have been more careful.
I apologize for wasting your time.
