### ISSUE TITLE
Copying and pasting/replacing fx chain with video-fx blur fails

### ISSUE THREAD

**Issue by mrndev** [reaper-oss/sws#1857]
copying and pasting fx chain with video fx gaussian blur or the low quality blur fail to syntax error in the blur effect code
<img width="198" alt="image" src="https://github.com/reaper-oss/sws/assets/71446193/ba58f585-f366-4547-890c-575f1e1364e0">
<img width="317" alt="image" src="https://github.com/reaper-oss/sws/assets/71446193/9af6b3cc-9859-4277-88e6-93ade9251818">

leads to 
<img width="430" alt="image" src="https://github.com/reaper-oss/sws/assets/71446193/2c19f670-36d6-4b0d-8a1f-1826777fcbfd">
in the fx code (when trying to save with ctrl-s in the target item

The code is somehow altered on the was which leads to syntax error. The first thing you see is that the blur fx is not working anymore in the target item

**Comment by cfillion** [comment]
Fixing, thanks! Line with unbalanced quotes are being discarded. In the case of those blur presets it's `colorspace=='RGBA' ? "` and `",flag`.

**Comment by mrndev** [comment]
Great - thanks for the quick response!
