### ISSUE TITLE
"Rename sourse file" doesn't work with reverse files

### ISSUE THREAD

**Issue by Bufgil** [reaper-oss/sws#1863]
Hi! I find bug. I have item and enable "Reverse" on it, then when i try to apply "Rename take sourse files" or "Rename takes and sourse files" to it this nothing happens. it would be more comfortable if it worked with reversed files. Thanks!
Reaper v. 7.11/win
![2024-03-27 00-19-36](https://github.com/reaper-oss/sws/assets/165089953/01bb6e1b-b219-4478-997d-af81146501ae)
64

**Comment by cfillion** [comment]
This was fixed in version 2.13. The one on the homepage is extremely outdated. The latest version (2.14.0.1) can be fetched from this page: https://www.sws-extension.org/download/pre-release.

**Comment by Bufgil** [comment]
> This was fixed in version 2.13. The old v2.12 on the homepage is extremely outdated. The latest version (2.14.0.1) can be fetched from [this page](https://www.sws-extension.org/download/pre-release) or via ReaPack.

Thanks, i will try!
