### ISSUE TITLE
"SWS/FNG: Show only used CC lanes" crashes Reaper when the MIDI Editor is empty

### ISSUE THREAD

**Issue by BenTalagan** [reaper-oss/sws#1869]
I'm on MacOS X 13.6.7, Reaper 7.15, SWS v2.14.0.1.

Steps to reproduce : 

- Use one MIDI Editor for whole project / tracks / items
- Create an empty track
- Create an empty MIDI Item
- Open the item in the MIDI Editor
- Delete the item
- The MIDI Editor is now empty
- Launch the action "SWS/FNG: Show only used CC lanes" 
- You died, restart at last bonfire :)

The take validity should probably be checked here (and an error could probably be thrown just like at the line before) : 

https://github.com/reaper-oss/sws/blob/4a37570da2f5535e2ef38ffdef585a87053d8211/Fingers/RprMidiCCLane.cpp#L122

Since this function is used by other actions, this bug probably affects them too.

**Comment by cfillion** [comment]
Nice catch, fixing! I've reviewed all `MIDIEditor_GetTake` call sites, turns out 9 actions are affected by the crash.

(Also, *Contents > Options when using one MIDI editor per project > Close editor when the active media item is deleted in arrange view* has to be disabled.)

**Comment by BenTalagan** [comment]
Thanks, @cfillion !
