### ISSUE TITLE
CF_ExportMediaSource midi file header

### ISSUE THREAD

**Issue by LexaProductions** [reaper-oss/sws#1878]
Hello, 
I'm trying to export a midi file using that function.  It works great but only the Media Source is exported.  With no Tempo and/or markers included in the midi file.  Is there any way to get those included?

Thanks for you time.

**Comment by cfillion** [comment]
That function is a wrapper for REAPER's functionality. It should behave the same as the "File: Export contents as .MID" MIDI Editor action.
