### ISSUE TITLE
NF_Get/SetSWSTrackNotes don't throw Lua error when track is invalid

### ISSUE THREAD

**Issue by Buy-One** [reaper-oss/sws#1881]
NF_SetSWSTrackNotes crashes REAPER instead.

NF_GetSWSTrackNotes doesn't crash REAPER.

REAPER 7.18, Windows 7 x64

**Comment by cfillion** [comment]
Fixing the crash. The no-error part is normal for extension-provided functions.

**Comment by Buy-One** [comment]
Thank you
