### ISSUE TITLE
Update website with stable build

### ISSUE THREAD

**Issue by njelich** [reaper-oss/sws#1884]
According to this release:

https://github.com/reaper-oss/sws/releases/tag/v2.13.2.1

The 2.13.2 has been branded as stable, yet the sws website still displays the 2.12.1 as stable, despite being 3 years old.|

https://www.sws-extension.org/whatsnew.php

Should this be updated?

![Screenshot 2024-07-31 at 17 13 27](https://github.com/user-attachments/assets/f069e2e2-c521-4b63-90c6-fcb3bfcbb8ba)

**Comment by cfillion** [comment]
Yes, it should. v2.12 is obsolete. Still waiting on @swstim to take care of that.

**Comment by njelich** [comment]
Any way I can help? It seems like the web is in this repo:

https://github.com/reaper-oss/sws-web

**Comment by cfillion** [comment]
🎉
