### ISSUE TITLE
feature request : extend FX number beyond 8 for all the SWS/S&M toggle bypass / bypass / unbypass fx (number) for selected tracks actions

### ISSUE THREAD

**Issue by djabthrash** [reaper-oss/sws#1893]
Hi !

Now in Reaper we have the following type of actions, but they are limited to FX number 1 to 8 : 

SWS/S&M: Toggle FX 1 bypass for selected tracks
SWS/S&M: Bypass FX 1 for selected tracks
SWS/S&M: Unbypass FX 1 for selected tracks
etc (any "SWS/S&M: (...) FX (...) selected tracks" type of actions really)

Since i use more than 8 FX on my tracks, I'd also need to have these actions to go beyond FX number 8.
Being able to go to at least FX number 16 would be a gamechanger for me, because i use custom actions to toggle bypass / bypass / unbypass certain combinations of FXs on selected tracks, using the type of actions listed above.

I'd need to also be able to use actions like :

SWS/S&M: Toggle FX 13 bypass for selected tracks
SWS/S&M: Bypass FX 13 for selected tracks
SWS/S&M: Unbypass FX 13 for selected tracks

etc

This would be a gamechanger for me actually !

Thanks !

**Comment by cfillion** [comment]
The amount of these actions is user-configurable via the S&M.ini file (Options > Show REAPER resource path in explorer/finder). Edit these lines while REAPER is closed:

```ini
S&M_FXBYP=8                              ; [Main] Toggle FX n bypass for selected tracks
S&M_FXBYP_SETOFF=8                       ; [Main] Unbypass FX n for selected tracks
S&M_FXBYP_SETON=8                        ; [Main] Bypass FX n for selected tracks
```

**Comment by djabthrash** [comment]
@cfillion : thanks a ton !

I had no clue i could do that (i was searching for a script for these actions and didn't know there was this .ini file somewhere that i could edit).

I just edited the .ini file, bascially replacing all the "=8" by "=16", and it worked like a charm.

Thanks a ton !

Now on my way to make a little donation to SWS :)
