### ISSUE TITLE
NF_AnalyzeTakeLoudness_IntegratedOnly Function Returns Incorrect LUFS Values in SWS 2.14, compared to 2.12.1.3.

### ISSUE THREAD

**Issue by MartinBTelus** [reaper-oss/sws#1898]
I have a LUA that adjusts item gain based on LUFS. Updated to SWS 2.14 this morning and the reported LUFS values were inconsistent with other tools, whereas previous they were the same. Reports approx 3dB louder than actual. Reverting to SWS 2.12.1.3 fixed the issue. Windows 64bit.

**Comment by nofishonfriday** [comment]
Is this with mono items (only)?
In SWS v2.13 (the version after vv2.12.1.3) dual mono scanning mode was introduced.
When enabled this scans mono items 3 dB louder, also when scanning via script, as in your case.
So my guess is maybe you have dual mono scanning mode enabled?
You can check via actions > SWS/BR/NF: Toggle use dual mono mode (for mono takes/channel modes) for loudness analyzing
or via the Loudness window (action: SWS/BR: Analyze loudness...) > Options > Use dual mono mode...

**Comment by MartinBTelus** [comment]
Ah, thank you so much. Changing the option fixed the issue for me. Very much appreciated!
