### ISSUE TITLE
Some GUI tweaks needed on Snapshots window in this case

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#21]
_From [mario.kr...@gmail.com](https://code.google.com/u/102406584402060217289/) on November 09, 2009 12:00:32_

What steps will reproduce the problem? 1. Dock the Snapshot window
2. Select Mixer view
3. Decrease the height of the Mixer view
4. Go back to Snapshot window What is the expected output? What do you see instead? EXPECTED: something like this: http://www.imagesforme.com/show.php/779179_Clipboard02.png INSTEAD: http://www.imagesforme.com/show.php/779123_Clipboard01.png What version of SWS extension are you using? (Extensions -> About SWS...)

Latest. What Reaper version #? Latest.

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=21_

**Comment by swstim** [comment]
I think this is fixed.
