### ISSUE TITLE
import/export marker list (as file)

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#213]
_From [nofishonfriday](https://code.google.com/u/nofishonfriday/) on November 17, 2010 12:59:44_

I'd like to have a "import/export" markerlist function.

Reason is, I'm working on the same project on two different computers and would like an easy way to transfer the current marker list to the project on the other computer.

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=213_

**Comment by X-Raym** [comment]
@swstim Done within SWS as _SWS: Export formatted marker list to file_
