### ISSUE TITLE
Add/move Marker Goes up to 30

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#255]
_From [greg.so...@gmail.com](https://code.google.com/u/115091438113147976777/) on February 07, 2011 19:15:46_

I could really use the add\move mrker actions going past 10 (up to 30?). This would be a great help for some macros I use that auto insert markers.  Only adding markers up to 10 limits things or adds complications to certain tyoes of macros.

thanks

g

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=255_

**Comment by X-Raym** [comment]
@swstim Can be customized in SWS.ini file
`S&M_GOTO_MARKER=0                        ; [Main] Go to marker n (obeys smooth seek)`
