### ISSUE TITLE
SWS item notes: remember formatting. 

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#303]
_From [pixeltar...@gmail.com](https://code.google.com/u/105056840015445761492/) on June 04, 2011 12:31:31_

Useful info: I'm on a mac (osx 10.7)

so I was like so insanely happy when I found sws notes and started using it. 
today I was even more happy when I right clicked some text to find that you can go to "font>show fonts" and edit it proper. 

if I go to "track notes" and then back to "project notes" it doesn't retain the color or multiple sizes of text. 

it would be freaking awesome if it could do so! 

I mean not that it's not freaking awesome now, but it would be even more awesome. like. awesomezilla.

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=303_

**Comment by cfillion** [comment]
Formatting in text boxes was a REAPER issue that was fixed in justinfrankel/WDL@55199fca0cddaa93e6db0b10fc3597bc31318c8e. Text boxes no longer support rich text on macOS.
