### ISSUE TITLE
SWS: Wait for next bar/beat - crashes on OSX

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#394]
_From [avuol...@gmail.com](https://code.google.com/u/109262143732144733707/) on October 08, 2011 23:37:25_

Yeah, using either one of those actions when playing back a project is causing Reaper to freeze.

What version of SWS extension are you using? (Extensions -> About SWS...)

2.1.0 build #1

Reaper 4.03pre7a & Reaper 4.11pre2 i386

OSX 10.5.8

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=394_

**Comment by estrica2000** [comment]
any chance to have this back?
