### ISSUE TITLE
Rename takes and sources overwrites other files in folder

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#407]
_From [sergioar...@gmail.com](https://code.google.com/u/114349142085426040966/) on November 01, 2011 23:41:28_

What steps will reproduce the problem? Rename an item using "Rename takes and source files" command. What is the expected output? What do you see instead? Renaming the items WITHOUT overwriting others with the same names. A prompt would be nice to ask if they should be overwritten. 

What version of SWS extension are you using? (Extensions -> About SWS...)
2.1.0 build#1 What is your Reaper version number and CPU architecture (e.g. Reaper 3.75 x64)? 4.10 x86 What operating system are you running?  (e.g. Windows XP/7, OSX 10.5.8 etc, 64bit?) W7

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=407_

**Comment by Breeder** [comment]
Bump - came across this one today, it would indeed be nice to have that prompt asking for overwrite/cancel rename operation

**Comment by nofishonfriday** [comment]
@Breeder
Looking into it currently, but I don't quite understand the report, as there can't be more than one file with the exact same name in the same folder (to my knowledge).
So could you elaborate what exactly the issue is here?

**Comment by Breeder** [comment]
> @Breeder
> Looking into it currently, but I don't quite understand the report, as there can't be more than one file with the exact same name in the same folder (to my knowledge).
> So could you elaborate what exactly the issue is here?

It's been a while but I think the bug went this like:

If you have two files called:
file1.wav
file2.wav

And you use this function to rename file1.wav to file2.wav the function will simply overwrite existing file file2.wav and put file1.wav in its place but with a new name file2.wav and effectively losing original file2.wav.
