### ISSUE TITLE
Toggle Marker Lines

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#437]
_From [secret...@gmail.com](https://code.google.com/u/107564163892032195898/) on December 22, 2011 08:36:42_

Is it possible to include an action to toggle the display of marker lines?

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=437_

**Comment by X-Raym** [comment]
@swstim Bets solution for that is Heda's script:
[Regions&Markers from Items ··· HeDaScripts for REAPER ··· |](https://reaper.hector-corcin.com/app/regionsmarkers-items)

Also, there is SWS markers sets.

This can be close, IMHO.

**Comment by swstim** [comment]
I think this issue is actually referencing the "Marker Line Z Order" setting which I don't see in Heda's scripts.

**Comment by nofishonfriday** [comment]
Meanwhile there where actions added: _SWS/BR: Options - Set marker line Z order to ..._
