### ISSUE TITLE
Snapshot does not recall Phase Invert/reverse

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#455]
_From [peterric...@earthlink.net](https://code.google.com/u/112722212405206849793/) on February 29, 2012 19:45:39_

What steps will reproduce the problem? Using full track mix setting, the phase invert setting does not import to another songfile What is the expected output? What do you see instead? What version of SWS extension are you using? (Extensions -> About SWS...)

2.1.0 What is your Reaper version number and CPU architecture (e.g. Reaper 3.75 x64)? Reaper 4.0 x32 What operating system are you running?  (e.g. Windows XP/7, OSX 10.5.8 etc, 64bit?) Windows XP SP3

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=455_

**Comment by reaperblog** [comment]
2019, phase/polarity still not saved with snapshots
