### ISSUE TITLE
SWS: Analyze and display peak and RMS: add button to move cursor to peak location

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#501]
_From [cmascot...@gmail.com](https://code.google.com/u/114279255517175139266/) on August 10, 2012 21:16:31_

SWS: Analyze and display peak and RMS

Would it be possible to add a button to the results dialog box that would move the cursor to the peak location?  I realize that there is another action (the name escapes me) that does this, but adding a button to the results dialog box would:
- be quicker and more convenient
- would avoid having to analyze the item twice (once for each action)

I wouldn't recommend automatically (without user request) moving the cursor in this action: someone would probably be upset about losing his cursor position.

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=501_

**Comment by nofishonfriday** [comment]
Can be done via scripting meanwhile, NF_GetMediaItemMaxPeakAndMaxPeakPos()
