### ISSUE TITLE
Action : Set time selection to items without move of edit cursor

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#502]
_From [vientemu...@gmail.com](https://code.google.com/u/112447891539929936047/) on August 13, 2012 23:18:43_

I badly need this action. In current behaviour when i set time selection to items it also move edit cursor to beginning of the item. Would be nice to have such action without moving of edit cursor. Im sure others can find it useful as well. For example to be able to select item and time selection at the same time and still place your cursor to any part of the item.

Thanks!

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=502_

**Comment by X-Raym** [comment]
@swstim This can done via custom action, or with scripting.
