### ISSUE TITLE
Triplet grid toggle action for MIDI editor

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#514]
_From [avuol...@gmail.com](https://code.google.com/u/109262143732144733707/) on September 16, 2012 20:24:24_

We have this for the arrange view. Could we also have this for the MIDI editor. It would save a lot of mousing around! Thanks.

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=514_

**Comment by mkruselj** [comment]
@nofishonfriday - care to add an action to toggle swing grid that would mirror its state on the toolbar? Seems that native action doesn't really play well when grids are linked between arrange and MIDI editor.

(Perhaps another such action for arrange is needed, similar to Adam Wathan's toggle grid actions?)

Thanks!

**Comment by nofishonfriday** [comment]
added in v2.9.3
