### ISSUE TITLE
'reset mix' action (low priority)

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#521]
_From [nofishonfriday](https://code.google.com/u/nofishonfriday/) on October 05, 2012 15:20:19_

Sometimes when wanting to mix a already mixed/tweaked project again from scratch I think it would be handy to have a 'reset mix' action.

This action is probably a combination of already present actions, so of course one could do a macro, so it's not a super-important FR, just thought maybe it would be nice to have as 'native' SWS action.
This action does:
- reset volume and pan on all tracks
- delete all FX plugins (VSTi's shoudn't be deleted probably)
- delete automation
- delete all sends
  (- maybe I forgot something but you got the idea)

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=521_

**Comment by nofishonfriday** [comment]
While going through old issues I come across stuff I don't even remember having opened. :P
This is suffuciently done for me with a [custom action + scripts](https://forum.cockos.com/showpost.php?p=1475621&postcount=14).
