### ISSUE TITLE
Actions for quantize values, so that you can set/change quantize on the fly.

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#53]
_From [jonespn...@gmail.com](https://code.google.com/u/112192908096563077693/) on January 31, 2010 01:31:18_

It would be nice to have actions to set track quantize on as well as set
the values (8th, 16th, ect.) and maybe CC actions to control the strength,
swing, ect.
Thanks.

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=53_

**Comment by X-Raym** [comment]
@swstim This could be closed. Actions like _Track: Set MIDI input quantize to 1/4 for all tracks_ already exists.
