### ISSUE TITLE
sends envelopes not recalled correctly with snapshots

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#537]
_From [nofishonfriday](https://code.google.com/u/nofishonfriday/) on December 09, 2012 18:31:33_

What steps will reproduce the problem? see attached example project
it contains one snapshot with send automation, which was saved with the send automated (exactly as you see it when you open the project)
now recall this snapshot, send automation is gone (envelope is at 0db)

What version of SWS extension are you using? (Extensions -> About SWS...)

2.3.0 #4 What is your Reaper version number and CPU architecture (e.g. Reaper 3.75 x64)? 4.32 RC1 What operating system are you running?  (e.g. Windows XP/7, OSX 10.5.8 etc, 64bit?) WinXP32 SP3

**Attachment:** [snapshots send automation bug test.RPP](http://code.google.com/p/sws-extension/issues/detail?id=537)

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=537_

**Comment by nofishonfriday** [comment]
I had a look into this issue and came up with a a rather 'naive' approach using Jeffos' ChunkParserPatcher which so far with simple testing it looks like it may work, but I'm thinking from the comments here it's probably not as straightforward as I'm assuming...

Test:
![snapshots](https://user-images.githubusercontent.com/7658194/37870325-2f155766-2fcb-11e8-8666-48ab9e82e2dd.gif)

@devs
Here's the patch:
https://github.com/nofishonfriday/sws/commit/e59f34e3f3ed854e40589d6d2fc40f3981e14bf7
Would like to hear your thoughts on this...

**Comment by swstim** [comment]
Wow, that is a really simple patch....  My first instinct is it can't be that simple, but I haven't checked it out yet. :)  Looks like you add at most one send per track as you moved the m_sends.Add out of the loops.  Does that work when restoring complicated routing snapshots?   I will have a chance to dig in later but wanted you to know I had a first glance.

**Comment by nofishonfriday** [comment]
Thanks for looking into it, appreciated.
Would be nice if we could finally squash this bugger. :)

>  Looks like you add at most one send per track as you moved the m_sends.Add out of the loops
Hm, now you got me wondering...

My understanding is that what it does in the loops is iterating through each track send, find the destination track and store the relevant "AUXRECV... chunk bit (and now also the env. points).

As for every send there's only one receive chunk (?) I'd think it should work this way, but you may know better as you've coded it originally I assume, no ?
Anyway, maybe I test the wrong scenarios but couldn't break it here so far.

Even if it's not 100% foolproof it may at least be an improvement to before where the send env's completely vanished when recalling a snapshot ?

Curious about your findings when you have a chance to dig in. :)
