### ISSUE TITLE
Snapshot crash with renamed/moved FX

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#559]
_From [jeffos...@gmail.com](https://code.google.com/u/117694019867148365119/) on April 04, 2013 12:40:10_

From http://forum.cockos.com/showpost.php?p=1148981&postcount=1234 ______________

another quick snapshot bug is that if you rename an effect (AFTER you have saved the snapshot) and then move it in the chain. If you then this earlier snapshot it seems to crash/freeze reaper. It all works fine if you don't rename the effect.

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=559_

**Comment by swstim** [comment]
Can't reproduce.
