### ISSUE TITLE
Grid actions for MIDI Editor

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#579]
_From [avuol...@gmail.com](https://code.google.com/u/109262143732144733707/) on May 28, 2013 00:04:45_

In addition to the default actions for setting the grid size in arrange, there are SWS/AW actions for setting the grid size. 

The advantage of these actions is that you can use them as toolbar buttons and the button "pressed" status indicates the current grid setting.

I'd like to ask for these to be implemented for the MIDI Editor too, along with the Triplet and Dotted note toggle actions.

Cheers!

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=579_

**Comment by X-Raym** [comment]
@swstim This is now native REAPER. Can be close.

Also, SWS/AW grid actions can deleted from SWS now. Pressing SWS/AW grid action on a toolbar doesn't update native grid buttons unless play is pressed, so rather than fixing, as they already exist in REAPER now...
