### ISSUE TITLE
sws_2.4.0.2.dmg not working here

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#609]
_From [santiago...@gmail.com](https://code.google.com/u/108537761558323166531/) on November 16, 2013 20:16:40_

What steps will reproduce the problem? Installer failes What is the expected output? What do you see instead? Terminal 80x24

Last login: Sat Nov 16 15:59:15 on ttys000
/Volumes/SWS_Extension/reaper_sws.dylib ; exit;
Mac-Pro:~ xecozz$ /Volumes/SWS_Extension/reaper_sws.dylib ; exit;
-bash: /Volumes/SWS_Extension/reaper_sws.dylib: cannot execute binary file
logout

[Proceso completado]

What version of SWS extension are you using? (Extensions -> About SWS...)
2.4.0.1 What is your Reaper version number and CPU architecture (e.g. Reaper 3.75 x64)? 4.56 x 32 What operating system are you running?  (e.g. Windows XP/7, OSX 10.5.8 etc, 64bit?) OSX 10,6,8

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=609_

**Comment by jillii** [comment]
Where is Install.command found? I am having this issue 1 year later :{
