### ISSUE TITLE
Focus Main Window via KEY is Broken

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#624]
_From [andivax2...@gmail.com](https://code.google.com/u/108837015477180461326/) on February 06, 2014 17:45:17_

subj
SWS Focus Main main window or Focus Main window (close others) doesn't work when i bind it on keyboard key. If i RUN it via Actions button "RUN" all works good.

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=624_

**Comment by Boone777** [comment]
It works if I use Command key in my macro
