### ISSUE TITLE
SubRip SRT enhancements

### ISSUE THREAD

**Issue by Jeff0S** [reaper-oss/sws#639]
_From [extremr...@yahoo.fr](https://code.google.com/u/104016236531233509923/) on April 03, 2014 12:14:39_

Hi !

i already writte a whole post on Cockos forum but i didn't writte at the good place. But please let me show you that post : http://forum.cockos.com/showpost.php?p=1336289&postcount=1514 . That post has colors and screenshots, i think it will be far me pleasing to read :P

In summary there is three ideas :
1. Regions to Regions Subtitles
   The habilty to convert regions names to regions subtitles (preserving regions names)
2. Merge regions with same name (preserving subtitles)
   If regions with same name could be merged, while preserving subtitles information, it could be perfect
3. Region names after SubRip SRT importation
   When importing SubRip SRT file, the regions names are not very handy (it is just an index). Regions named with regions subtitles will be perfect.

Once again, i encrouage you to show my post on Cockos forum, more detailed and with pictures to illustrates my need and desires.

Thanks ! :)

_Original issue: http://code.google.com/p/sws-extension/issues/detail?id=639_

**Comment by X-Raym** [comment]
Consider feature request 2 and 3  as done (see my EEL directory on github for these !)
1 as a workarround in eel too :P
