### ISSUE TITLE
Feature Request : Global Startup Action

### ISSUE THREAD

**Issue by Claudiohbsantos** [reaper-oss/sws#707]
Hi. First of all thanks for the great extension. It's hard to imagine reaper without SWS now. 

I wanted to ask if it would be possible to create a Global Startup action like the current Project Startup Action, but one that would be executed in every and any project that was opened. 

I think it would be very useful in two levels:
1. It is a great way to do basic action such as deselect, unarm, collapse,... basically tidying up the mess that we probably left the project when we last closed. 
2. More powerful and useful: Now that defered scripts are getting more and more powerful, it would be incredible to be able to initialize all of them automatically on project opening. That prevents the user from forgetting to initialize one.  

Even if the feature only allowed for a single action to be set as startup action that wouldn't be a problem since Custom actions containing all the necessary sub actions could be created and set. 

Sorry if this is already possible in any way. Wouldn't be the first time I found I missed an action or feature. 

Thanks
Claudio
(Claudiohbsantos in the forums)

**Comment by Breeder** [comment]
I personally have one custom action set as project startup action in the default project template  - so it works pretty much like global startup action (add something to that custom action, all projects will "inherit it")

But I agree that one global startup action that works no matter the project would be nice, will look into it...
I also always wanted some kind of "project close action"...so this might be the time to investigate if it's possible :)

**Comment by Claudiohbsantos** [comment]
Yeah, that seems like a good way of doing it for now. And a closing action
would be great! I can immediately think of quite a few uses for it.

Thanks

**Comment by Breeder** [comment]
I'm not sure when I will find the time for this, so removing assignment

**Comment by nofishonfriday** [comment]
Implemented, can be closed.

**Comment by Claudiohbsantos** [comment]
True, forgot this was here. Thanks a lot, It has been  very useful
