### ISSUE TITLE
FR: Show hide track envelope for every parametr.

### ISSUE THREAD

**Issue by nounaim** [reaper-oss/sws#712]
Hi). Please add if it possible command which shows envelope for last touched fx parametrs, last touched bypass & dry/wet fx knob.

**Comment by nounaim** [comment]
Sorry, I noticed that action  work now also for bypass & dry/wet knob in R5, maybe it was a bug

**Comment by nofishonfriday** [comment]
As said by OP, this is implemented natively meanwhile.
