### ISSUE TITLE
SWS/wol adjust selected envelope height (midi CC/mousewheel) 

### ISSUE THREAD

**Issue by nounaim** [reaper-oss/sws#716]
This action with mouse sometimes just scroll track view, and doesn`t change track/envelope height, & also SWS/wol adjust selected envelope or last touched track height (midi CC/mousewheel). 
I saw it in reaper 5pre28/x64+sws2.6.5 & reaper 4.77x64/sws2.6.0
Please fix it or add action for change heights for tracks & envelopes heights under mouse cursor.
![swsbug2-2](https://cloud.githubusercontent.com/assets/8280029/7469299/ded5fe6e-f322-11e4-92bd-121942e848a9.gif)

**Comment by nounaim** [comment]
its good, thanks!!!

**Comment by wolqws** [comment]
Close?
