### ISSUE TITLE
FR: Set track channels of selected tracks to 2/4/8/16

### ISSUE THREAD

**Issue by ThoughtPhotography** [reaper-oss/sws#730]
So I have a project with 150+ tracks, and for some reason each track was set to 8 track channels.
I don't know if Reaper needs extra resources for multi-channel tracks, but when I went to put them all back to 2, there didn't seem to be anyway to do multiple tracks at once.

I had to manually open 150 track routing windows from the mixer which was VERY time consuming.

It would be nice if there was an SWS action for setting the number of track channels of selected tracks. Actions to set to 2/4/8 or 16 channels would probably be sufficient for most people (an action to set to stereo or 4 channels is all I'd need).

thanks

**Comment by X-Raym** [comment]
This could be done with natively interpreted scripts :) What version of REAPER do you use ?

**Comment by X-Raym** [comment]
Of course when I finish it I realize that it was already there... --'
Look for the action SWS:Open console with "| " to set channel #
You will just have to set the number and it will be good.

**Comment by ThoughtPhotography** [comment]
Thanks! Strange that I didn't find it before.

**Comment by X-Raym** [comment]
Don't worry I script a whole script before finding that number was called #... Maybe we can request a rename for this action ?

**Comment by X-Raym** [comment]
@swstim This can be closed.
