### ISSUE TITLE
Action request: Duplicate all in time selection

### ISSUE THREAD

**Issue by nounaim** [reaper-oss/sws#736]
Ability to duplicate all in time selection with all envelopes points may would be comfortable i think, would not need to create regions or an empty item on the tracks with automation,for copy the points,
![duplicate2](https://cloud.githubusercontent.com/assets/8280029/8270979/3da2e544-1810-11e5-8d41-4e17dbd1bd0d.gif)

**Comment by nofishonfriday** [comment]
There's now a script available in [ReaPack](https://reapack.com/) which does this:

[Area selection - Duplicate items and automation in time selection of selected tracks to edit cursor](https://forum.cockos.com/showpost.php?p=1863415&postcount=28)

**Comment by nofishonfriday** [comment]
closing as 'implemented via script'
