### ISSUE TITLE
Actions for show/hide or toggle take envelopes (pan,vol,pitch)

### ISSUE THREAD

**Issue by nounaim** [reaper-oss/sws#751]
For change that  in a  take envelopes dialog window, but not for disabling envelope ,please

**Comment by nofishonfriday** [comment]
Added in v2.10.0

> - SWS/S&M: Show/Hide take ... envelope, SWS/S&M: Toggle show take ... envelope (unlike the native "Take: Toggle take ... envelope" actions these change visibility only)
