### ISSUE TITLE
S&M Warning - Playlist contains nested markers!

### ISSUE THREAD

**Issue by michail03** [reaper-oss/sws#758]
Ok, here is the problem. I got region 1 & region 2 with marker inside region 1. When I hit Play button in S&M Region Playlist or when I moving to another region in Playlist with arrow keys and hit Enter - Reaper shows 

S&M Warning - The Playlist #1 might not work as expected. It contains nested markers/regions (inside region 1 at least).

What's the problem? It WORKS as expected! I use Region playlist in live performance, and I don't need this annoying message. Bug?

**Comment by Jeff0S** [comment]
Thank you for the report. I see the prob but I would like to double-check something: please, can you attach (or link) an example project? (no media files needed, just the RPP file).
Thank you in advance!

**Comment by michail03** [comment]
How can I attach file into this forum?

**Comment by Jeff0S** [comment]
Don't bother uploading a project michail03, that isn't needed.
I see the prob, this isn't a bug actually, there is a real issue behind the scene when you have markers within regions (potential bug = unexpected "jumps"). REAPER would need a slight update to make it safe, I'll see if I can do it. Keep on eye on this issue (and do not nest markers for the time being)...

**Comment by oe2-j** [comment]
Any update on this, @Jeff0S? I've just come across a problem of this category for the first time and it is rather odd. (Also, I could've sworn it wasn't a problem in the past. But maybe it was. :)

In my limited tests, nested markers cause the play cursor to smooth seek from one region in the playlist to the nest. Bizarre.

Thanks!

**Comment by MauricDaniel** [comment]
This is still a problem, and frankly makes the Region Playlist useless.
It should be fixed or the Region Playlist should be removed from the project to prevent others wasting time and stumbling here.
#814 is also related.

**Comment by filipesantosind** [comment]
Eight years later and the problem remains. It's a shame, the Region Playlist is a great tool.
