### ISSUE TITLE
Action for removing bypassed and/or offline FX from track

### ISSUE THREAD

**Issue by highvoltaged** [reaper-oss/sws#767]
Title pretty much sums it up.
It would be a tremendous help to have a shortcut that removes bypassed and/or offline FX.

It would be great to use before archiving tracks, because if you set all fx offline, and you already had offline FX, you wont know which one was active at the time of archiving, thus bringing back all the FX online.
Not to mention it could clean up channels nicely.

**Comment by ThoughtPhotography** [comment]
This sounds useful. :) I'd only suggest making the action for "selected tracks", that way a single track, or the entire mixer at once could be done with the same action.

**Comment by highvoltaged** [comment]
Yes, i forgot to write that!

**Comment by nofishonfriday** [comment]
Meanwhile there's a script doing this:
mpl_Delete bypassed and offline fx from selected tracks-lua

Available via ReaPack or [here](https://raw.githubusercontent.com/MichaelPilyavskiy/ReaScripts/master/FX/mpl_Delete%20bypassed%20and%20offline%20fx%20from%20selected%20tracks.lua).

**Comment by highvoltaged** [comment]
Wow, thanks this is great!

**Comment by swstim** [comment]
Closing due to ReaPack functionality.
