### ISSUE TITLE
Bug: Stretch Marker Mouse Context and Strech Marker Display with 5.04 pre 1 Update

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#771]
I'm afraid that with the last pre-release (5.04 pre1), the great updates on stretch markers broke the Get Stretch Marker Under Mouse Context... =/
It does work horizontally (where the markers are) but not vertically (we have to put the mouse where their original vertical position was, even if they are above or below).

**Comment by Breeder** [comment]
That sucks...more reverse engineering of pixels -_- Not really sure when I will have the time for that...let pre cycle first finish to see where it ends up

**Comment by daxliniere** [comment]
Hey guys, any news on this?

**Comment by daxliniere** [comment]
@Jeff0S , I've spoken with Breeder and he is no longer able to work on this. With your knowledge of and access to the _inside_ of REAPER, are you able to get this working, please? It's a very useful part of SWS and it's killing me that scripts crucial to my workflow no longer work because of this.

**Comment by daxliniere** [comment]
Honestly, I'd much prefer to go back to the old stretch marker system. I really hate the cluttered views and who ever needs rate transitions anyway? I can't imagine anything they're useful for and I've been editing audio for 20 years.
The handles are also impossible to grab when there's a volume envelope over the item set to 0dB. You actually have to hide the envelope first.

Plus, you have to reach for different places when adjusting them. That SUCKS for workflow.

I'm sure there's a better place for this conversation, I'm just not sure where it is. Please advise.

**Comment by daxliniere** [comment]
Hello? Is anyone here anymore?

**Comment by jalovatt** [comment]
Bump, not it that it helps.

**Comment by swstim** [comment]
Hey now, no need to be cranky.  I'll take a look next time I build.

**Comment by jalovatt** [comment]
Sorry, it's just been a year and a half since the thread was opened and I didn't think anyone was actively maintaining SWS anymore.

**Comment by X-Raym** [comment]
@swstim 
Thanks ! Javolatt made some [suggestions](http://forum.cockos.com/showpost.php?p=1805528&postcount=2234) about how to solve it, maybe it can help.

**Comment by swstim** [comment]
FYI the bump does help - the list of bugs here is prohibitively long and it's good to know what people are hitting their heads against.  I need to get an update out soon as it's been WAY too long.

**Comment by X-Raym** [comment]
@swstim Indeed, reports and FR list is long, but some issues could be closed because they are already solves like this one : https://github.com/reaper-oss/sws/issues/350

Reviewing all 11 pages of FR to check if it need to be closed, add BUG or FR labels, or tells that it can be scripted and doesn't need to be included right in SWS can be a bit boring, for sure. But maybe some people can help ?

**Comment by daxliniere** [comment]
@swstim Thanks Tim, that's super-exciting to hear you're willing to put some time into this.

This sounds like a great solution, if it will work: "Remove the y-check entirely and just see if the mouse is within STRETCH_M_HIT_POINT of a stretch marker horizontally."

**Comment by daxliniere** [comment]
@X-Raym, great idea to do a cull. Normally I would love to help with this, but I'm neck-deep in building the studio complex in London at the moment.

**Comment by swstim** [comment]
OK - I've removed the Y hit logic per Lokasenna's suggestion [here](http://forum.cockos.com/showpost.php?p=1805528&postcount=2234) and daxliniere's agreement above.  I will leave this open to maybe someday update the logic to account for actual stretch marker logic or other issues that crop up because of this change.

**Comment by daxliniere** [comment]
Thank you SO MUCH Tim! I'll test this tomorrow and let you know how it goes.
(Perfect timing as I have a drum editing session tomorrow.)

**Comment by X-Raym** [comment]
Cool ! My Reset stretch marker under mouse may be usable again ! :P

**Comment by daxliniere** [comment]
## **OMFG!!** Raymond's script _Snap stretch marker under mouse to closest grid line_ works again!!!!
I'm so happy!!

**Comment by X-Raym** [comment]
@daxliniere At last 🎉 👍 
@swstim Thanks 📦 
Closed because fix here : https://github.com/reaper-oss/sws/commit/dbae5b93b58595a0c87796aaffe52691f03c5551
