### ISSUE TITLE
SWS will not install

### ISSUE THREAD

**Issue by patautrey** [reaper-oss/sws#776]
just installed windows 10, but now i can't get the update to install

**Comment by Jeff0S** [comment]
It's a bit vague, and smells like an user error (no such reports on Win10), sorry... Are you sure you have downloaded the proper 64 or 32-bit version? Are you pointing at the correct installation path in the installer? Well, what is happening exactly?

**Comment by patautrey** [comment]
When I attempt to install, this is the error window I get - and I am sure I
selected the correct version


[image: Inline image 1]

**Comment by Jeff0S** [comment]
I can't see the screenshot, can you please upload this image (on the reaper stash for ex., http://stash.reaper.fm)?

**Comment by patautrey** [comment]
i am unable to upload there - do you have a different email i can send the
screenshot to?
