### ISSUE TITLE
API FR: Encode/Decode Base64

### ISSUE THREAD

**Issue by MichaelPilyavskiy** [reaper-oss/sws#778]
At least plugin routing it holds.
I`m writing GUI for FX chain, and seems LUA cant decode base64 to hex (and back, I guess) properly.
http://forum.cockos.com/showthread.php?t=168478

**Comment by mespotine** [comment]
+1 on this one. I have written myself a encoder/decoder in Lua but it's extremly slow on huge strings(due a lot of concatenation needed) so native functions to do it would be great.

And as in some areas Reaper uses hexstrings, I would like to ask for Ascii2Hex and Hex2Ascii-functions as well, who convert a string into their hex-counterparts and reverse.
(I have them coded in Lua as well but...they have the same problem being too slow on huge string due some of Lua's design decisions.)

Thnx :)

**Comment by nofishonfriday** [comment]
@cfillion What do you think about exposing the WDL Base64 functions to ReaScript?
https://github.com/justinfrankel/WDL/blob/4acb00d6298047cbb4b82f67a0ea632e23b7a77f/WDL/wdl_base64.h
