### ISSUE TITLE
(FR) API: Get Item Max Peak and Average RMS Level

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#781]
Hi,

SWS is capable of analyzing items and determine what is it's Max Peak level, and what is it's Average RMS level. This function is use in the SWS label processor and in the Organize Items by Peak/RMS actions.

It could be nice if we could get this value from ReaScript, with two functions like this:
max_peak = GetMediaItemMaxPeak( item )
average_rms = GetMediaItemAverageRMS( item )

Currently, we can only access this value by using the SWS label processor, and renaming all the items with the level we want. No very flexible.

Thanks for listening !

**Comment by nofishonfriday** [comment]
I'm assigning to this request.
No promises, but I have it basically working already. Will sprobably send a pull request for review to Tim soon.

**Comment by X-Raym** [comment]
Added in v2.9.3 thanks to @nofishonfriday  !
