### ISSUE TITLE
Request : Global(General) option/section for SWS Notes

### ISSUE THREAD

**Issue by mehmethand** [reaper-oss/sws#785]
Hi SWS Devs,
Now we have notes per project,track, item...etc.
Is it possible to have a "Global Notes" section where we can reach those notes from every project. 

For example : I'm working on an album. I have some note about the whole album. Now I'm using notepad for these notes. But if we have a global notes inside reaper that wolud be cool.

Thanks.

**Comment by nofishonfriday** [comment]
added in v2.10.0
