### ISSUE TITLE
"Split items at time selection (if exists), else at edit cursor" is splitting at PLAY cursor

### ISSUE THREAD

**Issue by TAG13** [reaper-oss/sws#796]
"Split items at time selection (if exists), else at edit cursor" is splitting at the PLAY cursor instead of the EDIT cursor. For my uses I need it to actually split at the edit cursor.

I tested and this is also happening with "Split items at time selection, edit cursor, or mouse cursor." The action "split items at edit cursor w/ crossfade on left" appropriately makes a split at the edit cursor, however.

I'm on Windows 7 using the 64bit version of Reaper.

Thanks!

**Comment by mkruselj** [comment]
It actually does split at edit cursor as well, but when transport is stopped. I think the name of the action is not complete, it should probably be like this:

SWS: Split items at time selection (if exists), play cursor (during playback), else at edit cursor
