### ISSUE TITLE
Error Notice

### ISSUE THREAD

**Issue by sdekuyper** [reaper-oss/sws#797]
I am getting an error notice every time I open Reaper telling me i have several copies already installed. I have checked, but can't find them anywhere other than where I have saved it. I have reinstalled it several times now, but it still keeps giving me the notice.
![screen shot 2016-04-01 at 11 30 14](https://cloud.githubusercontent.com/assets/18215899/14211660/43bcfb9a-f7fd-11e5-86bc-7e2259a74c88.png)

I checked the file menu and it seems to be installed.
![screen shot 2016-04-01 at 11 31 52](https://cloud.githubusercontent.com/assets/18215899/14211696/69d8cf70-f7fd-11e5-80cf-3d667081ebc7.png)

**Comment by swstim** [comment]
Let me know if this is still an issue.
