### ISSUE TITLE
Issues with Batch Loudness function

### ISSUE THREAD

**Issue by nozehed** [reaper-oss/sws#801]
I thought I would try out the batch loudness feature on a selection of around 100 items of dialogue. I set the option to "Analyse Selected Items", analysed them and normalised them to -23 LUFS. The result was random every time I tried it with some items set to -inf db and others set to -23 LUFS.

This is with SWS v2.8.7 Reaper v5.18/64 on Mac OSX 10.11.4

**Comment by Floflo35** [comment]
Hello, I'm not sure if this is the same issue, but if you do other stuff with your computer while analyzing loudness, it will get a wrong result. If you want to have accurate resulte, do not interact with you computer during the process.

**Comment by nofishonfriday** [comment]
^^ Addressed in SWS v2.9.8 pre-release:
"Prevent items going offline during analysis"
