### ISSUE TITLE
Bug: Toolbars auto refresh is broken

### ISSUE THREAD

**Issue by daxliniere** [reaper-oss/sws#810]
Toolbar buttons don't auto-refresh. You need to change track selection to trigger the refresh (which seems to defeat the purpose of this action).

**Comment by swstim** [comment]
Hey Dax.  What toolbar buttons are you expecting to be refreshed?

**Comment by daxliniere** [comment]
I can't remember what I was trying to do, but it was probably to do with this: https://github.com/Jeff0S/sws/issues/809

**Comment by swstim** [comment]
I'm going to assume this is more related to #809 than the auto refresh being broken.

**Comment by daxliniere** [comment]
No, from memory, this was unrelated to #809. It just happened that when investigating the actions' behaviour, we discovered that problem.
