### ISSUE TITLE
"Reposition Items" - can't set time interval to "Item start"

### ISSUE THREAD

**Issue by bladlus** [reaper-oss/sws#811]
![screen shot 2016-05-02 at 1 51 41 pm](https://cloud.githubusercontent.com/assets/9609740/14967908/2dcc3032-10ba-11e6-9ead-cd85acb58662.png)

**Comment by X-Raym** [comment]
@bladlus 
I created scripts to match the item start behavior, it also have special features,
You can take a look at these here: http://forum.cockos.com/showpost.php?p=1754955&postcount=38
These scripts can mimic this item start behavior.

A SWS fix would still be appreciated.

**Comment by bladlus** [comment]
@X-Raym great stuff, thanks!
