### ISSUE TITLE
ULT_SetMediaItemNote not working in Python

### ISSUE THREAD

**Issue by karumba** [reaper-oss/sws#817]
it seems that function is not defined in Python (however, it works in lua):

> NameError: name 'ULT_SetMediaItemNote' is not defined

**Comment by swstim** [comment]
You probably need to add `from sws_python import *` at the top of your script.

**Comment by karumba** [comment]
that solved it, thanks!

**Comment by X-Raym** [comment]
@swstim I think you can close the issue :)
