### ISSUE TITLE
"Reposition selected items..." on Mac not working for "item start"

### ISSUE THREAD

**Issue by leonardobarragan** [reaper-oss/sws#819]
OS X 10.11.5
sws-v2.8.3.0
Reaper v5.20/64

"Reposition selected items..."  When selecting "item start", "item end" remains selected and the action will only work as "item end"

**Comment by X-Raym** [comment]
Confirmed.

Meanwhile, you can envisage use these [scripts](https://www.extremraym.com/en/downloads/reascripts-space-items-pack/).

related issue: https://github.com/reaper-oss/sws/issues/811

**Comment by X-Raym** [comment]
**@leonardobarragan** 
I created alternatives scripts for the item start option. Check the link put in my previous post. Maybe it can help you.

**Comment by swstim** [comment]
Closed as duplicate of #811
