### ISSUE TITLE
SWS/BR: Split selected items at stretch markers

### ISSUE THREAD

**Issue by juliansader** [reaper-oss/sws#821]
"SWS/BR: Split selected items at stretch markers" skips some stretch markers, particularly if multiple items are selected.

![bug - sws_br split selected items at stretch markers](https://cloud.githubusercontent.com/assets/19420549/18255145/81eee840-73a6-11e6-98c6-bb32c033558f.gif)

**Comment by swstim** [comment]
I can't reproduce this... any chance you have an RPP (no media needed) that shows this?

**Comment by daxliniere** [comment]
Thanks Tim! :)

**Comment by jalovatt** [comment]
I think Pipelineaudio and I just ran into this issue. None of the stretch markers after bar 42.3.00 in the attached project are split. Selecting the leftover item and running the action splits some of it, but continues leaving smaller and smaller portions intact all the way to the splitting the last marker by itself.

![split at stretch issue](https://user-images.githubusercontent.com/19697310/42728048-bfc94718-876e-11e8-8ae2-e40dfc802ce1.gif)

RPP: https://www.dropbox.com/s/rg7mw5isegkanjg/split%20stretch%20issue.rpp?dl=1
