### ISSUE TITLE
SWS Website is down

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#826]
SWS extension website is not avaible, and so, the extension cannot be downloaded anymore.
Who is in charge of the domain name ?

**Comment by swstim** [comment]
Thanks for letting me know.  I'll fix ASAP.

**Comment by swstim** [comment]
OK site is back up, but may require a bit of time for the DNS change to propagate the through the tubes.

**Comment by X-Raym** [comment]
@swstim thanks ! good to see this is not abandoned :)
I will close the issue when it will back again so people can see that an issue was already open.

**Comment by X-Raym** [comment]
it's back ! :)
