### ISSUE TITLE
SWS 2.8.3.0 failing to load in Reaper 5.34

### ISSUE THREAD

**Issue by Prophet082017** [reaper-oss/sws#834]
I have installed Reaper v5.34 on an XP SP2 32bit machine and this runs ok. Tried nstalling SWS 2.8.3.0 and nothing happens. No error messages. I can see the SWS DLL named in the startup of Reaper when it scans for DLLs so I believe the install worked OK but there is no "Extentions" menu in the main menu and actions like "Marker Actions" are no responding. 

I don;t know where to look for error logs or how to switch on error logging from the SWS DLL to see if there is something failing so I am not able to send additional information but I will do if some can tell me where to find it or generate it.

**Comment by swstim** [comment]
Try the prerelease version, that should work fine: http://standingwaterstudios.com/download/pre-release/

**Comment by Prophet082017** [comment]
Hi SWSTim,. Just downloaded 2.8.7.0 and installed. Same result, not loading when Reaper starts. I have also tried previous versions with different Reaper versions. Always the same result. I see the DLL mentioned on Reaper start but no menu and no actions. ATB Mark

**Comment by swstim** [comment]
Any chance the new SWS 2.8.8 works?

**Comment by swstim** [comment]
Can't reproduce, and I can't support XP anymore.
