### ISSUE TITLE
Snapshot disappears on Undo

### ISSUE THREAD

**Issue by killergege** [reaper-oss/sws#835]
This is the first time I used snapshots, so I may have missed something.

If I create a snapshot and use Undo, the snapshot disappears. 
It may happen "in real life" that you create a snapshot, do some edits and use Undo, but if you undo a little too far, you lose your snapshot.
This happened to me (I'm still not used to snapshots so I don't always think about recalling one), and it's pretty annoying.

So could you keep snapshot creation outside of the undo history, if possible ?
If it's an expected behavior, could you add an option ?

**Comment by swstim** [comment]
Hey killergege, sorry for the slow response.
Snapshots are stored in the RPP file.  Reaper manages the RPP when doing undo steps, and will delete any changes (like new snapshots) when you run undo.  There's not much I can do about that.
However, you can export snapshots by right clicking on them, or pasting to the clipboard.  Those exports of course will last forever.  I know this isn't a perfect solution, but that's really all I can do right now.

**Comment by killergege** [comment]
Ok, thanks !
