### ISSUE TITLE
Snapshot recall delete the sends tracks

### ISSUE THREAD

**Issue by vincentsermonne** [reaper-oss/sws#843]
One track with lot of ReaSamplomatic and a complex routing with 32 stereo sends to separate tracks.
I do a snapshot and, when I recall it, some sends tracks are deleted.

https://dl.dropboxusercontent.com/u/50562634/strange%20snapshot.gif

**Comment by swstim** [comment]
If you could send over a copy of the RPP (no media) that would help.

**Comment by vincentsermonne** [comment]
Hi Tim,
https://dl.dropboxusercontent.com/u/50562634/Tchackpoum%20ReaperDrummer%20Bastard.RTrackTemplate

This is a track template link, import it, see the number of the sends , make a snapshot, recall the snapshot.

**Comment by swstim** [comment]
Thanks @vincentsermonne, the RPP was helpful!
