### ISSUE TITLE
BUG: "SWS/BR: Copy take media item source file path of selected items to clipboard" adds an invalid character to the path

### ISSUE THREAD

**Issue by mrdeangray** [reaper-oss/sws#846]
After running the action and pasting the file path in an Open File Dialog window of another app, I get a message like the following:

<img src="http://stash.reaper.fm/30215/InvalidFilename.PNG">

**Comment by swstim** [comment]
Do you have any more info?  Is it a slash character that's causing the issue?  Does it work if you add quotes to the front and back of the pasted name?

**Comment by mrdeangray** [comment]
Hey Tim,

There seems to be a newline character added at the end of the filename
because when I paste it into notepad++, the cursor ends up on the line
underneath the filename. See the gif below:

​

**Comment by swstim** [comment]
Ah, thank you. Fixed for next pre.
