### ISSUE TITLE
BUG: "Create markers from selected items (name by take source file name)"

### ISSUE THREAD

**Issue by JustinPerkinsMKE** [reaper-oss/sws#850]
I just installed the latest 2.9.2.0 beta build and still have the issue where the "Create markers from selected items (name by take source file name)" action sometimes numbers the markers in reverse order. This usually happens with higher item count situations over 15 items.

Normally the markers are numbered starting from number 1 and going up from there, in this case, the first marker is #18 and the markers go down from there.

Here is a screen shot of what happens:
https://www.dropbox.com/s/b4qm59w2fposwkx/Screen%20Shot%202017-03-28%20at%2011.38.01%20AM.png?dl=0

Here is the RPP file:
https://www.dropbox.com/s/iomklbflk8fxcdw/Guerrilla%20Ghost%20Analog%20Play%20And%20Capture.RPP?dl=0

sws edit: fixed links

**Comment by swstim** [comment]
I should have it fixed.  Will be in next pre.

**Comment by JustinPerkinsMKE** [comment]
Thanks for looking into it!

When I install the next pre-release, will the new version be overwritten in the custom action I’ve built containing this script? Or will I have to re-create the custom action again?

**Comment by swstim** [comment]
You won't have to change anything on your end.
