### ISSUE TITLE
BUG: Normalize item(s) to Peak RMS

### ISSUE THREAD

**Issue by JustinPerkinsMKE** [reaper-oss/sws#851]
See this post:

http://forum.cockos.com/showpost.php?p=1797923&postcount=38

Sometimes for no apparent reason an item will normalize to an insanely loud level even though it's more or less just like all the other items in a group that were normalized.

Can you look into what might cause this?

![screen shot 2017-02-06 at 9 46 09 am](https://cloud.githubusercontent.com/assets/20074678/24432390/8307a780-13e7-11e7-80eb-bc610173c6f1.jpg)

**Comment by swstim** [comment]
If you have an example RPP of this going bad it would be super helpful.  (PS hey from down the road in Madison)

**Comment by JustinPerkinsMKE** [comment]
Hi Tim,

I didn't realize you were in Madison.

In the morning I'll revisit this session and try to reproduce. If I can do that I'll pass the files along to you.

Thanks,
Justin

**Comment by JustinPerkinsMKE** [comment]
OK, sorry for the large zip file but I wanted to get you the RPP file and all the source audio files. Also, ignore the terrible song titles for this project. It's not mine, just something I mastered recently for a client.

**Here is the zip file you'll need:**
https://www.dropbox.com/s/7qh7j28i3yuv5h7/SWS_RMS_Normalize_Test_V1.zip?dl=0

(At this time it still has 20 minutes to finish uploading)
![after](https://cloud.githubusercontent.com/assets/20074678/24457783/c348dfe2-145c-11e7-820c-566644bc3cd9.png)
![before](https://cloud.githubusercontent.com/assets/20074678/24457784/c36b7a98-145c-11e7-81ee-c4fe0f6f7f48.png)

The zip file contains my REAPER configuration, the original WAV files for the project (32-bit FP/96k), a folder of two screen shots (before and after I run my custom action containing the RMS normalize action), and then the folder with two RPP projects, one before the custom action is run, and one after. The _Audio Files_ folder in the REAPER project folder is meant to be empty because it's pulling the audio files from that "original files folder".

As you'll see if you load my REAPER configuration, I have a custom action that does a few things by pressing F13. One of those things is the "Normalize item(s) to Peak RMS" action.

As mentioned, now and then I'll have a project where an item gets normalized by an insane amount. In this project, the item named "Asshole_24bit_96k.wav" gets boosted by 72.1dB. The file itself is actually a 32-bit/96k WAV but the original file came is as 24-bit/44.1k so that why it has that confusing name. It appears to be just a normal WAV file like all the rest but something causes an incorrect normalization.

I see this happen now and then and I'm not sure why certain files trigger such a bizarre normalization level.
