### ISSUE TITLE
FR: Relative item timeline

### ISSUE THREAD

**Issue by JustinPerkinsMKE** [reaper-oss/sws#853]
One thing that exists in WaveLab and I've seen in no other DAW is a relative clip timeline. This means that when activated, a smaller timeline is shown on the audio file and relates to the start of the audio file and not the total project timeline.

In REAPER, it would be great if items could have their own mini timeline so you can easily find the 1:23 point in that file for example.

Maybe this is already possible but if not, curious to see if anybody else would find it useful.

**See this thread for more comments:**
http://forum.cockos.com/showthread.php?t=181286

**Comment by nofishonfriday** [comment]
Accepted alternative:
Item Timecode script, available in [HeDaScripts Manager](https://reaper.hector-corcin.com/app/hedascripts-manager)

**Comment by swstim** [comment]
For the record, this thread talks about the Item Timecode script: https://forum.cockos.com/showthread.php?t=195711

Also, a thought - using the project start offset (project settings) might be an alternative way to have the master time reflect the item time.

**Comment by JustinPerkinsMKE** [comment]
I think the HeDa script also address the issue of the project start offset time. Either way, the HeDa version works pretty well for me.

My original idea was to be more like the WaveLab option where the item time is shown right on the item itself and not as a counter but I also realized I have a need for region time as well so the pop up counter is really probably the best solution.
