### ISSUE TITLE
Bug: reaper.BR_EnvAlloc misbehaving after "Take: Toggle take volume envelope"

### ISSUE THREAD

**Issue by amagalma** [reaper-oss/sws#861]
reaper.BR_EnvAlloc does not work for a take volume envelope after having been toggled with action "Take: Toggle take volume envelope" (40693). 

Relevant test code can be found here:
http://forum.cockos.com/showthread.php?p=1829881&posted=1#post1829881

**Comment by nofishonfriday** [comment]
@amagalma 

Since your link points to "Now I can not reproduce" is this working ok now ?
Can we close this issue or should it stay open ?

FWIW, I could not reproduce the issue with your code in the first post in this thread (but I've only tried with a single MIDI item so far.)

**Comment by amagalma** [comment]
You can close this issue as with further tests, I found that it is a Reaper bug and not an SWS one.
https://forum.cockos.com/showthread.php?p=1899095#post1899095
