### ISSUE TITLE
FR: Wildcards for FX names for the "x" console command

### ISSUE THREAD

**Issue by admiralbumblebee** [reaper-oss/sws#863]
Often there may be Mono/Stereo/Surround/etc.. versions of a plug-in with multiple types (channel, buss for instance) that you want to use the console "x" command on.

Being able to just type "x;plug * stereo" would be much easier to manage than "x;plug channel long stereo".

**Comment by swstim** [comment]
Sorry, there's no extension/plugin access to the available plugins, I can only add plugins using exact names.
