### ISSUE TITLE
Delay for Startup actions

### ISSUE THREAD

**Issue by daxliniere** [reaper-oss/sws#874]
Hey guys,
I have actions for 'scroll view to first selected track' and 'scroll mixer to first selected track' as my startup actions, but they never seem to run. Is it possible a delay period could be implemented to allow for the project to load before the actions are run?

Cheers!
Dax.

**Comment by bFooz** [comment]
This have recently came as an issue also with Heda's Track Inspector - when it is set as a global startup and a project is opened from a welcome screen, it messes with its sends.

**Comment by daxliniere** [comment]
Any news on this?

**Comment by X-Raym** [comment]
@daxliniere you have Wait for X seconds type of action natively :P
