### ISSUE TITLE
Default ReaConsole shortcut doesn't work

### ISSUE THREAD

**Issue by andybarilla** [reaper-oss/sws#877]
I've tried this on two difference machines (both Windows) with both a regular installation and portable. 

If I check the keyboard shortcut for ReaConsole and it says 'C' but that doesn't work. If I remove that and re-set it to 'C' it works fine.

Before fixing it once I tried assigning 'C' to another random command and it didn't warn me about the shortcut already being used.

**Comment by nofishonfriday** [comment]
Confirmed here.

**Comment by cfillion** [comment]
It works on macOS. For some reasons setting the FVIRTKEY flag in the fVirt member of the action's ACCEL struct appears to fix it on Windows.

```cpp
{ { { FVIRTKEY, 'C', 0 }, "SWS: Open console" },								"SWSCONSOLE",       ConsoleCommand,  "SWS ReaConsole", 0, IsConsoleDisplayed },
```

Not sure if it's a bug in REAPER of it this workaround is actually a proper solution. MSDN mentions that FVIRTKEY is not meant for character code.

**Comment by nofishonfriday** [comment]
Thanks for the fix @cfillion .

Just a thought, I (and I assume some other users) have currently assigned "C" to some other action. Wouldn't this lead to a potential conflict now if "C" gets re-assigned also as default shortcut for the console (as Reaper doesn't allow same shortcut for different actions, what will happen ?)

**Comment by cfillion** [comment]
From my tests, REAPER ignores the shortcut suggested by SWS if it is or was used for another action.

**Comment by nofishonfriday** [comment]
So it seems fine I think, thanks for testing.
