### ISSUE TITLE
"CC: Create CC Lane" and "...Make it last clicked" CRASH instantly

### ISSUE THREAD

**Issue by tusitala** [reaper-oss/sws#879]
Hi, these two midi editor actions instantly crash Reaper in my system:SWS/S&M: Create CC laneSWS/BR: Create CC lane and make it last clickedjust as soon as i click on "run" Reaper crashes instantly

MacOS 10.12.5

**Comment by veto-gh** [comment]
FWIW no crashs with this actions on linux native

**Comment by cfillion** [comment]
Closing as stale. Feel free to re-open along with a [crash report](https://forum.cockos.com/showthread.php?t=36653) if you still encounter this issue.
