### ISSUE TITLE
ReaScript FR: LU and LUFS function

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#880]
Thanks to @nofishonfriday, we now have max peaks and RMS function for ReaScript. Good !
https://github.com/reaper-oss/sws/issues/781
But I think it could be very intersestig to also have LU and LUFS used in SWS Loundess Analyser like
```

lufs = GetMediaItemLUFS( item )
lu = GetMediaItemLU( item )
```

We can also imagine this being used on Take instead like

```
lufs = GetMediaItemTakeLUFS( take)
lu = GetMediaItemTakeLU( take )
```

This kind of calculus is hard to make from scratch with Lua and regular audioprocessor tools so having this in ReaScript could be very interesting :P

Thanks for listening !

**Comment by Soundiron** [comment]
This feature would be extremely helpful!

**Comment by X-Raym** [comment]
Pull request made by @nofishonfriday : https://github.com/reaper-oss/sws/pull/882

(thanks, nofish !)

**Comment by X-Raym** [comment]
See v2.9.5. for detailed about the integration. Thanks @nofishonfriday !
