### ISSUE TITLE
Xenakios/SWS: Set previous/next fade in/out shape for items

### ISSUE THREAD

**Issue by udzele** [reaper-oss/sws#889]
In these 4 actions the fade shapes do not fit with those in the Media Item Properties window.
For some of the expected curves only a linear fade is set.

Xenakios/SWS: Set previous fade in shape for items
Xenakios/SWS: Set next fade in shape for items
Xenakios/SWS: Set previous fade out shape for items
Xenakios/SWS: Set next fade out shape for items

**Comment by veto-gh** [comment]
Possibly a Reaper bug? Same with Reascript code (eel):
```
it=GetSelectedMediaItem(0,0);
s=GetMediaItemInfo_Value(it,"C_FADEINSHAPE");
s+=1;
s>6 ? s=0;
SetMediaItemInfo_Value(it,"C_FADEINSHAPE",s);
UpdateTimeline();
```
The stock action 

> Item: Cycle through fade-in shapes

 works though.

**Comment by nofishonfriday** [comment]
Thanks veto.
Confirmed here too (with a Lua script).

Xenakios also uses API GetSetMediaItemInfo() so Ithink it can be safely assumed it's a Reaper (API) bug.
https://github.com/reaper-oss/sws/blob/master/Xenakios/MoreItemCommands.cpp#L673

**Comment by swstim** [comment]
@udzele As a workaround you can make a custom action that calls cycle forward 6 times, which essentially moves you backwards one.

**Comment by udzele** [comment]
That's a great workaround!
Thanks Tim!
