### ISSUE TITLE
_WOL_ADJENVTRHMOUSEZCMC kills AI points still

### ISSUE THREAD

**Issue by mkruselj** [reaper-oss/sws#891]
"SWS/wol: Adjust envelope or track height under mouse cursor, zoom center to mouse cursor (MIDI CC relative/mousewheel)" action nulls all automation points within automation items when resizing the envelope height down to a certain level. See GIF

![resize env](https://user-images.githubusercontent.com/2393720/30515419-a24d61bc-9b27-11e7-9bea-dff60e3ee026.gif)

There might be more actions that do this, I didn't check. But this one for sure.

**Comment by wolqws** [comment]
I can't reproduce, maybe some settings?
(Can't attach gif, too...)
[https://www.dropbox.com/s/zm6titdilt41xkn/ai%20bug.gif?dl=0](url)

**Comment by mkruselj** [comment]
Which settings would that be?

This is with latest SWS and Reaper 5.50c.

**Comment by mkruselj** [comment]
OK LOL, brainfart. I was scrolling above the trim slider. Sorry. :)
