### ISSUE TITLE
open recent project

### ISSUE THREAD

**Issue by kirschkematthias** [reaper-oss/sws#893]
after updating to SWS 2.9.6 'open recent project' and 'open project template' are always empty. Replacing the new reaper_sws_extension with the old one shows all my projects and templates.

**Comment by swstim** [comment]
I assume you're on High Sierra, and this is related to #297.  Fixed in 2.9.7.

**Comment by kirschkematthias** [comment]
Yes, you're right. thanks for your reply.

**Comment by kirschkematthias** [comment]
everything works fine now! Thanks
