### ISSUE TITLE
Select next item (across tracks) - not working as expected

### ISSUE THREAD

**Issue by Sebadier** [reaper-oss/sws#896]
The action SWS: Select next item (across tracks) selects the next item on the track with a item already selected. When there are no more items it selects the first item on the next track.

I would expect it to select the next item (so the item the appears after the minimum of elapsed time) no matter on which track that item is.
And there is no other action doing this, is there?

Thanks and cheers, Sebasitan

**Comment by nofishonfriday** [comment]
So this is what you want I assume ?

![Alt Text](https://i.imgur.com/3aKfRrm.gif)

I'll upload a script to ReaPack which does this shortly:
nofish_Select next item (in time) across tracks

Let me know if it helps.

**Comment by Sebadier** [comment]
That is exactly what I'm looking for! Didn't find it on ReaPack though. Is it a special repository?

**Comment by nofishonfriday** [comment]
Oh forgot to mention, my repo isn't enabled by default in ReaPack, sorry.
Instructions here:
https://github.com/nofishonfriday/ReaScripts

Please report back here if it does what you need so we can close this issue (or not).

Renaiming existing SWS actions is not a good idea I'd think (even if the naming may be confusing, which I could agree here) for not breaking existing custom actions.

**Comment by Sebadier** [comment]
Works like a charm - thanks a lot!
