### ISSUE TITLE
SWS Issues on OSX 10.13 High Sierra / Reaper 5.50

### ISSUE THREAD

**Issue by acklin83** [reaper-oss/sws#897]
All my Themes are gone from the menu (still in Resources Folder) and no more right-click menus on TCP/MCP/Media Lane. It all works if I uninstall SWS.
Other User Reports include inability to select anything from the "File" Menu and empty "Recent Projects" list (although correctly written in Reaper.ini file).

**Comment by swstim** [comment]
Thanks - fix coming later today.

**Comment by swstim** [comment]
Fixed in v2.9.7

**Comment by pophitru** [comment]
Is it the time to upgrade to 10.13 to work in reaper? Is MIDI window issue fixed now?
