### ISSUE TITLE
A set action to navigate/select automation item by keyboard.

### ISSUE THREAD

**Issue by vgjh2005** [reaper-oss/sws#899]
Hi:
I often use my keyboard to control reaper. Now cockos develop a new function called automation item to contain automation info. It's a great function. But
 until now, there are only some mouse modifier key to do some specific control on it. So, hope to add a set additional actions to visit those function. Summary are below:
action： switch to next/previous automation item
action： switch to next/previous automation item from pool
action: Select next/previous automation item
action: Select next/previous automation item from pool
action: select next/previous automation item leaving  selected items from pool
action: select next/previous automation item leaving  selected items
Thanks!

**Comment by htibcsike** [comment]
I'm interested in this set action, thank you. My e-mail address is: hermann.tibor@gmail.com

**Comment by cfillion** [comment]
This can be done in scripts. Should the actions work on the AI in the current envelope only or on every AI in the whole project?

**Comment by cfillion** [comment]
![Script demo](https://i.imgur.com/poFrBZM.gif)

**Comment by vgjh2005** [comment]
Hi:
I think applying those actions into a selected automation lane is more convinience. Thanks!

**Comment by vgjh2005** [comment]
Hi:
However, automation item points also need similar actions to control them. select/delete/add/edit/switch etc. Or update original item point actions are also good idea. Thanks!

**Comment by cfillion** [comment]
I just released the scripts. It's available as "Automation item selection bundle (10 actions)" in ReaPack. The actions are:

- cfillion_Add next automation item in pool to selection.lua
- cfillion_Add next automation item to selection.lua
- cfillion_Add previous automation item in pool to selection.lua
- cfillion_Add previous automation item to selection.lua
- cfillion_Select all automation items in pool.lua
- cfillion_Select all automation items.lua
- cfillion_Select and move to next automation item in pool.lua
- cfillion_Select and move to next automation item.lua
- cfillion_Select and move to previous automation item in pool.lua
- cfillion_Select and move to previous automation item.lua

**Comment by vgjh2005** [comment]
Good job! Thanks!

**Comment by htibcsike** [comment]
Hi!
Where can I find the ReaPack?
Thank you very much!
With Best Regards,
Tibor

2017-10-01 5:02 GMT+02:00, vgjh2005 <notifications@github.com>:

**Comment by cfillion** [comment]
https://reapack.com
https://forum.cockos.com/showthread.php?t=177978

**Comment by htibcsike** [comment]
I went to the website and I found "The latest stable release, ReaPack v1.1 released on 2017-01-16" where can I get the updated and modified version? Thank you.

**Comment by cfillion** [comment]
1.1 is the latest stable version. Once installed, do these two steps to install the automation item selection scripts:

1. Search for "automation item selection" in Extensions > ReaPack > Browse packages
2. Right click on the package in the list, select "Install" and click on OK

You will then be able to find all 10 actions in your Action List.
