### ISSUE TITLE
SNAP STRETCH MARKER IN TIME SELECTION TO GRIND IF UNTER XXms

### ISSUE THREAD

**Issue by AEB31415** [reaper-oss/sws#908]
I Angelo and I'm a really happy user of your SWS Reaper extension.
I have a feature request for you. 
I often use the native function in reaper "Snap stretch markers in time selection to grid". 
It's is really useful but the problem is that if the stretch marker is that it works indipendently of how far is the stretch marker from the grind.
For example, if a stretch marker is approximatley in the middle between two grid lines than with this function it will snap the stretch marker to the closest gind line, even if it's not the correct one. 
It would be nice to have something like the option "Maximum gap" in your function "fill the gaps between selected items": 
for example it could add a marker and leave the stretch marker where it is when the distance from the stratch and the closest gind line is bigger the XXmilliseconds (or a percentage of the timelenght between two grind bars).

I hope everithing make sense and you..

Thank you, 
Angelo

**Comment by nofishonfriday** [comment]
Hi, 

have you seen [mpl Quantize tool](http://wiki.cockos.com/wiki/index.php/Quantize_tool_by_mpl) already ?
It can snap stretch markers (in time selection) to grid and has a 'Gravity' setting (to only snap within x ms), I'd think that's what you're looking for or ?

It's available via [ReaPack](https://reapack.com/).

**Comment by AEB31415** [comment]
Thank you nofishonfriday,
 
it's exactly what I was looking for!
I didn't know about ReaPack, it's full of really useful scripts.

Bye,
Angelo

**Comment by nofishonfriday** [comment]
Glad it helped.
So I'm closing this issue.
