### ISSUE TITLE
Open Projects from List cannot read from text file

### ISSUE THREAD

**Issue by Phildrummer** [reaper-oss/sws#910]
Hi
I am in a coverband and I have a massive excel to keep track of a lot of different information about songs like name, artist, tempo, length and so on. I also have a column that builds the file path of each Reaper project so I can just copy those cells, paste it in a text file(notepad++), save it, change the extension from ".txt" to ".RPL" and then open this project list in Reaper which is at the end of the day a kind of set list for practices or gigs. Reaper will open the first one in the list, but after that it can't find the rest. I do not want to open each individual file and then save the list of open projects. That just takes way too long.
I really don't know if this is a bug or a formatting issue. I have attached the error messages and .txt file. 
Cheers
Philip

![error1](https://user-images.githubusercontent.com/32986307/31854222-a7d751e0-b695-11e7-95e9-4c4552d64396.JPG)
![error2](https://user-images.githubusercontent.com/32986307/31854229-b45dc58e-b695-11e7-8bb9-56e83ddf7586.JPG)
![error3](https://user-images.githubusercontent.com/32986307/31854230-b47c00bc-b695-11e7-9818-af3fb2dadd16.JPG)
[Setlist.txt](https://github.com/reaper-oss/sws/files/1404323/Setlist.txt)

**Comment by cfillion** [comment]
The lines in this text files are terminated by only carriage return characters (legacy macOS fashion). Use regular new line (unix/modern fashion) or cariage return + new line (historic Windows fashion).

There should a setting for this in Notepad++ (if not try another text editor which gives you control over how the line breaks are stored in the file).

**Comment by Phildrummer** [comment]
My first thought was the length, but I have shorter ones, so I didn't think that was the issue.
I used Lin Feed Unix and it worked like a charm!
Thanks!

**Comment by nofishonfriday** [comment]
Closing this as it seems solved.

@Phildrummer 
If you think otherwise just tell and we can re-open.
