### ISSUE TITLE
Region Playlist - No stopping allowed?

### ISSUE THREAD

**Issue by Khorus2112** [reaper-oss/sws#914]
Hello good people!

I'm trying to use a Region Playlist to sequence songs in a live show.     Looks like it is working great but there's no way to stopping/pausing the playlist in between regions.   I tried adding a marker with an "!1016" (and other action numbers) at the end of my regions, nope...  The playlist just won't stop...

Now, would there be a way of doing this?   Maybe there is, I just don't see how.    Could it be a "feature request"?    Say, if we put "0" on the Loop count column, the Playlist could stop after the current region has been played.   That'd be simple and awesome for designing set lists in a live show.

Thanks for all the hard work, you guys rock!

Marc aka Khorus

**Comment by nofishonfriday** [comment]
Seems to work here with !1016 action marker.
![Alt Text](https://i.imgur.com/1EJniNr.gif)

Have you tried running action: "SWS: Enable marker actions" before ?
Maybe they were disabled ?

**Comment by Khorus2112** [comment]
Yes I did, but I don't have the same behavior as yours it seems.   In the exact same setup, mine just skips to the next region, no questions asked.   Have you tried adding more than one region?

**Comment by nofishonfriday** [comment]
Doh that was kinda stupid not trying with more than one region. 🗡 
Ok, I now see the same behaviour as you when having more than one region.

**Comment by cfillion** [comment]
The native Region/marker Manager dialog has a "Play region through then repeat or stop" option in the context menu.

**Comment by Khorus2112** [comment]
I just tried the native Region Manager, it somehow does the right thing but you can't reorder the regions for changing set lists.

**Comment by Khorus2112** [comment]
Here's a little mockup I made real fast to show you guys how this could work.   We could have 3 modes (or behaviors if you will) for each regions.   That's the way Cubase works in its Arrangement Window and it is a lifesaver.   If only I knew how to code, I'd do it myself but, alas coding in C/C++ is not one of my talents! :(

![capture](https://user-images.githubusercontent.com/33158043/32133569-9d2df56a-bba8-11e7-8e72-8795213964d2.PNG)

**Comment by nofishonfriday** [comment]
I think "Repeat Forever" mode is already there, when e.g. putting -1 in the Loop count column it turns to ∞.
So it would actually 'just' need a "Pause after repeats" tickbox, no ?

**Comment by Khorus2112** [comment]
Yes, that's the main feature request.    The repeat forever is indeed already implemented.

**Comment by Khorus2112** [comment]
Hi guys,

I've been doing some research on various Reaper forums and such.    I have found that I'm not the only cat who'd like to have the "Pause after Region" function included.    In fact, people have been asking for this function in Reaper since 2009.    

It is vital if you want to use Reaper Live on stage.    Now, if only I knew how to code in C++! :(

**Comment by nofishonfriday** [comment]
What I found seems to kinda work is putting a Pause action marker (!1008) not at the end of the region but at the start of the next one.
Have you tried this already ?

![Alt Text](https://i.imgur.com/1ijoYoH.gif)

Current issues with this:
1. Play cursor doesn't stop exactly at marker, it's up to I think ~100ms later, due to 'lazy updating'.
2. Currently you get a warning about nested markers when doing this.
3. No way to 'unpause' directly from the Playlist window, need to use the main transport Pause button instead.

1. would probably need to stay this way, but 2. + 3. could probably be changed.

@Khorus2112 
Do you think this would be a 'workable solution' ?

**Comment by Khorus2112** [comment]
It looks like a working hack but after just a few tests, it bugged and went like this! 

![khoruscap](https://user-images.githubusercontent.com/33158043/32710240-9a10002c-c804-11e7-86d3-169e26614970.gif)

For some unknown reasons, the !1008 skips and loops in an unknown region at the end?   I'm puzzled!

**Comment by Khorus2112** [comment]
Ah, ain't got no love anymore! :P    Jokes apart, many users has been requesting this for a very long time.   That feature alone would make me abandon Cubase. ;)

**Comment by eruji** [comment]
Yes please! I love the reordering through the SWS manager but i need to be able to stop/pause the playlist on every region, or as specified with the Mode mockup above.

**Comment by Khorus2112** [comment]
I actually fixed the issue by coding/scripting my own region player!   It works pretty good, just no nice list like Region Manager...

**Comment by imlukedewitt** [comment]
@Khorus2112 would you mind sharing the region player you made?

**Comment by peelybird** [comment]
Yes please. Would be the key to making this useful for live performances. Currently I’m unable to use this otherwise excellent playlist tool for what we need but khorus2112 idea for the 3 modes would be perfect. Plus shouldn’t there really be a stop action? There’s a stop button because obviously there has to be… so lets mirror it with the action!

**Comment by Buy-One** [comment]
@Szapi

Since you're working on the Playlist, would you consider this feature request?

And related 
https://github.com/reaper-oss/sws/issues/1575

**Comment by Szapi** [comment]
My changes would allow you to put action markers inside regions. But pausing precisely at a given time is not supported by the Reaper API, so that's the best we can do right now.
