### ISSUE TITLE
[Bugs] Loudness Analyzer TP Bug+

### ISSUE THREAD

**Issue by DGTall** [reaper-oss/sws#917]
Here's an image that illustrates the problem

![sws loudness bugs](https://user-images.githubusercontent.com/33203146/32146499-c620a2e8-bcd8-11e7-86c2-a19a2f94bc27.png)

DG

**Comment by DGTall** [comment]
And I mean't to say "doesn't" :D

**Comment by cfillion** [comment]
Is "Measure true peaks (slower)" enabled when you right click > Options?

**Comment by DGTall** [comment]
Hey,

Sorry for the late reply.

I did forget to enable "Measure true peaks (slower)", so yeah it's my fault, I apologise. :/
However the cancel button is still an issue. ;)

**Comment by DGTall** [comment]
Oh dear lord, I think I really misinterpreted the "Cancel" button...
I thought it acted as a "close" button to close the window, but it was mean't to cancel the ANALYSIS process ONLY.

I am sincerely sorry for making up confusion on this bug thread...
I will do my best to be more careful next time.
