### ISSUE TITLE
"Move grid line to edit cursor"

### ISSUE THREAD

**Issue by zappazapper** [reaper-oss/sws#925]
I'm using this to build a tempo track from a live performance not played to click...  i don't want to (at least at this point) modify the existing material in terms of tempo, i only want to build a click that follow the existing tempo as the drummer speeds up and slows down...

i have "Timebase for events/envelopes/markers" set to "Beats (position only)" so that no matter what happens to the project tempo, the audio doesn't change...

i tap out a tempo with the mouse just to start with a tempo that will be close to the material...

using transient detection to find the first drum hit, i manually place the first drum hit on the appropriate Measure:Beat...  for arguments sake, let's say it's a kick on beat 1 of measure 5...  i place a tempo marker at that point, with "Gradually transition tempo to next marker" set to OFF...

i again use transient detection to find the next drum hit, let's say a snare that should be on beat 2 of the same measure, but the grid is off...

so i use "Move grid to edit cursor"...  it partially does what i want...  it modifies the tempo of the marker at beat 1 so that the grid at beat 2 lines up with the cursor, which is currently on the transient at the beginning of the snare hit...  great...

but it also places a stretch marker WHERE THE GRID LINE USED TO BE...  since the grid line has moved, the place that it's putting the stretch marker is useless...  there is no way that i can see that will allow me to either disable the placement of the stretch marker (good enough), or put the stretch marker where it makes sense to have it, WHERE THE GRID LINE IS NOW, on the transient at the beginning of the drum hit...

please advise...

**Comment by zappazapper** [comment]
never mind :)

"SWS/BR: Options - Automatically insert stretch markers when inserting tempo markers with SWS actions"

OFF

**Comment by nofishonfriday** [comment]
So sounds like we can close this.
