### ISSUE TITLE
BR - StartupVersionCheck value in reaper.ini crashes Reaper

### ISSUE THREAD

**Issue by knochenhans** [reaper-oss/sws#930]
Hi, I'm having a very weird problem: Since I used Reaper today, it started crashing on startup. I tracked down the cause to the "BR - StartupVersionCheck" variable in the [SWS] section in my reaper.ini file. When I delete that line or change it back to the value of my last working configuration ("1 0 1510712171" in my case), Reaper works again, but on closing changes the value back to "1 0 1511313510", thus crashing again at the next startup until I delete/change the line. Can someone explain to me what happens here?

I'm using SWS 2.9.7 on Reaper 5.52.

**Comment by cfillion** [comment]
Which operating system? Can you send a crash dump/log?

One thing you can try to avoid the crashes is to disable "Official releases" update checks in Extensions > About SWS extension (or just set the first 1 to an 0 in the ini setting you mention).

**Comment by knochenhans** [comment]
Ah sorry, forgot to add this info. I'm using the x64 version of Reaper on Windows 10 (x64). I attached some windows crash files my last crash produced, I hope that helps :)

[crash files.zip](https://github.com/reaper-oss/sws/files/1496562/crash.files.zip)

By the way, I switched off the update check via the file, but that doesn't change anything, it really seems to be that number at the end.

**Comment by knochenhans** [comment]
I poked a bit around and found a strange connection to some entries in my reaper-extstate.ini. I'm using a user-made plugin for my Tascam US-2400 which uses a overlay window. The state of that window is written into the reaper-extstate.ini file when Reaper closes. When I take this data out or edit it so that plugin windows is closed, the value of the StartupVersionCheck variable mentioned above seems to have no influence anymore and Reaper starts fine (right now, I always have to set it back to 1510712171 before i start Reaper). However, it crashes when I then try to open the mentioned plugin window again... does this make any sense? ;)

**Comment by nofishonfriday** [comment]
What happens if you remove / uninstall SWS and then open the mentioned plugin window in Reaper ?

**Comment by cfillion** [comment]
That crash dump has `reaper_csurf_us2400_mkey.dll!00000000073e8789` in the call stack, which would point toward that crashing.

And I just tried building and running that plugin: it crashed as soon as I added it as a control surface in REAPER preferences (then on startup).

MySetSurface_OutputMeters attempated to call Track_GetPeakInfo with tk == null.

**Comment by knochenhans** [comment]
@nofishonfriday After uninstalling SWS, Reaper still crashes.

@cfillion So I guess this is really more a fault of that plugin. That's a bit weird because I never had any problems like that with it and there were no changes to since a while... but I better ask in the Reaper thread for the plugin then :) Thanks for pointing me in right direction, anyway!

The only thing I really don't get is how that all is linked to that StartupVersionCheck value...

**Comment by nofishonfriday** [comment]
The third number in the StartupVersionCheck is the [Unix Time Stamp](https://www.unixtimestamp.com/) of the last SWS update check, so I wouldn't think its value has anything to do with this crash directly.

Anyway, given @cfillion's reproduction of the crash with said plugin (thanks for checking) and the fact that the crash still happens on your side if SWS isn't even installed I think we can relatively savely assume this is not a SWS related crash and I'm closing this for now.

If new indications show up it IS related to SWS in some way we can always reopen.
