### ISSUE TITLE
After reboot Reaper do not save settings REAPER v5.70

### ISSUE THREAD

**Issue by shibbolethwithout** [reaper-oss/sws#934]
After reboot Reaper do not save settings such as automatic color and icon,  track template and more. REAPER v5.70 Windows 8 64

**Comment by cfillion** [comment]
This was fixed in WDL last August (justinfrankel/WDL@30dda7782d6fdbc22b99fd5662980d3d1b8ed2df). SWS needs to be rebuilt with up to date WDL.

You can try this one in the meantime: https://cfillion.ca/files/sws/utf8-resource-path/.

**Comment by shibbolethwithout** [comment]
In SWS beta autocolor and icon is working ok
