### ISSUE TITLE
SWS beta:  track template slots and fx chains doesn't work: don't save settings 

### ISSUE THREAD

**Issue by shibbolethwithout** [reaper-oss/sws#935]
track template slots and fx chains doesn't work: don't save settings. After reboot Reaper slots list is clear. REAPER v5.70

**Comment by cfillion** [comment]
This happens because WDL doen't provide UTF-8 implementations of GetPrivateProfileSection and WritePrivateProfileSection.

**Comment by burdak** [comment]
I have the same problem. You could tell in more detail how to solve it? Thanks.

**Comment by cfillion** [comment]
I've updated my build at https://cfillion.ca/files/sws/utf8-resource-path/ with an additional fix for this.

There is at least one remaining issue: the content of S&M.ini file is limited to the ANSI code page. This means all settings related to file paths may lose their data.

The solution seems to be creating the file with a UTF-16 BOM before letting {Get,Set}PrivateProfile* read/write into it.

REAPER's own reaper.ini is also affected by this, eg. it doesn't save last used projects with Unicode.
