### ISSUE TITLE
Analyze loudness window UI bugs

### ISSUE THREAD

**Issue by mkruselj** [reaper-oss/sws#942]
1. Right-clicking the column header, checkboxes are not shown for the enabled columns

2. Sorting by True peak column is broken. Positive dBTP values are sorted AFTER the lowest negative value! This is clearly wrong, should be an easy fix?

**Comment by cfillion** [comment]
1. It works here. https://i.imgur.com/YaFTG6Y.png
2. Try this build: https://cfillion.ca/files/sws/numeric-truepeak-sort/

**Comment by mkruselj** [comment]
That build fixes the sorting, but not the checkboxes. Not sure what's up with that... (W10 here, latest Reaper pre).

**Comment by cfillion** [comment]
What is the value of `BR - AnalyzeLoudnessView WndPos` in your reaper.ini? Are the checkboxes still broken for you in a fresh portable install?

**Comment by mkruselj** [comment]
BR - AnalyzeLoudness=0 1 1 1 0 1 1 1 0
BR - AnalyzeLoudnessView WndPos=-6 25 0 265 1 216 2 87 3 70 4 70 5 115 6 115 7
BR - AnalyzeLoudness WndPos=3B0200007A0100001B07000086030000000000000000000063
BR - AnalyzeLoudness WndPos=0.50000000 0


But even if I remove all that from the .ini, still no checkboxes. There's only one grayed out under "visible columns"...

![image](https://user-images.githubusercontent.com/2393720/35028931-c392e7b6-fb58-11e7-9ceb-097ba7117d53.png)

**Comment by mkruselj** [comment]
This was fixed in PR #942.
