### ISSUE TITLE
Include Latch-Preiview in the action "SWS/S&M: Toolbar - Toggle track envelopes in touch/latch/write"

### ISSUE THREAD

**Issue by robingshore** [reaper-oss/sws#945]
It would be very helpful if tracks that are in Latch-Preview automation mode were toggled by the action "SWS/S&M: Toolbar - Toggle track envelopes in touch/latch/write". Right now this action only affects tracks that are in touch, latch, and write mode.

**Comment by nofishonfriday** [comment]
merged.
