### ISSUE TITLE
Bug: BR_SetMediaItemEdges should keep envelope points in place

### ISSUE THREAD

**Issue by X-Raym** [reaper-oss/sws#950]
Hi,

The ReaScript function BR_SetMediaItemEdges keep envelope points position relative to the item left edges, instead as leaving them at their absolute position in the project (the whole point of this function is to modify items and by preserving absolute position of the content, so envelope points should move).

Steps:

1. Have an item
2. Create an envelope
3. Add points
4. use the SetMediaEdges function
5. see that envelope has been offset.

![demo](https://i.imgur.com/QmhJEKe.gif)

Thanks for taking a look :)

**Comment by X-Raym** [comment]
Some Lua code that may help

```lua
function OffsetTakesEnvelopes(take, offset)
  local env_count = reaper.CountTakeEnvelopes(take)
  local take_rate = reaper.GetMediaItemTakeInfo_Value( take, "D_PLAYRATE" )
  for i = 0, env_count - 1 do
      local env = reaper.GetTakeEnvelope(take, i)
      local env_points = reaper.CountEnvelopePoints( env )
      for j = 0, env_points - 1 do
        local retval, time, value, shape, tension, selected = reaper.GetEnvelopePoint( env, j )
        reaper.SetEnvelopePoint( env, j, time + offset*take_rate, value, shape, tension, selected, true )
      end
    reaper.Envelope_SortPoints(env)
  end
end
```

**Comment by cfillion** [comment]
Same with "SWS/BR: Trim MIDI item to active content" which uses the same code as BR_SetItemEdges. The code is also used for some tempo-related actions, not sure if moving envelope points would affect those.

The code in question:

https://github.com/reaper-oss/sws/blob/b3ad441575f075d9232872f7873a6af83bb9de61/Breeder/BR_Util.cpp#L1081

**Comment by nofishonfriday** [comment]
Potential fix for testing (Win 64):
https://www.dropbox.com/s/6no74lzkbu13pk8/reaper_sws64.dll?dl=1

Should hopefully fix both, BR_SetItemEdges() and "SWS/BR: Trim MIDI item to active content".
Testing and feedback appreciated, if it works I'll do a PR.

**Comment by X-Raym** [comment]
@nofishonfriday Tested with various item and playrates and it seems to work !!

![Demo](https://i.imgur.com/0ngSWgO.gif)

Many thanks !

**Comment by nofishonfriday** [comment]
Nice, thanks for the quick feedback.
While you're at it, could you also test if it still works correctly if takes contain stretch markers (with rate other than 1.0) ?
(I have a fear it could break then, I didn't dare to test myself yet :P)

**Comment by nofishonfriday** [comment]
Previous version did break with SM's here, as I thought.
Hopefully also fixed in new version, please test again (with SM's):

https://www.dropbox.com/s/bsh18aqg0bjs3q8/reaper_sws64.dll?dl=1

**Comment by X-Raym** [comment]
@nofishonfriday 

It works in most case, but there is some issues:

![Demo](https://i.imgur.com/VJdnqL1.gif)

(item on top would be the expected behavior, it is the result we have if we extend items manually)

Here is a demo project.

https://www.dropbox.com/s/pm7nqcqoqh1gmd1/BrSetItemEdges.zip?dl=0

```lua
reaper.Undo_BeginBlock()
item = reaper.GetSelectedMediaItem(0,0)
if not item then item = reaper.GetMediaItem(0,0) end
reaper.BR_SetItemEdges(item, 10,30)
reaper.Undo_EndBlock("haha", -1)```

**Comment by X-Raym** [comment]
Also, there is some minor problem with Snap Offset in very particular cases

![demo](https://i.imgur.com/0nrVMPh.gif)

By hand with click and drag, snap offset stay in place.

In this case (item has some sort of incomplete pre-source extension), snap offset isn't preserve at the right absolute position.

**Comment by X-Raym** [comment]
@nofishonfriday 
I asked to Stretch Marker master MPL to take a look and he got pretty successful results !! 👍 

![Demo](https://i.imgur.com/4CRNEyR.gif)

```lua
reaper.Undo_BeginBlock()

item = reaper.GetSelectedMediaItem(0,0)

if not item then item = reaper.GetMediaItem(0,0) end



take = reaper.GetActiveTake(item)

pos1 = 0

pos2 = reaper.GetMediaItemInfo_Value( item, 'D_LENGTH' )* reaper.GetMediaItemTakeInfo_Value( take, 'D_PLAYRATE' )

reaper.SetTakeStretchMarker( take, -1, pos1 )

reaper.SetTakeStretchMarker( take, -1, pos2 )

it_pos = reaper.GetMediaItemInfo_Value( item, 'D_POSITION' )

t = {} for idx = 1,  reaper.GetTakeNumStretchMarkers( take ) do 

  local ID = #t+1

  t[ID] = {}

  _, t[ID].pos, t[ID].srcpos = reaper.GetTakeStretchMarker( take, idx -1)

  t[ID].slope = reaper.GetTakeStretchMarkerSlope( take, idx -1)

end



reaper.DeleteTakeStretchMarkers( take, 0, 10000000 )

reaper.BR_SetItemEdges(item, 10,30)

it_pos2 = reaper.GetMediaItemInfo_Value( item, 'D_POSITION' )

for i = 1, #t do  

  local idx = reaper.SetTakeStretchMarker( take, -1, t[i].pos+(it_pos-it_pos2)* reaper.GetMediaItemTakeInfo_Value( take, 'D_PLAYRATE' ), t[i].srcpos )

  reaper.SetTakeStretchMarkerSlope( take, idx, t[i].slope )

end

reaper.Undo_EndBlock("haha", -1)

reaper.UpdateArrange()```

Very close to what we get with manual extension (tough, the audio doesn't loop here before the stretch markers for some very weird reason. But the solutions should be close to MPL code).

(thanks again to MPL !!)

**Comment by X-Raym** [comment]
@nofishonfriday Oh Man, I found a very quick way to do it !!

[demo](https://i.imgur.com/mhildNv.gif)

The SetMediaItem edges could be rewritten just with edit cursor, and these trim actions. !!

**Comment by nofishonfriday** [comment]
> The BR_SetItemEdges could be rewritten just with edit cursor, and these trim actions !!

Doh, yes, this seems to work in this case. Needs to be careful though not to break the other functions which are using this code. I'll get back with a new test version soon.

Thanks for asking the stretch marker master (I had the same idea :D), and thanks mpl himself for providing code example.

**Comment by nofishonfriday** [comment]
New version fore testing:
https://www.dropbox.com/s/qrviacjl553dk6v/reaper_sws64.dll?dl=1

BR_SetItemEdges() now uses Trim... actions (instead of API).

If other @devs are following:
[This](https://github.com/nofishonfriday/sws/commit/535c07f7c5e72dd7cb9b381a472bb1bb6cd577f9) is the code I have currently, thoughts / suggestions appreciated.

**Comment by X-Raym** [comment]
@nofishonfriday seems to work perfectly !

**Comment by nofishonfriday** [comment]
Thanks for testing.

**Comment by X-Raym** [comment]
@nofishonfriday Hi ! There is a bug in the function, it works on every selected items instead of just the one which is pass as argument.

This is supposed to work on only one item:

```lua
item_1 = reaper.GetSelectedMediaItem(0,0)
reaper.BR_SetItemEdges( item_1, 2,4)
```

But it works on every selected items:

![Demo](https://i.imgur.com/IYBmUGM.gif)

Tested with SWS 2.9.8.

Can you reproduce ?

**Comment by nofishonfriday** [comment]
Oops, yeah, I see why this happens. Because the [now used native actions](https://github.com/reaper-oss/sws/commit/92ba71e97a742b984d33532e77436624a7243494#diff-944dfe20875d86377acc279ebcecf4d2R1132) work on _selected_ items, stupid from me not thinking about this.

So I think it means having to fiddle with stretch markers to properly fix which I suck at (as seen in previous fix attempt). I'll try but if anyone from the other contributers wants to to tackle this I'm not unhappy. :)

Anyway, the current 'fix' needs to be reverted.

**Comment by X-Raym** [comment]
@nofishonfriday you just need to handle unselection items then reselect them within the function :)
It is fast enough to do a good enough solution. And it should be straightfoward to implement, in reascript it is just 4 new lines . :P

**Comment by X-Raym** [comment]
@nofishonfriday Here is my current workarround on script side:

```lua
	for i, item in ipairs( sel_items ) do
		
		-- Workarround SWS BR_SetItemEdges Bug in v2.9.8
		reaper.SelectAllMediaItems(0, false)
		reaper.SetMediaItemSelected(item.item, true)
		
		reaper.BR_SetItemEdges( item.item, trim_pos, trim_end)
	
	end
	
	-- Workarround SWS BR_SetItemEdges Bug in v2.9.8
	for i, item in ipairs( sel_items ) do
		reaper.SetMediaItemSelected(item.item, true)
	end
```

It could be implemented in the API function itself.

**Comment by nofishonfriday** [comment]
Yeah I already thought about doing it this way. :D
I dunno, seems a little dirty somehow, but ok I guess (unless no one from the other devs chimes in).

**Comment by X-Raym** [comment]
@nofishonfriday it doesn't look extra efficient, but it has the great advantage of being 'simple to deploy' and backward compatible.
Most of all, it is friendly with all of our concerns (stretch markers etc...).

It is not even said that having to deal with this properly (by making calculation on stretch markers rather than saving items selection) would be that more efficient in performance, so I guess it is fully ok to do this trick 😁

**Comment by X-Raym** [comment]
@nofishonfriday All good ! I hope it could merge soon cause I have quite some scripts using this API function.
