### ISSUE TITLE
BR_Win32_WritePrivateProfileString crashes, when string keyName is set to nil.

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#956]
The following line crashes Reaper, which happens, when the second parameter is set to nil:

reaper.BR_Win32_WritePrivateProfileString("", **nil**, "", reaper.GetExePath().."\\reaper.ini")
The other parameter have no problem with being set to nil.

When I use GetResourcePath in it:

reaper.BR_Win32_WritePrivateProfileString("", nil, "", reaper.GetResourcePath().."\\reaper.ini")

Reaper doesn't crash but Lua behaves weird with the script not running anymore, as if Lua crashed on this specific script-instance...

Tested on portable installation of Reaper 5.70/x64 with SWS 2.9.7 on Windows 7.

**Comment by cfillion** [comment]
I can't reproduce. Both cases return false without crashing here. The nil is converted to an empty string by REAPER, which gives it to SWS, which in turn passes it straight to Windows.

**Comment by mespotine** [comment]
Ok, I'll check further. Maybe, if the passing of nil is really done by Reaper, it had been fixed somewhere in the last versions.

I'll check again with the newest versions(including the prereleases) and with non-portable...

**Comment by nofishonfriday** [comment]
Re-opening this as I saw the crash got repruduced.
https://forum.cockos.com/showthread.php?t=209749
