### ISSUE TITLE
SNM_GetIntConfigVar does not work for theme colors

### ISSUE THREAD

**Issue by juliansader** [reaper-oss/sws#958]
Theme colors are stored in the ini file, similar to other settings.  For example:
col_mi_label=4259584

However, SNM_GetIntConfigVar cannot return these values.

**Comment by swstim** [comment]
For SNM_GetIntConfigVar SWS just uses the REAPER API function "get_config_var" - we have no control over what it can and can't retrieve.

What language are you using?  Can you just parse the INI file manually?
