### ISSUE TITLE
Trouble building SWS on Mac

### ISSUE THREAD

**Issue by nofishonfriday** [reaper-oss/sws#963]
Rather a call for help than an actual 'issue'...

I've recently upgraded from Mountain Lion to High Sierra and now I'm having difficulties building SWS on Mac.
Apparently I can't run XCode 3.x (which is mentioned on the Wiki) anymore on High Sierra.
I've managed to integrate the 10.5 Base SDK (which is used by the SWS XCode project file) into the current XCode version. But when I try to build with the 10.5 Base SDK I get these errors:

![img](https://i.imgur.com/5Ud2C1n.jpg)

I can build without errors changing the base SDK to latest (10.13) but obviously I don't want to permanently change the SWS project file.

Any ideas how to solve this ?

**Comment by swstim** [comment]
Hmm... I have a virtual machine with OSX 10.6 just for building SWS because the tools are so out of date.
Unfortunately I don't have a great answer.  Maybe someone else has been successful with newer versions of XCode?

**Comment by nofishonfriday** [comment]
Thanks Tim.
I'm also using a VM for Mac debug / build, so no biggie going back to earler OSX (until maybe at some point the SWS project files will be updated. :D).

**Comment by swstim** [comment]
I have always tried to stay in step with official Reaper compatibility - since Reaper supports OSX 10.5+ I think we're basically stuck.  It is what it is.  Soonish I will setup an auto-build that will just build latest from GitHub and drop it somewhere on the web.
