### ISSUE TITLE
FR: B-Format Ambisonic Loudness Normalization based on first "W" (omni) channel only

### ISSUE THREAD

**Issue by BPBaker** [reaper-oss/sws#965]
Hello! This is part feature request and part question: how does SWS analyze multichannel/polywav audio files? Could we make a discreet loudness action for ambisonic files?

I've been using the SWS loudness normalization function to work with 4-channel first order ambisonic (B-format ambix) files, and I've noticed loudness appears to be calculated differently (about 4-5 db quieter) as opposed to the loudness of a mono or stereo file. Which makes sense, assuming the analysis is reading all four ambisonic channels. 

But in order to maintain consistent loudness, it seems to me that it's best to only calculate loudness based off the first channel of an ambisonic file, which is the omnidirectional sum of channels 2, 3 and 4 (the X, Y, and Z axis).  In essence, it would give the same loudness calculation as if the polywav were a mono file. 

I expect this would have to be a separate action for from other SWS loudness analysis actions in order to not disrupt loudness calculation for traditional mono, stereo, or multichannel surround files.

What do you think?

**Comment by nofishonfriday** [comment]
Workaround: Set channel mode to 'Mono (Left)' before analysing, as discussed [herer](https://forum.cockos.com/showthread.php?p=1971078#post1971078).
