### ISSUE TITLE
Building under Linux aborts (Can't locate reascript_helper.pl)

### ISSUE THREAD

**Issue by knochenhans** [reaper-oss/sws#970]
Hi, trying to build the current version under Arch Linux aborts with:
`Can't locate reascript_helper.pl in @INC (@INC contains: /usr/lib/perl5/5.26/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.26/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.26/core_perl /usr/share/perl5/core_perl) at reascript_python.pl line 9.
make: *** [Makefile:112: sws_python64.py] Error 2`

**Comment by mdmayfield** [comment]
I was able to resolve this by manually adding the following line to the beginning of `reascript_python.pl`, right after the initial comments:

```
BEGIN { unshift @INC, "."; }
```

**Comment by nofishonfriday** [comment]
@devs

Just so this doesn't get missed, anyone currently maintaining the SWS Linux build ?
(I could add this line for next build but I have no idea about Linux so I'd rather not.  :D)

**Comment by shane-axiom** [comment]
Another workaround is adding the source dir to PERL5LIB

```
PERL5LIB=. make
```

**Comment by cfillion** [comment]
Closing, this was fixed a while ago.
