### ISSUE TITLE
request: SWS - Wait for next bar/beat for OSX

### ISSUE THREAD

**Issue by estrica2000** [reaper-oss/sws#971]
originally i asked in general forum for a way to: "start recording after passing next cycle left locator" (https://forum.cockos.com/showthread....83#post1976583)

i was told the existence of SWS: Wait for next bar/beat which would help doing the task, but seems this actions are not available for OSX and so i request here

Thank you

**Comment by kennette21** [comment]
I am also interested in the SWS: Wait for next bar/beat! Would be great help with my project.

I am trying to trigger a track to mute only at hte end of the measure. If you send a mute message in the  middle of the measure, the track will wait till the end to mute.

any ideas welcome!!

**Comment by PrimevalMudd** [comment]
I could do with this for Linux too!
