### ISSUE TITLE
Feature request:  API for 'SWS/S&M: Set project startup action'

### ISSUE THREAD

**Issue by tparker24** [reaper-oss/sws#974]
I'd like to be able to invoke **'SWS/S&M: Set project startup action'**.  via an API from my reascript, but as far as I can tell, this is only available as an Action (and not through an API).

The drawback to the Action is that it requires user input (i.e.  "Paste command ID or identifier string here"), whereas I'd like my reascript to provide that.  

Similarly, for the companion actions:  '**SWS/S&M: Clear project startup action'** and **'SWS/S&M: Show project/global startup actions'**.  Especially the latter, where I'd like my reascript to be able to examine the current actions.

Thanks so much,
Tom****

**Comment by nofishonfriday** [comment]
![](https://i.imgur.com/VNHb4OI.jpg)

What are your system specs (Win/Mac, Reaper 32/64 bit) so I could build a version for testing ?

**Comment by nofishonfriday** [comment]
It'll still need a bit refinement, test version will come in the next day or two.

>  BTW, what are these "fast strings" that I see (and have used in others, like with Track Notes).  
It's a bit easier to implement on the SWS side (avoids having to deal with c-strings / char arrays and buffer sizes as they can expand automatically.) It comes from Cockos [WDL),](https://www.cockos.com/wdl/) library which is used in SWS extensions. The slight drawback is, that for use in scripts, the fast strings have to be created and destroyed manually.

**Comment by nofishonfriday** [comment]
https://www.dropbox.com/s/yz19k5yzy90noaq/reaper_sws64.dll?dl=1

Example code (Lua):
``
reaper.ClearConsole()

function msg(m)
  return reaper.ShowConsoleMsg(tostring(m) .. "\n")
end

-- project startup action ---
-- clear
reaper.NF_ClearProjectStartupAction()
msg("Proj startup action cleared!")

-- check
local projStartup_Desc = reaper.NF_GetProjectStartupAction_Desc('') -- returns empty string if not set
msg("Proj startup action desc: " .. projStartup_Desc)
local projStartup_CmdID = reaper.NF_GetProjectStartupAction_CmdID('') -- returns 0 if not set
msg("Proj startup action cmdID: " .. projStartup_CmdID)

-- set
reaper.NF_SetProjectStartupAction("_BR_MIDI_PROJ_TEMPO_ENB")
msg("Proj startup action set!")
-- NOTE: project must be saved after setting project startup action to be persistent

-- check
local projStartup = reaper.NF_GetProjectStartupAction_Desc('')
msg("Proj startup action desc: " .. projStartup)

local projStartup = reaper.NF_GetProjectStartupAction_CmdID('')
msg("Proj startup action CmdID: " .. projStartup)

msg("\n")

-- global startup action ---
-- clear
reaper.NF_ClearGlobalStartupAction()
msg("Global startup action cleared!")

-- check
local gblStartup = reaper.NF_GetGlobalStartupAction_Desc('')
msg("Gbl startup action desc: " .. gblStartup)
local gblStartup_CMDID = reaper.NF_GetGlobalStartupAction_CmdID('')
msg("Gbl startup action cmdID: " .. gblStartup_CMDID)

-- set
reaper.NF_SetGlobalStartupAction("40882") -- Global automation override: All automation in write mode
msg("Global startup action set!")

-- check
local gblStartup_Desc = reaper.NF_GetGlobalStartupAction_Desc('')
msg("Gbl startup action desc: " .. gblStartup_Desc)

local gblStartup_CmdID = reaper.NF_GetGlobalStartupAction_CmdID('')
msg("Gbl startup action CmdID: " .. gblStartup_CmdID)
``

If you test, let me know how it goes, if you find any quirks etc. :)

**Comment by tparker24** [comment]
Forgive me, I'm sorry, I should have mentioned that my Reascripts are all in 
*python*.

So, I believe I would need little python scripts to interface to 
'reaper_sws64.dll', like for example, these two that I use for TrackNotes that 
are in 'Plugins\sws_python.py' :


def NF_GetSWSTrackNotes(p0,p1):
   a=rpr_getfp('NF_GetSWSTrackNotes')
   f=CFUNCTYPE(c_char_p,c_uint64,c_uint64)(a)
t=(rpr_packp('MediaTrack*',p0),rpr_packp('WDL_FastString*',p1))
   r=f(t[0],t[1])
   return str(r.decode())


def NF_SetSWSTrackNotes(p0,p1):
   a=rpr_getfp('NF_SetSWSTrackNotes')
   f=CFUNCTYPE(None,c_uint64,c_char_p)(a)
   t=(rpr_packp('MediaTrack*',p0),rpr_packsc(p1))
   f(t[0],t[1])



So, I would need python scripts for, at least:

    NF_ClearProjectStartupAction()
    NF_GetProjectStartupAction_CmdID()
    NF_GetProjectStartupAction_Desc()
    NF_SetProjectStartupAction()


- Tom


nofish wrote on 5/3/2018 6:57 PM:

**Comment by nofishonfriday** [comment]
Took me a bit to figure this out, as I haven't done anything Python yet and it's not mentioned in the SWS build Wiki.

Anyway, I found that while building SWS it can automatically export the ReaScript Python functions (do the function wrapping) which it does via a Perl script which didn't work because I didn't have Perl installed.

Here:
https://www.dropbox.com/s/cz0mbmmxckyu0y3/sws_python.py?dl=1

So if you place this file in your REAPER/plugins folder (next to the reaper_sws64.dll and restart REAPER if currently running), and add 
```
from sws_python import *
```
to your Python script you hopefully should be able to use all the currents SWS functions including my newly added ones.
I tried with
```
NF_ClearGlobalStartupAction()
```
and it did work for me (i.e. no error on script execution).
Note:
If you open open sws_python.py in a text editor, it contains 'from reaper_python import *', so you needn't to import this separately to get the native REAPER API Python functions, but you may know this anyway.

**Comment by tparker24** [comment]
Hey, this is great!

I was having trouble at first, until I read your updated doc, to learn that there are actually TWO arguments to NF_GetProjectStartupAction_CmdID().

I was then able to exercise all four of the ProjectStartup versions, and they worked great!  (I didn't test the Global versions).


A couple of minor suggestions for the doc:

- In NF_GetProjectStartupAction_CmdID, where it says:

     Returns command ID number (native actions) or named command (extension/ReaScript) if project startup action is set, **otherwise 0**.

  It might be helpful to put that 0 in **quotes** "0", to emphasize that it's a string (and not an integer).  So:

   Returns command ID number (native actions) or named command (extension/ReaScript) if project startup action is set, **otherwise "0"**.

- Similarly, in NF_SetProjectStartupAction(), it might be helpful to put the string items in **quotes**.  E.g. 
  "_SWS_ABOUT, _f506bc780a0ab34b8fdedb67ed5d3649" and "47145".

- In NF_GetProjectStartupAction_Desc()

  it might be helpul to expand "Returns action **desc.**" to "Returns action **description**".


Good job and thanks very much.

Tom

**Comment by nofishonfriday** [comment]
Nice to hear it's working for you and thanks for the doc. suggestions, I'll put them in.

Btw., there's one part in there which is wrong in the current version for NF_GetGlobalStartupAction_CmdID()

It says "If ret. val. is from a native action or from extension/ReaScript can be checked with ReverseNamedCommandLookup.".
Correct would be one needs to check if returned value starts with a number (-> native action) or underscore (-> extension/ReaScript cmdID). 
I'll correct that too for the next version.

**Comment by tparker24** [comment]
Oh, here's a little typo:

The help for NF_SetProjectStartupAction() says:

        Returns true if **global** startup action was set successfully

I think that should be **project**.

**Comment by tparker24** [comment]
Tested all four of the GlobalStartup routines.  All went well.

**Thanks so much** for your great work on this "little" project.  I really appreciate it!

Oh, and any idea when the next production version of SWS (which includes the Startup stuff) might be coming out?

Tom

**Comment by nofishonfriday** [comment]
Typo is fixed already, thanks.
I'm not doing the SWS releases, so I don't know when next version will appear.

**Comment by StephanRoemer** [comment]
@nofishonfriday did this ever make it in the current release? 
I tried `projStartup_Desc = reaper.NF_GetProjectStartupAction_Desc('')` but get an error.

**Comment by nofishonfriday** [comment]
@StephanRoemer Sorry no, did not make it in a public release (yet).
The reason is (roughly) that we wanted to concentrate on fixes (rather than new features which themselves could introduce new bugs) until next major version of SWS is out.
I could do a SWS (test) build with these functions added though if you're interested.

**Comment by StephanRoemer** [comment]
Hey @nofishonfriday !
Ahh, gotcha, yes that makes sense, no worries.
Well I won't say no to a test build in this case! :)

**Comment by nofishonfriday** [comment]
Here you go:
https://www.dropbox.com/s/a6vgp3ge4vps91v/reaper_sws-x64-2.12.0.0%2BNF_%20global%20%20project%20startup%20action%20functions.dll?dl=1

Example code:
https://github.com/reaper-oss/sws/issues/974#issuecomment-386480161

If you test let me know how it goes. :)

**Comment by StephanRoemer** [comment]
Awesome, this works perfectly! 
I Tried: 

- retrieving the current project startup
- clearing it
- setting a new one
- retrieving it again

Looking forward to have this in the official build :)

**Comment by StephanRoemer** [comment]
Oopsie, had a crash with the extension when working in the MIDI editor 😄 
![image](https://user-images.githubusercontent.com/34496643/93599974-47639600-f9bf-11ea-8d14-ebd458b0f5d8.png)

**Comment by nofishonfriday** [comment]
Thanks. 
Which SWS version is that? I assume not the one from above as I named it differently, or did you rename it?
(Could you check Extensions > About SWS if in doubt?)

Also, do you have steps to reproduce ? That error message doesn't seem that helpful for debugging.

**Comment by StephanRoemer** [comment]
It is indeed the version from above (renamed it 😛) and renamed the official release to reaper_sws-x64.dll_orig.
Damn, I had hoped the message would be helpful. I can't say 100%, but I think I was just dragging a note or using 
"SWS/BR: Play from mouse cursor position". Will keep an eye on it and report back when I find out more details.

**Comment by StephanRoemer** [comment]
Hey nofish!

I just noticed: could we have that API for "SWS/BR: Project track selection action - Set..." as well?
That would be amazing!

Cheers,

Stephan

**Comment by nofishonfriday** [comment]
Yes, makes sense for consistency.
Done.

**Comment by StephanRoemer** [comment]
Thanks nofish!
