### ISSUE TITLE
FR: "SWS: Select previous folder" and "SWS: Select next folder" to be a little smarter

### ISSUE THREAD

**Issue by ScottChesworth** [reaper-oss/sws#981]
Hi,

Currently, these two actions only work when a folder track is selected. Would it be possible to modify them so that if a user is on a standard track when they trigger the actions, they land on the nearest folder in either direction?

Example: let's say I have 12 drum tracks contained within a folder called "Drum bus", followed by two bass tracks which aren't folders, and below those, let's say 6 guitar tracks contained within a folder called "Guitar bus".

Currently, to navigate between those two folders using the SWS actions, I have to have one of the existing folders selected first. IE, if my snare track is selected, it's not possible to hit the keystroke I've bound to "SWS: Select next folder" and move to the "Guitar bus" folder.

This change would make folder navigation way more intuitive, and be massively appreciated by a whole bunch of blind users that I'm involved in putting a keymap together for.

Thanks for considering,

Scott

**Comment by nofishonfriday** [comment]
Hi,
modifying existing actions is always a little problematic imo because of the risk of breaking existing workflows.

So I've added two new actions for the next SWS version called "SWS: Select nearest previous folder" and  "SWS: Select nearest next folder" which behave the way you're suggesting.

**Comment by ScottChesworth** [comment]
Thanks for the super speedy response! Point taken re modifying
existing actions, and many many thanks for adding the two new ones.
Looking forward to taking them for a spin whenever the next release
drops. :)

**Comment by nofishonfriday** [comment]
Test build (Win x64):
https://www.dropbox.com/s/vdwek7ynpv8wx66/reaper_sws64.dll?dl=1

**Comment by ScottChesworth** [comment]
Thanks dude. From my initial tests, these behave exactly as I was
hoping! I'll post back if the other testers discover anything weird.
