### ISSUE TITLE
Feature Request: Get/SetHWNDProperties() and GetWindowHWNDByName()

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#986]
I would like to suggest a function, with which I can get the properties of a HWND, like size, position, maximized-state, position of the inner "viewport-rectangle" inside the window(means, excluding the size of the window-frame itself), etc.
Currently, this isn't possible in ReaScript, although it would be really helpful to calculate a numerous things in a window. 
Like calculating positions of certain screenelements(e.g. arrangeview) of the Reaper-Main-Window, whose HWND I can get with GetMainHwnd().
Currently calculating position of screenelements is only possible within the Reaper-window, but if the position of Reaper's window changed, the coordinates are still in relation to the window, not to the position on the screen.

In addition to that, it would be cool to have a function, that returns the HWND of other opened windows from within Reaper, by using the title of the window.
Like: 

> GetWindowHWNDByName(string _windowtitle_, integer _windowinstance_)

where _windowtitle_ is the windowtitle whose HWND I would love to have, while _windowinstance_ is the idx for multiple windows with the same title.
This would allow for real cool stuff, like reprogramming clickable elements in the video-window, for which I need it's current position toread mouse-position and draw elements into the video-window properly.

**Comment by juliansader** [comment]
I am currently writing new SWS functions to expose a bunch of Win32 windows-related C++ functions to the Lua API. These will include:
Win32_FindWindow (Find the HWND to the window by titlebar text)
Win32_GetClientRect
and several others.

**Comment by mespotine** [comment]
Sounds great :)

Could you also add setting window-properties as well? This would be very helpful when working with Lua-GFX-Windows, that can be set only when opened, but after that, no chance to influence. how the window looks, works, the size of it.
Especially when I want to open a gfx-window for an OK-dialog, I can't set the window to fixed height/width. This would be great to do(and already wished in the Reaper-forums from time to time :) )

**Comment by mespotine** [comment]
Done in JS-extension and SWS.
