### ISSUE TITLE
SNM_GetStringConfigVar() and SNM_SetStringConfigVar()

### ISSUE THREAD

**Issue by mespotine** [reaper-oss/sws#987]
I don't know if this is possible at all, but I would love to have these two functions as well, to get access to string-config-variables. 
That way, I could update strings like recording-path, rendering-path or other things, that are strings that can't be changed by SNM_GetDoubleConfigVar, SNM_SetDoubleConfigVar, SNM_GetIntConfigVar and SNM_SetIntConfigVar.

**Comment by nofishonfriday** [comment]
You may want to check latest REAPER pre-release (v5.91pre2).
+ API: add get_config_var_string() for ReaScript

(no set... function though it seems...)

**Comment by mespotine** [comment]
I've looked into, how SNM did the setting of configvars, and is doing the following:

> bool SNM_SetDoubleConfigVar(const char* _varName, double _newVal) {
> 	if (double* pVar = (double*)(GetConfigVar(_varName))) {
> 		*pVar = _newVal;
> 		return true;
> 	}
> 	return false;
> }

It seems like, the function is getting the pointer to the variable, returned by GetConfigVar(), and then altering it. Maybe, this can be done with the new get_config_var_string()-function as well...
