### ISSUE TITLE
freeze with "Paste FX chain to selected tracks"

### ISSUE THREAD

**Issue by reaperblog** [reaper-oss/sws#992]
Step 1 - insert a vst
Step 2 - give a parameter a MIDI link like 14-bit CC 03,35
step 3 - SWS/S&M: Copy FX from selected track
step 4 - select some other tracks
step 5 - SWS/S&M: Paste FX chain to selected tracks

at this point there's a good chance reaper becomes unresponsive.

Was recording video one of the times it happened
https://www.youtube.com/watch?v=y0Fs75J1u5s

Fullsize screenshot is here https://imgur.com/Z0HgTs7

you can see 1 additional plugin was inserted but it's not seen in the track fx chains, the UI is broken and the toolbar button for paste fx is stuck pressed. App is unresponsive.

link to forum post
https://forum.cockos.com/showpost.php?p=1992206&postcount=2443

**Comment by nofishonfriday** [comment]
Observation here:
It only seems to happen if a copied / pasted FX is currently floating.
I.e. when they are in the FX chain or invisible when copy / pasting I don't get a freeze here, can you confirm ?

**Comment by reaperblog** [comment]
can confirm. It's interesting that the behavior is different depending on how the fx is displayed.

If the fx is floating then new floating windows will be shown. If just the fx chain is showing, no new windows or fx chains will pop up after paste. 

I also just tested and it's not limited to MIDI link, param mod with LFO + fx visible will freeze also.
No freezes without param mod or midi link.

**Comment by nofishonfriday** [comment]
These are exactly my findings.

I've been looking into the code and
> If the fx is floating then new floating windows will be shown. 
seems to be the culprit.

I've pushed a possible fix which seems to prevent the freeze but with the drawback that above would no longer apply, i.e. when copy / pasting floating FX they'd no longer appear floating but in the FX chain.

Actually I'm wondering if this behaviour could be improved on Reaper's side instead, because I'm not sure if it's strictly speaking 'a bug' on SWS side.

@devs
Opinions ?

**Comment by reaperblog** [comment]
I think not floating the fx, or fx-chain is a great solution.

**Comment by nofishonfriday** [comment]
Here's a build with the potential fix for testing if you want:
https://www.dropbox.com/s/helkd5g8tpbpbyz/reaper_sws_extension.zip?dl=1

(no installer, d'nd' into Application Support/REAPER/UserPlugins,overwriting existing one)

**Comment by reaperblog** [comment]
excellent, no problems with this version.

**Comment by nofishonfriday** [comment]
Thanks for testing.

The technical issue seems to be (from what I gather) that Reaper doesn't seem to like to get patched with a FX chain chunk that has a floating FX (FLOAT... line) **and** active MIDI link, param mod (<PROGRAMENV subchunk) which leads to the freeze.

I'll ask Justin if this could maybe be handled on Reaper's side (so we could keep the 'If the fx is floating then new floating windows will be shown.' feature, which I actually find nice.)

**Comment by justinfrankel** [comment]
Thanks, fixing for REAPER 5.91pre2.

**Comment by nofishonfriday** [comment]
Thanks Justin.
So closing this one.
