### ISSUE TITLE
FR: new action to cycle MIDI record mode

### ISSUE THREAD

**Issue by ScottChesworth** [reaper-oss/sws#994]
Hi,

Would it be possible to add an action that behaves similarly to "SWS/BR: cycle through recording modes"? It'd be super useful here to have all MIDI record modes accessible from a single keystroke.

If there are any specifics I can provide that would be helpful, just shout.

Thanks in advance.

**Comment by nofishonfriday** [comment]
Hi,

added 
- SWS/NF: Cycle through MIDI recording modes
- SWS/NF: Cycle through track automation modes (your FR #995)
for next SWS version.

A test build (Win x64) with these actions added is here:
https://www.dropbox.com/s/namu009mtgtvupt/reaper_sws64.dll?dl=1

If you get around to test, feedback is welcome...

**Comment by ScottChesworth** [comment]
Awesome!

I'll send that build to a small pool of testers here and give you a
shout if they find any bugs.

Much thanks for your work on this man :)

**Comment by ScottChesworth** [comment]
Actually, could I ask you for one more thing related to this? A few
weeks ago you added "SWS: Select nearest previous folder" and "SWS:
Select nearest next folder". Any chance you could shoot over a test
build with those actions incorporated too? There's an extra step that
the developer of my accessibility plugin has to do which triggers
spoken feedback automatically for the blind folks, and it'd be great
if he could test these actions ahead of release.

No pressure - I really should learn to build SWS myself here anyway,
so if you don't have time, this will be the reason for me to learn
stuff.

**Comment by nofishonfriday** [comment]
Added a test build for these actions in #981. 
(No worries, as I had SWS open anyway it was quick to do. :))
